---
- name: Run fault injection test
  hosts:
    - localhost
  tasks:
    - name: Import faults role
      ansible.builtin.import_role:
        name: faults
      vars:
        faults_cluster:
          kubeconfig: "{{ cluster.kubeconfig }}"
        faults_injection_tasks:
          - id: invalid-kubernetes-service-selector
            args:
              kubernetesObject:
                apiVersion: v1
                kind: Service
                metadata:
                  name: test-service
                  namespace: invalid-service-selector-test
