---
argument_specs:
  main:
    author:
      - Gerard Vanloo
    options:
      awx_cluster:
        options:
          kubeconfig:
            required: true
            type: str
          platform:
            choices:
              - kubernetes
              - openshift
            required: true
            type: str
          provider:
            required: true
            type: str
        required: true
        type: dict
      awx_configuration:
        options:
          agent:
            options:
              configuration:
                required: true
                type: dict
            required: false
            type: dict
          github:
            options:
              agent:
                options:
                  branch:
                    required: true
                    type: str
                  ssh:
                    options:
                      private_key_passphrase:
                        required: true
                        type: str
                      private_key_path:
                        required: true
                        type: str
                    required: false
                    type: dict
                  url:
                    required: true
                    type: str
                required: true
                type: dict
              itbench:
                options:
                  branch:
                    required: true
                    type: str
                  ssh:
                    options:
                      private_key_passphrase:
                        required: true
                        type: str
                      private_key_path:
                        required: true
                        type: str
                    required: false
                    type: dict
                  url:
                    required: true
                    type: str
                required: true
                type: dict
            required: true
            type: dict
          providers:
            options:
              aws:
                options:
                  enabled:
                    default: false
                    required: false
                    type: bool
                required: false
                type: dict
            required: false
            type: dict
          scenarios:
            elements: dict
            options:
              id:
                choices:
                  - 1
                  - 3
                  - 16
                  - 18
                  - 20
                  - 23
                  - 26
                  - 27
                  - 30
                  - 31
                  - 33
                  - 34
                  - 37
                  - 38
                  - 39
                  - 40
                  - 41
                  - 42
                  - 43
                  - 44
                  - 45
                  - 46
                  - 47
                  - 48
                  - 49
                  - 50
                  - 51
                  - 52
                  - 53
                  - 54
                  - 55
                  - 56
                  - 57
                  - 58
                  - 59
                  - 60
                  - 102
                  - 105
                required: true
                type: int
            required: true
            type: list
        required: false
        type: dict
      awx_experiments:
        options:
          agent:
            options:
              version:
                required: true
                type: str
            required: false
            type: dict
          runners:
            options:
              kubeconfigs:
                elements: str
                required: true
                type: list
            required: true
            type: dict
          storage:
            options:
              local:
                options:
                  directory:
                    required: true
                    type: str
                required: false
                type: dict
              s3:
                options:
                  bucket:
                    required: true
                    type: str
                  directory:
                    required: false
                    type: str
                  endpoint:
                    required: true
                    type: str
                required: false
                type: dict
            required: false
            type: dict
          trials:
            required: false
            type: int
          workflow:
            choices:
              - data
              - full
              - start
              - stop
            required: false
            type: str
        required: false
        type: dict
      awx_network_configuration:
        required: false
        type: dict
        options:
          cloud_provider_kind:
            required: false
            type: dict
