---
- name: Import waiter argument validation tasks
  ansible.builtin.import_tasks:
    file: validate_waiter_arguments.yaml

- name: Scale workload to 0 replicas
  kubernetes.core.k8s_scale:
    api_version: "{{ waiters_kubernetes_object.apiVersion }}"
    kind: "{{ waiters_kubernetes_object.kind }}"
    kubeconfig: "{{ waiters_cluster.kubeconfig }}"
    name: "{{ waiters_kubernetes_object.metadata.name }}"
    namespace: "{{ waiters_kubernetes_object.metadata.namespace }}"
    replicas: 0
    wait: true
    wait_timeout: 120

# NOTE: Since the workload may not be in a working state, the
#       following action does not wait for a success.

- name: Scale workload to original replica count
  kubernetes.core.k8s_scale:
    api_version: "{{ waiters_kubernetes_object.apiVersion }}"
    kind: "{{ waiters_kubernetes_object.kind }}"
    kubeconfig: "{{ waiters_cluster.kubeconfig }}"
    name: "{{ waiters_kubernetes_object.metadata.name }}"
    namespace: "{{ waiters_kubernetes_object.metadata.namespace }}"
    replicas: "{{ waiters_kubernetes_object.spec.replicas }}"
    wait: false
