---
- name: Import documentation role
  ansible.builtin.import_role:
    name: documentation
    tasks_from: load

- name: Create waiters `task_files` variable
  ansible.builtin.copy:
    content: "{{ lookup('ansible.builtin.template', 'templates/vars/task_files.j2') }}"
    dest: "{{ [role_path, 'vars', 'main', 'task_files.yaml'] | ansible.builtin.path_join }}"
    mode: "0644"
  vars:
    waiters: "{{ documentation_library_index.waiters }}"

- name: Create waiters roles meta argument specs file
  ansible.builtin.copy:
    content: "{{ lookup('ansible.builtin.template', 'templates/meta/argument_specs.j2') }}"
    dest: "{{ [role_path, 'meta', 'argument_specs.yaml'] | ansible.builtin.path_join }}"
    mode: "0644"
  vars:
    waiters: "{{ documentation_library_index.waiters }}"

- name: Create waiter tasks files
  ansible.builtin.copy:
    content: |+
      ---
      - name: Include waiter argument validation tasks
        ansible.builtin.include_tasks:
          file: validate_waiter_arguments.yaml

      - name: Print message
        ansible.builtin.debug:
          msg: This waiter ({{ waiter.id }}) is unimplemented.
    dest: "{{ [role_path, 'tasks', task_file_name] | ansible.builtin.path_join }}"
    force: false
    mode: "0644"
  loop: "{{ documentation_library_index.waiters }}"
  loop_control:
    label: waiter/{{ waiter.id }}
    loop_var: waiter
  vars:
    task_file_name: wait_{{ waiter.id | ansible.builtin.replace('-', '_') }}.yaml
