---
- name: Generate files from templates
  vars:
    waiters: "{{ generator_library_index.waiters }}"
  block:
    - name: Create waiters roles meta argument specs file
      ansible.builtin.template:
        dest: "{{ [role_path, 'meta', 'argument_specs.yaml'] | ansible.builtin.path_join }}"
        mode: "0644"
        src: templates/meta/argument_specs.j2

    - name: Create waiters `task_files` variable
      ansible.builtin.template:
        dest: "{{ [role_path, 'vars', 'main', 'task_files.yaml'] | ansible.builtin.path_join }}"
        mode: "0644"
        src: templates/vars/task_files.j2

    - name: Create waiters unimplemeneted wait task
      ansible.builtin.template:
        dest: "{{ [role_path, 'tasks', task_file_name] | ansible.builtin.path_join }}"
        force: false
        mode: "0644"
        src: templates/tasks/unimplemeneted_wait.j2
      loop: "{{ waiters }}"
      loop_control:
        label: waiter/{{ waiter.id }}
        loop_var: waiter
      vars:
        task_file_name: wait_{{ waiter.id | ansible.builtin.replace('-', '_') }}.yaml
