---
- name: Include wait tasks
  ansible.builtin.include_tasks:
    file: "{{ waiters_library_map[wait_task.id].taskFile }}"
    apply:
      tags:
        - inject_faults
      vars:
        waiter_args: "{{ wait_task.args }}"
  loop: "{{ waiters_tasks }}"
  loop_control:
    label: task/{{ wait_task.id }}
    loop_var: wait_task
  tags:
    - inject_faults
