---
- name: Import waiter argument validation tasks
  ansible.builtin.import_tasks:
    file: validate_waiter_arguments.yaml

- name: Restart only the deployments associated with the modified flags
  ansible.builtin.command:
    argv:
      - kubectl
      - -n
      - "{{ waiters_kubernetes_object.metadata.namespace }}"
      - rollout
      - restart
      - "{{ waiters_kubernetes_object.kind | ansible.builtin.lower }}"
      - "{{ waiters_kubernetes_object.metadata.name }}"
      - --kubeconfig={{ waiters_cluster.kubeconfig | ansible.builtin.expanduser }}
  register: waiters_rollout_restart_result
  changed_when:
    - waiters_rollout_restart_result.rc == 0
