---
- name: Include waiter argument validation tasks
  ansible.builtin.include_tasks:
    file: validate_waiter_arguments.yaml

- name: Scale workload
  kubernetes.core.k8s_scale:
    api_version: "{{ waiters_kubernetes_object.apiVersion }}"
    kind: "{{ waiters_kubernetes_object.kind }}"
    kubeconfig: "{{ waiters_cluster.kubeconfig }}"
    name: "{{ waiters_kubernetes_object.metadata.name }}"
    namespace: "{{ waiters_kubernetes_object.metadata.namespace }}"
    replicas: "{{ waiter_args.replicas }}"
    wait: true
    wait_timeout: 60
