---
- name: Include waiter argument validation tasks
  ansible.builtin.include_tasks:
    file: validate_waiter_arguments.yaml

- name: Restart workloads
  kubernetes.core.k8s:
    resource_definition:
      apiVersion: "{{ waiters_kubernetes_object.apiVersion }}"
      kind: "{{ waiters_kubernetes_object.kind }}"
      metadata:
        annotations:
          kubectl.kubernetes.io/restartedAt: "{{ now(utc=true, fmt='%Y-%m-%dT%H:%M:%SZ') }}"
        name: "{{ waiters_kubernetes_object.metadata.name }}"
        namespace: "{{ waiters_kubernetes_object.metadata.namespace }}"
    state: patched
