---
applications_managers:
  book_info:
    git:
      repository: "{{ packages.git_repositories.book_info.repository }}"
      tag: "{{ packages.git_repositories.book_info.tag }}"
    kubernetes:
      namespace: book-info
  opentelemetry_demo:
    helm:
      chart:
        reference: "{{ packages.helm_charts.opentelemetry_demo.registry }}"
        version: "{{ packages.helm_charts.opentelemetry_demo.version }}"
      release:
        name: otel-demo
    kubernetes:
      namespace: otel-demo
