applications_opentelemetry_demo_enabled: false
applications_opentelemetry_demo_kubernetes_autoscaling_enabled: false
applications_opentelemetry_demo_load_generator_browser_enabled: false
applications_opentelemetry_demo_load_generator_spawn_rate: 5
applications_opentelemetry_demo_load_generator_users: 50
