---
recorders_namespaces:
  data_recorders: data-recorders

recorders_instances:
  clickhouse_data_recorder:
    name: clickhouse-recorder
    namespace: "{{ recorders_namespaces.data_recorders }}"
  jaeger_data_recorder:
    name: jaeger-recorder
    namespace: "{{ recorders_namespaces.data_recorders }}"
  kubernetes_topology_monitor_data_recorder:
    name: kubernetes-topology-monitor-recorder
    namespace: "{{ recorders_namespaces.data_recorders }}"
  prometheus_data_recorder:
    name: prometheus-recorder
    namespace: "{{ recorders_namespaces.data_recorders }}"
