---
- name: Destroy test container
  hosts:
    - localhost
  tasks:
    - name: Remove container
      community.docker.docker_container:
        name: x11-forwarding-test
        state: absent
        force_kill: true
