FROM registry.access.redhat.com/ubi10/python-314-minimal:10.2-1791464217@sha256:8e385670e8a2ef3ca18f5bc3ef005a424601b58f2964d5a144861be544537624

WORKDIR /app

COPY pyproject.toml pyproject.toml

RUN python3.14 -m pip install --no-cache-dir .

COPY gather.py gather.py
COPY test_gather.py test_gather.py

ENTRYPOINT ["python3.14", "gather.py"]
