---
arguments:
  jsonSchema:
    properties:
      autoscaling:
        minProperties: 1
        properties:
          kubernetes:
            properties:
              hpa:
                default: false
                description: Enables autoscaling through Kubernetes Horizontal Pod Autoscaler. Defaults to false.
                type: boolean
            type: object
        type: object
    type: object
authors:
  - Istio
description: This microservice application is primarily used to showcase the capabitlities of Istio.
name: Book Info
platforms:
  - Kubernetes
repository: https://github.com/istio/istio
resources:
  - https://istio.io/latest/docs/examples/bookinfo/
  - https://istio.io/latest/docs/ambient/getting-started/deploy-sample-app/
