---
- name: Discover SRE and FinOps Incident Environment Sample Application Components
  hosts:
    - localhost
  tasks:
    - name: Import applications role
      ansible.builtin.import_role:
        name: applications
