---
- name: Manage SRE and FinOps Agent Namespace Access
  hosts:
    - localhost
  pre_tasks:
    - name: Import executables role
      ansible.builtin.import_role:
        name: executables
      tags:
        - always

    - name: Configure storage
      tags:
        - always
      block:
        - name: Override storage configuration
          ansible.builtin.set_fact:
            storage: |-
              {{
                lookup("ansible.builtin.template", template_path) |
                ansible.builtin.from_yaml
              }}
          vars:
            template_path: "{{ playbook_dir }}/templates/group_variables/storage.j2"
          when:
            - scenario_id is defined
            - storage is defined
            - storage_overrides is defined

        - name: Create directory for local storage export
          ansible.builtin.file:
            mode: "0755"
            path: "{{ storage.local.directory | ansible.builtin.default('/tmp') }}"
            state: directory
          when:
            - storage.local is defined
  tasks:
    - name: Import role variables from scenario
      tags:
        - grant_access
      when:
        - scenario_id is defined
      block:
        - name: Import scenarios role
          ansible.builtin.import_role:
            name: scenarios
          vars:
            scenarios_identifier: "{{ scenario_id }}"

        - name: Create fault injections variable
          ansible.builtin.set_fact:
            agent_access_request:
              namespaces: |-
                {{
                  (
                    (
                      scenarios_scenario.spec.faults |
                      map(attribute='injections') |
                      ansible.builtin.flatten |
                      ansible.builtin.selectattr('args.kubernetesObject.metadata.namespace', 'defined') |
                      map(attribute='args.kubernetesObject.metadata.namespace')
                    ) +
                    (
                      scenarios_scenario.spec.faults |
                      map(attribute='injections') |
                      ansible.builtin.flatten |
                      ansible.builtin.selectattr('args.kubernetesObject.kind', 'defined') |
                      ansible.builtin.selectattr('args.kubernetesObject.kind', '==', 'Namespace') |
                      map(attribute='args.kubernetesObject.metadata.name')
                    )
                  ) |
                  ansible.builtin.unique
                }}

        - name: Create storage variable
          ansible.builtin.set_fact:
            agent_storage: "{{ storage }}"
          when:
            - storage is defined

    - name: Import agent role
      ansible.builtin.import_role:
        name: agent
      vars:
        agent_cluster:
          kubeconfig: "{{ cluster.kubeconfig }}"
