---
- name: Manage SRE and FinOps Incident Environment Sample Application Stack
  hosts:
    - localhost
  environment:
    K8_AUTH_KUBECONFIG: "{{ cluster.kubeconfig }}"
  pre_tasks:
    - name: Import executables role
      ansible.builtin.import_role:
        name: executables
      tags:
        - always

    - name: Import cluster role
      ansible.builtin.import_role:
        name: cluster
      tags:
        - always
      vars:
        cluster_files:
          kubeconfig: "{{ cluster.kubeconfig }}"
  tasks:
    - name: Import applications role
      ansible.builtin.import_role:
        name: applications
      vars:
        applications_cluster:
          kubeconfig: "{{ cluster.kubeconfig }}"
          platform: "{{ cluster_platform }}"
