---
- name: Manage SRE and FinOps Agent Namespace Access
  hosts:
    - localhost
  pre_tasks:
    - name: Import executables role
      ansible.builtin.import_role:
        name: executables
      tags:
        - always

    - name: Create directory for local storage export
      ansible.builtin.file:
        mode: "0755"
        path: "{{ storage.local.directory | ansible.builtin.default('/tmp') }}"
        state: directory
      tags:
        - always
      when:
        - storage is ansible.builtin.defined
        - storage.local is ansible.builtin.defined
  tasks:
    - name: Grant agent access
      tags:
        - grant_access
      block:
        - name: Create temporary file for restricted kubeconfig
          ansible.builtin.tempfile:
            prefix: kubeconfig
            state: file
            suffix: .tmp
          register: agent_temporary_kubeconfig

        - name: Create restricted kubeconfig
          ansible.builtin.command:
            argv:
              - "{{ ansible_python_interpreter }}"
              - "{{ [playbook_dir, '..', '..', '..', 'scripts', 'agent', 'grant_access.py'] | ansible.builtin.path_join }}"
              - "{{ agent_temporary_kubeconfig.path }}"
          changed_when:
            - true

        - name: Copy restricted kubeconfig into local directory
          ansible.builtin.copy:
            dest: "{{ [storage.local.directory, 'kubeconfig'] | ansible.builtin.path_join }}"
            mode: "0644"
            src: "{{ agent_temporary_kubeconfig.path }}"
          when:
            - storage is ansible.builtin.defined
            - storage.local is ansible.builtin.defined

        - name: Upload restricted kubeconfig to S3 bucket
          amazon.aws.s3_object:
            endpoint_url: "{{ storage.s3.endpoint }}"
            bucket: "{{ storage.s3.bucket }}"
            object: "{{ [storage.s3.directory, 'kubeconfig'] | ansible.builtin.path_join }}"
            src: "{{ agent_temporary_kubeconfig.path }}"
            mode: put
          when:
            - storage is ansible.builtin.defined
            - storage.s3 is ansible.builtin.defined
      always:
        - name: Delete the temporary kubeconfig
          ansible.builtin.file:
            path: "{{ agent_temporary_kubeconfig.path }}"
            state: absent

    - name: Revoke agent access
      ansible.builtin.command:
        argv:
          - "{{ ansible_python_interpreter }}"
          - "{{ [playbook_dir, '..', '..', '..', 'scripts', 'agent', 'revoke_access.py'] | ansible.builtin.path_join }}"
      changed_when:
        - true
      tags:
        - revoke_access
