---
- name: Manage Argo Workflows Benchmark Orchestration
  hosts:
    - localhost
  pre_tasks:
    - name: Import executables role
      ansible.builtin.import_role:
        name: executables
      tags:
        - always

    - name: Import cluster role
      ansible.builtin.import_role:
        name: cluster
      tags:
        - always
  tasks:
    - name: Import Argo Workflows role
      ansible.builtin.import_role:
        name: argo
      vars:
        argo_runners: "{{ stack.environments }}"
