---
- name: Manage SRE and FinOps Resource Files
  hosts:
    - localhost
  tasks:
    - name: Generate and update files
      tags:
        - generate_files
      block:
        - name: Import awx role
          ansible.builtin.import_role:
            name: awx
            tasks_from: generate_files

        - name: Import faults role
          ansible.builtin.import_role:
            name: faults
            tasks_from: generate_files

        - name: Import waiters role
          ansible.builtin.import_role:
            name: waiters
            tasks_from: generate_files

        - name: Include scenarios role
          ansible.builtin.import_role:
            name: scenarios
            tasks_from: generate_files
