---
- name: Delete all agent access related ClusterRoleBindings
  kubernetes.core.k8s:
    api_version: rbac.authorization.k8s.io/v1
    delete_all: true
    kind: ClusterRoleBinding
    kubeconfig: "{{ agent_cluster.kubeconfig }}"
    label_selectors:
      - "app.kubernetes.io/component = agent-access-provider"
      - "app.kubernetes.io/managed-by = ITBench"
    state: absent
    wait: true

- name: Delete all agent access related ClusterRoles
  kubernetes.core.k8s:
    api_version: rbac.authorization.k8s.io/v1
    delete_all: true
    kind: ClusterRole
    kubeconfig: "{{ agent_cluster.kubeconfig }}"
    label_selectors:
      - "app.kubernetes.io/component = agent-access-provider"
      - "app.kubernetes.io/managed-by = ITBench"
    state: absent
    wait: true

- name: Delete all agent access related ServiceAccounts
  kubernetes.core.k8s:
    api_version: v1
    delete_all: true
    kind: ServiceAccount
    kubeconfig: "{{ agent_cluster.kubeconfig }}"
    label_selectors:
      - "app.kubernetes.io/component = agent-access-provider"
      - "app.kubernetes.io/managed-by = ITBench"
    namespace: default
    state: absent
    wait: true
