---
apiVersion: itbench.io/v2
kind: EvaluationCriteria
metadata:
  name: scenario-31
spec:
  checks:
    - alertName: HighRequestErrorRate
      backend: prometheus-alert-absent
    - alertName: NoRequestsReceived
      backend: prometheus-alert-absent
