---
- name: Retrieve all CustomResourceDefinitions
  kubernetes.core.k8s_info:
    api_version: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
  register: tools_custom_resource_definitions

- name: Delete Chaos Mesh related CustomResourceDefinitions
  kubernetes.core.k8s:
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    resource_definition: "{{ definitions }}"
    state: absent
    wait: true
  vars:
    definitions: |-
      {{
        tools_custom_resource_definitions.resources |
        ansible.builtin.selectattr("spec.group", "==", "chaos-mesh.org")
      }}
  when:
    - definitions | ansible.builtin.length > 0

- name: Delete Alinity Clickhouse Operator related CustomResourceDefinitions
  kubernetes.core.k8s:
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    resource_definition: "{{ definitions }}"
    state: absent
    wait: true
  vars:
    definitions: |-
      {{
        tools_custom_resource_definitions.resources |
        ansible.builtin.selectattr("spec.group", "search", "\.altinity\.com$")
      }}
  when:
    - definitions | ansible.builtin.length > 0

- name: Delete Istio related CustomResourceDefinitions
  kubernetes.core.k8s:
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    resource_definition: "{{ definitions }}"
    state: absent
    wait: true
  vars:
    definitions: |-
      {{
        tools_custom_resource_definitions.resources |
        ansible.builtin.selectattr("spec.group", "search", "\.istio\.io$")
      }}
  when:
    - definitions | ansible.builtin.length > 0

- name: Remove CustomResourceDefinitions not managed by OpenShift
  when:
    - tools_cluster.platform == "kubernetes"
  block:
    - name: Delete Kubernetes Gateway related CustomResourceDefinitions
      kubernetes.core.k8s:
        kubeconfig: "{{ tools_cluster.kubeconfig }}"
        resource_definition: "{{ definitions }}"
        state: absent
        wait: true
      vars:
        definitions: |-
          {{
            tools_custom_resource_definitions.resources |
            ansible.builtin.selectattr("spec.group", "==", "gateway.networking.k8s.io")
          }}
      when:
        - definitions | ansible.builtin.length > 0

    - name: Delete OpenTelemetry Operator related CustomResourceDefinitions
      kubernetes.core.k8s:
        kubeconfig: "{{ tools_cluster.kubeconfig }}"
        resource_definition: "{{ definitions }}"
        state: absent
        wait: true
      vars:
        definitions: |-
          {{
            tools_custom_resource_definitions.resources |
            ansible.builtin.selectattr("spec.group", "==", "opentelemetry.io")
          }}
      when:
        - definitions | ansible.builtin.length > 0

    - name: Delete cert-manager related CustomResourceDefinitions
      kubernetes.core.k8s:
        kubeconfig: "{{ tools_cluster.kubeconfig }}"
        resource_definition: "{{ definitions }}"
        state: absent
        wait: true
      vars:
        definitions: |-
          {{
            tools_custom_resource_definitions.resources |
            ansible.builtin.selectattr("spec.group", "search", "cert-manager\.io$")
          }}
      when:
        - definitions | ansible.builtin.length > 0

    - name: Delete Prometheus Operator related CustomResourceDefinitions
      kubernetes.core.k8s:
        kubeconfig: "{{ tools_cluster.kubeconfig }}"
        resource_definition: "{{ definitions }}"
        state: absent
        wait: true
      vars:
        definitions: |-
          {{
            tools_custom_resource_definitions.resources |
            ansible.builtin.selectattr("spec.group", "==", "monitoring.coreos.com")
          }}
      when:
        - definitions | ansible.builtin.length > 0
