---
- name: Destroy test resources
  hosts:
    - localhost
  tasks:
    - name: Delete test namespace
      kubernetes.core.k8s:
        kubeconfig: "{{ cluster.kubeconfig }}"
        resource_definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: strict-mtls-test
        state: absent
        wait: true

    - name: Uninstall Istio Base (CRDs)
      kubernetes.core.helm:
        kubeconfig: "{{ cluster.kubeconfig }}"
        release_name: istio-base
        release_namespace: istio-system
        release_state: absent
        wait: true

    - name: Delete Istio namespace
      kubernetes.core.k8s:
        kubeconfig: "{{ cluster.kubeconfig }}"
        resource_definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: istio-system

    - name: Import cluster role
      ansible.builtin.import_role:
        name: cluster
      vars:
        cluster_files:
          kubeconfig: "{{ cluster.kubeconfig }}"

    - name: Import tools role
      ansible.builtin.import_role:
        name: tools
        tasks_from: remove_custom_resource_definitions.yaml
      vars:
        tools_cluster:
          kubeconfig: "{{ cluster.kubeconfig }}"
          platform: "{{ cluster_platform }}"
          provider: "{{ cluster_provider }}"
