---
- name: Import OpenTelemetry Demo discovery tasks
  ansible.builtin.import_tasks:
    file: discover_opentelemetry_demo.yaml
  vars:
    out_directory: |-
      {{
        [
          playbook_dir,
          "..",
          "..",
          "..",
          ".itbench",
          "discovery",
          "opentelemetry-demo"
        ] |
        ansible.builtin.path_join
      }}
