---
- name: Import Book Info installation tasks
  ansible.builtin.import_tasks:
    file: install_book_info.yaml
  when:
    - applications_book_info_enabled

- name: Import OpenTelemetry Demo installation tasks
  ansible.builtin.import_tasks:
    file: install_opentelemetry_demo.yaml
  when:
    - applications_opentelemetry_demo_enabled
