---
# Note: The Prometheus offered by OpenShift is v2, while the one installed
#       in the chart is v3. While otel-demo supports the `otlphttp` exporter,
#       this is not easily exposed in OpenShift. So, ITBench uses the `prometheus`
#       exporter instead to support both platforms until the functionality of
#       Prometheus is the same on both platforms.

- name: Create Namespace
  kubernetes.core.k8s:
    resource_definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        labels:
          prometheus.itbench.io/monitor: "true"
        name: "{{ applications_releases.opentelemetry_demo.namespace }}"
    state: present

- name: Import tools role for variable setting tasks
  ansible.builtin.import_role:
    name: tools
    tasks_from: set_credentials_clickhouse
  vars:
    tools_cluster:
      kubeconfig: "{{ applications_cluster.kubeconfig }}"

- name: Import tools role for variable setting tasks
  ansible.builtin.import_role:
    name: tools
    tasks_from: set_internal_endpoints
  vars:
    tools_cluster:
      kubeconfig: "{{ applications_cluster.kubeconfig }}"
      platform: "{{ applications_cluster.platform }}"

- name: Create Service Account with `anyuid` access
  when:
    - applications_cluster.platform == "openshift"
  block:
    - name: Create ServiceAccount for OpenTelemetry Demo
      kubernetes.core.k8s:
        resource_definition:
          apiVersion: v1
          kind: ServiceAccount
          metadata:
            name: "{{ applications_releases.opentelemetry_demo.name }}"
            namespace: "{{ applications_releases.opentelemetry_demo.namespace }}"
        state: present

    - name: Create RoleBinding for access to anyuid SecurityContextConstraint
      kubernetes.core.k8s:
        resource_definition:
          kind: RoleBinding
          apiVersion: rbac.authorization.k8s.io/v1
          metadata:
            name: "{{ applications_releases.opentelemetry_demo.name }}"
            namespace: "{{ applications_releases.opentelemetry_demo.namespace }}"
          subjects:
            - kind: ServiceAccount
              name: "{{ applications_releases.opentelemetry_demo.name }}"
              namespace: "{{ applications_releases.opentelemetry_demo.namespace }}"
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: ClusterRole
            name: system:openshift:scc:anyuid
        state: present

- name: Install OpenTelemetry Demo (Astronomy Shop)
  kubernetes.core.helm:
    chart_ref: "oci://ghcr.io/open-telemetry/opentelemetry-helm-charts/opentelemetry-demo"
    chart_version: "0.42.3"
    release_name: "{{ applications_releases.opentelemetry_demo.name }}"
    release_namespace: "{{ applications_releases.opentelemetry_demo.namespace }}"
    release_state: present
    timeout: 10m0s
    values:
      serviceAccount:
        create: "{{ applications_cluster.platform != 'openshift' }}"
        name: "{{ applications_releases.opentelemetry_demo.name }}"
      components:
        accounting:
          podSecurityContext:
            runAsNonRoot: true
            runAsUser: 1654
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
        ad:
          resources:
            limits:
              cpu: 150m
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 256Mi
        fraud-detection:
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 256Mi
        image-provider:
          podSecurityContext:
            runAsNonRoot: true
            runAsUser: 101
        kafka:
          resources:
            limits:
              memory: 1024Mi
            requests:
              memory: 512Mi
        load-generator:
          envOverrides:
            - name: LOCUST_BROWSER_TRAFFIC_ENABLED
              value: "{{ applications_opentelemetry_demo_load_generator_browser_enabled | ansible.builtin.string }}"
            - name: LOCUST_SPAWN_RATE
              value: "{{ applications_opentelemetry_demo_load_generator_spawn_rate | ansible.builtin.string }}"
            - name: LOCUST_USERS
              value: "{{ applications_opentelemetry_demo_load_generator_users | ansible.builtin.string }}"
        product-catalog:
          resources:
            limits:
              memory: 160Mi
        recommendation:
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 128Mi
        valkey-cart:
          podSecurityContext:
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 999
      opentelemetry-collector:
        config:
          connectors:
            spanmetrics:
              dimensions:
                - name: namespace
                  default: "{{ applications_releases.opentelemetry_demo.namespace }}"
          exporters:
            clickhouse:
              username: "{{ tools_clickhouse_username }}"
              password: "{{ tools_clickhouse_password }}" # pragma: allowlist secret
              endpoint: "{{ tools_clickhouse_endpoint.http }}"
              logs_table_name: "otel_demo.logs"
            otlp/jaeger:
              endpoint: "{{ tools_jaeger_endpoint.collector.grpc }}"
            prometheus:
              endpoint: 0.0.0.0:8888
          service:
            pipelines:
              logs:
                exporters:
                  - clickhouse
                  - debug
              metrics:
                exporters:
                  - debug
                  - prometheus
              traces:
                exporters:
                  - debug
                  - otlp/jaeger
                  - spanmetrics
            telemetry:
              metrics:
                level: detailed
                readers:
                  - pull:
                      exporter:
                        prometheus:
                          host: 0.0.0.0
                          port: 8889
        mode: deployment
        presets:
          clusterMetrics:
            enabled: false
          hostMetrics:
            enabled: false
          kubeletMetrics:
            enabled: false
        serviceMonitor:
          enabled: true
          metricsEndpoints:
            - port: metrics
            - port: telemetry
        ports:
          jaeger-compact:
            enabled: false
          jaeger-thrift:
            enabled: false
          jaeger-grpc:
            enabled: false
          metrics:
            enabled: true
          telemetry:
            enabled: true
            containerPort: 8889
            servicePort: 8889
            protocol: TCP
          zipkin:
            enabled: false
      grafana:
        enabled: false
      jaeger:
        enabled: false
      opensearch:
        enabled: false
      prometheus:
        enabled: false
    wait: true

- name: Retrieve all pods
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Pod
    namespace: "{{ applications_releases.opentelemetry_demo.namespace }}"
  register: applications_otel_demo_pods

- name: Wait for pods to reach ready state
  kubernetes.core.k8s_info:
    api_version: "{{ pod.apiVersion }}"
    kind: "{{ pod.kind }}"
    name: "{{ pod.metadata.name }}"
    namespace: "{{ pod.metadata.namespace }}"
    wait: true
    wait_condition:
      type: Ready
      status: "True"
    wait_timeout: 300
  loop: "{{ applications_otel_demo_pods.resources }}"
  loop_control:
    label: "pod/{{ pod.metadata.name }}"
    loop_var: pod

- name: Retrieve all deployments
  kubernetes.core.k8s_info:
    api_version: apps/v1
    kind: Deployment
    namespace: "{{ applications_releases.opentelemetry_demo.namespace }}"
  register: applications_otel_demo_deployments

- name: Create HorizontalPodAutorscalers
  kubernetes.core.k8s:
    resource_definition:
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: "{{ workload.metadata.name }}"
        namespace: "{{ workload.metadata.namespace }}"
      spec:
        scaleTargetRef:
          apiVersion: "{{ workload.apiVersion }}"
          kind: "{{ workload.kind }}"
          name: "{{ workload.metadata.name }}"
        minReplicas: 1
        maxReplicas: 10
        metrics:
          - type: Resource
            resource:
              name: cpu
              target:
                type: Utilization
                averageUtilization: 70
          - type: Resource
            resource:
              name: memory
              target:
                type: Utilization
                averageUtilization: 80
        behavior:
          scaleDown:
            policies:
              - type: Percent
                value: 50
                periodSeconds: 60
              - type: Pods
                value: 2
                periodSeconds: 60
            selectPolicy: Min
    state: present
  loop: |-
    {{
      applications_otel_demo_deployments.resources |
      ansible.builtin.rejectattr('metadata.name', '==', 'load-generator') |
      ansible.builtin.rejectattr('metadata.name', '==', 'opentelemetry-collector')
    }}
  loop_control:
    label: deployment/{{ workload.metadata.name }}
    loop_var: workload
  when:
    - applications_opentelemetry_demo_kubernetes_autoscaling_enabled

- name: Create Common PrometheusRules
  kubernetes.core.k8s:
    template:
      path: templates/kubernetes/common/prometheusrules.j2
      variable_end_string: "]]"
      variable_start_string: "[["
    state: present
  vars:
    application_namespace: "{{ applications_releases.opentelemetry_demo.namespace }}"
    group_name: opentelemetrydemo

- name: Create OpenTelemetry Demo PrometheusRules
  kubernetes.core.k8s:
    template:
      path: templates/kubernetes/otel_demo/prometheusrules.j2
      variable_end_string: "]]"
      variable_start_string: "[["
    state: present
