---
- name: Delete Namespace
  kubernetes.core.k8s:
    resource_definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ applications_releases.book_info.namespace }}"
    state: absent
    wait: true
