---
arguments:
  jsonSchema:
    properties:
      seconds:
        minimum: 0
        type: integer
    required:
      - seconds
    type: object
description: Pauses for the requested number of seconds.
name: Pause Execution
platform: Any
