---
- name: Create kubeconfig credential type
  awx.awx.credential_type:
    controller_host: "{{ awx_controller_host }}"
    controller_password: "{{ awx_controller_password }}" # pragma: allowlist secret
    controller_username: admin
    description: Credentials type for Kubeconfig
    inputs:
      fields:
        - id: kubeconfig
          type: string
          label: kubeconfig
          secret: true
          multiline: true
      required:
        - kubeconfig
    injectors: "{{ lookup('ansible.builtin.file', 'files/awx/credential_types/kubeconfig_injectors.json') }}"
    kind: cloud
    name: Kubeconfig
    state: present

- name: Create kubeconfig credentials for each runner
  awx.awx.credential:
    controller_host: "{{ awx_controller_host }}"
    controller_password: "{{ awx_controller_password }}" # pragma: allowlist secret
    controller_username: admin
    credential_type: Kubeconfig
    description: Kubeconfig file for a Kubernetes cluster
    inputs:
      kubeconfig: "{{ lookup('ansible.builtin.file', kubeconfig) }}"
    name: Cluster-{{ kubeconfig_index + 1 }}-Kubeconfig
    organization: ITBench
  loop: "{{ awx_configuration.runners.kubeconfigs }}"
  loop_control:
    index_var: kubeconfig_index
    label: kubeconfig/{{ kubeconfig | ansible.builtin.basename }}
    loop_var: kubeconfig

- name: Create credentials for AWS Cloud Provider
  when:
    - awx_configuration.providers.aws.enabled | ansible.builtin.default(false)
  block:
    - name: Retrieve AWS access key id
      ansible.builtin.command:
        argv:
          - aws
          - configure
          - get
          - aws_access_key_id
      register: awx_aws_access_key_id_output
      changed_when:
        - false

    - name: Retrieve AWS secret access key
      ansible.builtin.command:
        argv:
          - aws
          - configure
          - get
          - aws_secret_access_key
      register: awx_aws_secret_access_key_output
      changed_when:
        - false

    - name: Create credentials for AWS
      awx.awx.credential:
        controller_host: "{{ awx_controller_host }}"
        controller_password: "{{ awx_controller_password }}" # pragma: allowlist secret
        controller_username: admin
        credential_type: Amazon Web Services
        description: Credentials for AWS
        inputs:
          username: "{{ awx_aws_access_key_id_output.stdout }}"
          password: "{{ awx_aws_secret_access_key_output.stdout }}" # pragma: allowlist secret
        name: AWS
        organization: ITBench
        state: present

- name: Create credentials for GitHub repositories
  awx.awx.credential:
    controller_host: "{{ awx_controller_host }}"
    controller_password: "{{ awx_controller_password }}" # pragma: allowlist secret
    controller_username: admin
    credential_type: Source Control
    description: "SSH Credentials for {{ repository.description }}"
    inputs:
      ssh_key_data: "{{ lookup('ansible.builtin.file', repository.configuration.ssh.private_key_path) }}"
      ssh_key_unlock: "{{ repository.configuration.ssh.private_key_passphrase }}"
    name: "{{ repository.name }}"
    organization: ITBench
    state: present
  loop:
    - name: GitHub-ITBench
      description: ITBench GitHub repository
      configuration: "{{ awx_configuration.github.itbench }}"
      is_required: "{{ awx_configuration.github.itbench.ssh is defined }}"
    - name: GitHub-LLM-Agent
      description: LLM agent repository
      configuration: "{{ awx_configuration.github.agent }}"
      is_required: "{{ awx_configuration.github.agent.ssh is defined }}"
  loop_control:
    label: credential/{{ repository.name }}
    loop_var: repository
  when:
    - repository.is_required
