---
- name: Import documentation role
  ansible.builtin.import_role:
    name: documentation
    tasks_from: load

- name: Create awx roles meta argument specs file
  ansible.builtin.copy:
    content: |-
      {{
        lookup('ansible.builtin.template', 'templates/meta/argument_specs.j2') |
        ansible.builtin.from_yaml |
        ansible.builtin.to_nice_yaml(explicit_start=true, indent=2)
      }}
    dest: |-
      {{
        [
          role_path,
          "meta",
          "argument_specs.yaml"
        ] |
        ansible.builtin.path_join
      }}
    mode: "0644"
  vars:
    scenario_ids: "{{ documentation_library_index.scenarios | map(attribute='id') }}"
