---
- name: Generate files from templates
  vars:
   scenarios: "{{ generator_library_index.scenarios }}"
  block:
    - name: Create awx roles meta argument specs file
      ansible.builtin.template:
        dest: "{{ [role_path, 'meta', 'argument_specs.yaml'] | ansible.builtin.path_join }}"
        mode: "0644"
        src: templates/meta/argument_specs.j2

    - name: Create awx `scenario_fault_count` variable
      ansible.builtin.template:
        dest: "{{ [role_path, 'vars', 'main', 'scenario_fault_count.yaml'] | ansible.builtin.path_join }}"
        mode: "0644"
        src: templates/vars/scenario_fault_count.j2
