---
- name: Import AWX operator installation tasks
  ansible.builtin.import_tasks:
    file: install_awx_operator.yaml

- name: Import AWX instance installation tasks
  ansible.builtin.import_tasks:
    file: install_awx_instances.yaml

- name: Import variable setting tasks
  ansible.builtin.import_tasks:
    file: set_awx_controller_host.yaml

- name: Import variable setting tasks
  ansible.builtin.import_tasks:
    file: set_awx_controller_password.yaml

- name: Display login details
  ansible.builtin.debug:
    msg:
      - "AWX Website: {{ awx_controller_host }}"
      - "AWX Username: admin"
      - "AWX Password: {{ awx_controller_password }}"
