---
- name: Install AWX operator
  kubernetes.core.helm:
    chart_ref: awx-operator
    chart_repo_url: "https://ansible-community.github.io/awx-operator-helm"
    chart_version: "3.2.1"
    create_namespace: true
    kubeconfig: "{{ awx_cluster.kubeconfig }}"
    release_name: "{{ awx_releases.awx_operator.name }}"
    release_namespace: "{{ awx_operands.awx.main.namespace }}"
    release_state: present
    timeout: 10m0s
    wait: true
