---
- name: Uninstall AWX
  kubernetes.core.k8s:
    kubeconfig: "{{ awx_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: awx.ansible.com/v1beta1
      kind: AWX
      metadata:
        name: "{{ awx_operands.awx.main.name }}"
        namespace: "{{ awx_operands.awx.main.namespace }}"
    state: absent
    wait: true
