---
awx_managers:
  awx_operator:
    helm:
      chart:
        reference: "{{ packages.helm_charts.awx_operator.name }}"
        repository: "{{ packages.helm_charts.awx_operator.repository }}"
        version: "{{ packages.helm_charts.awx_operator.version }}"
      release:
        name: awx-operator
    instances:
      names:
        main: awx-deployment
    kubernetes:
      namespace: awx
