---
- name: Create Docker registry secret
  kubernetes.core.k8s:
    kubeconfig: "{{ docker_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: v1
      kind: Secret
      type: kubernetes.io/dockerconfigjson
      metadata:
        name: regcred
        namespace: default
      stringData:
        .dockerconfigjson: >-
          {{
            {
              "auths": {
                docker_registry.server: {
                  "auth": (auth | ansible.builtin.b64encode),
                  "email": docker_registry.email,
                  "password": password,
                  "username": docker_registry.username
                }
              }
            } |
            ansible.builtin.to_json
          }}
    state: present
  vars:
    auth: "{{ docker_registry.username ~ ':' ~ docker_registry.password }}" # pragma: allowlist secret
    password: "{{ docker_registry.password }}" # pragma: allowlist secret
