---
- name: Install Kubernetes Gateway API Custom Resource Definitions
  block:
    - name: Create temporary directory for install files
      ansible.builtin.tempfile:
        prefix: k8s_gateway
        state: directory
      register: tools_install_directory

    - name: Download Gateway API files from standard release channel
      ansible.builtin.get_url:
        dest: "{{ tools_install_directory.path }}"
        mode: "0644"
        url: "https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.6.3/standard-install.yaml"

    - name: Apply Custom Resource Definitions to cluster
      kubernetes.core.k8s:
        apply: true
        kubeconfig: "{{ tools_cluster.kubeconfig }}"
        server_side_apply:
          field_manager: ansible
        src: "{{ [tools_install_directory.path, 'standard-install.yaml'] | ansible.builtin.path_join }}"
        state: present
  always:
    - name: Delete the temporary directory
      ansible.builtin.file:
        path: "{{ tools_install_directory.path }}"
        state: absent
