---
- name: Install Prometheus Operator Custom Resource Definitions
  kubernetes.core.helm:
    chart_ref: "oci://ghcr.io/prometheus-community/charts/prometheus-operator-crds"
    chart_version: "32.0.1"
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    release_name: "{{ tools_releases.prometheus_operator_crds.name }}"
    release_namespace: "{{ tools_releases.prometheus_operator_crds.namespace }}"
    release_state: present
    timeout: 10m0s
    wait: true
