---
- name: Apply Kubernetes Gateway API Custom Resource Definitions
  block:
    - name: Create temporary file for Kubernetes Gateway API CRD manifest
      ansible.builtin.tempfile:
        suffix: .yaml
      register: tools_kubernetes_gateway_api_manifest

    - name: Download Kubernetes Gateway API CRD manifest
      ansible.builtin.get_url:
        dest: "{{ tools_kubernetes_gateway_api_manifest.path }}"
        mode: "0644"
        url: "https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.6.2/standard-install.yaml"

    - name: Apply Kubernetes Gateway API Custom Resource Definitions
      kubernetes.core.k8s:
        src: "{{ tools_kubernetes_gateway_api_manifest.path }}"
        state: present
        server_side_apply:
          field_manager: ansible

    - name: Create Namespace for Kubernetes Gateway instances
      kubernetes.core.k8s:
        resource_definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            labels:
              "prometheus.itbench.io/monitor": "true"
            name: "{{ tools_kubernetes_gateways.istio.namespace }}"
        state: present
  always:
    - name: Delete temporary file for Kubernetes Gateway API CRD manifest
      ansible.builtin.file:
        path: "{{ tools_kubernetes_gateway_api_manifest.path }}"
        state: absent
