---
- name: Create Namespace for Clickhouse Operator
  kubernetes.core.k8s:
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        labels:
          "prometheus.itbench.io/monitor": "true"
        name: "{{ tools_releases.alinity_clickhouse_operator.namespace }}"
    state: present

- name: Install Clickhouse Operator
  kubernetes.core.helm:
    chart_ref: "oci://ghcr.io/altinity/clickhouse-operator-helm-chart/altinity-clickhouse-operator"
    chart_version: "0.27.2"
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    release_name: "{{ tools_releases.alinity_clickhouse_operator.name }}"
    release_namespace: "{{ tools_releases.alinity_clickhouse_operator.namespace }}"
    release_state: present
    timeout: 10m0s
    values:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.itbench.io/sandbox
                    operator: DoesNotExist
      configs:
        files:
          config.yaml:
            watch:
              namespaces:
                - "{{ tools_operands.alinity_clickhouse.main.namespace }}"
      serviceMonitor:
        enabled: true
    wait: true
