---
- name: Create Route for Clickhouse
  kubernetes.core.k8s:
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: route.openshift.io/v1
      kind: Route
      metadata:
        name: "{{ tools_operands.alinity_clickhouse.main.name }}"
        namespace: "{{ tools_operands.alinity_clickhouse.main.namespace }}"
      spec:
        httpHeaders:
          actions:
            response: "{{ route_response_headers }}"
        port:
          targetPort: 8123
        to:
          kind: Service
          name: clickhouse-{{ tools_operands.alinity_clickhouse.main.name }}
    state: present

- name: Create Route for Jaeger
  kubernetes.core.k8s:
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: route.openshift.io/v1
      kind: Route
      metadata:
        name: "{{ tools_operands.opentelemetry_collector.jaeger.name }}"
        namespace: "{{ tools_operands.opentelemetry_collector.jaeger.namespace }}"
      spec:
        httpHeaders:
          actions:
            response: "{{ route_response_headers }}"
        path: /jaeger
        port:
          targetPort: 16686
        to:
          kind: Service
          name: "{{ tools_operands.opentelemetry_collector.jaeger.name }}-collector"
    state: present

- name: Create Route for Kubernetes Topology Monitor
  kubernetes.core.k8s:
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: route.openshift.io/v1
      kind: Route
      metadata:
        name: "{{ tools_releases.kubernetes_topology_monitor.name }}"
        namespace: "{{ tools_releases.kubernetes_topology_monitor.namespace }}"
      spec:
        httpHeaders:
          actions:
            response: "{{ route_response_headers }}"
        port:
          targetPort: 8080
        to:
          kind: Service
          name: topology-monitor-svc
    state: present
  when:
    - tools_configuration.sre.enabled | ansible.builtin.default(false)

- name: Create Route for OpenCost
  kubernetes.core.k8s:
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: route.openshift.io/v1
      kind: Route
      metadata:
        name: "{{ tools_releases.opencost.name }}"
        namespace: "{{ tools_releases.opencost.namespace }}"
      spec:
        httpHeaders:
          actions:
            response: "{{ route_response_headers }}"
        port:
          targetPort: 9090
        to:
          kind: Service
          name: "{{ tools_releases.opencost.name }}"
    state: present
  when:
    - tools_configuration.finops.enabled | ansible.builtin.default(false)
