---
- name: Import Kubernetes Gateway API installation tasks
  ansible.builtin.import_tasks:
    file: install_kubernetes_gateway_api.yaml
  when:
    - tools_cluster.platform == "kubernetes"

- name: Import Prometheus Operator CRD installation tasks
  ansible.builtin.import_tasks:
    file: install_prometheus_operator_crds.yaml
  when:
    - tools_cluster.platform == "kubernetes"

- name: Import Kubernetes Gateway installation tasks
  ansible.builtin.import_tasks:
    file: install_kubernetes_gateway.yaml

- name: Install SRE and FinOps Tools
  when:
    - ((tools_configuration.finops.enabled | ansible.builtin.default(false)) or (tools_configuration.sre.enabled | ansible.builtin.default(false)))
  block:
    - name: Import Clickhouse installation tasks
      ansible.builtin.import_tasks:
        file: install_clickhouse.yaml

    - name: Import Prometheus installation tasks
      ansible.builtin.import_tasks:
        file: install_prometheus.yaml

    - name: Import Prometheus endpoint variable setting tasks
      ansible.builtin.import_tasks:
        file: set_internal_endpoints_prometheus.yaml

    - name: Import OpenTelemetry installation tasks
      ansible.builtin.import_tasks:
        file: install_opentelemetry.yaml

    - name: Import Kubernetes Metrics Server installation tasks
      ansible.builtin.import_tasks:
        file: install_kubernetes_metrics_server.yaml

    - name: Import cert-manager installation tasks
      ansible.builtin.import_tasks:
        file: install_cert_manager.yaml

    - name: Install FinOps specific tools
      when:
        - tools_configuration.finops.enabled | ansible.builtin.default(false)
      block:
        - name: Import OpenCost installation tasks
          ansible.builtin.import_tasks:
            file: install_opencost.yaml

    - name: Install SRE specific tools
      when:
        - tools_configuration.sre.enabled | ansible.builtin.default(false)
      block:
        - name: Import Chaos Mesh installation tasks
          ansible.builtin.import_tasks:
            file: install_chaos_mesh.yaml

        - name: Import Kubernetes Topology Monitor installation tasks
          ansible.builtin.import_tasks:
            file: install_kubernetes_topology_monitor.yaml

    - name: Import Istio installation tasks
      ansible.builtin.import_tasks:
        file: install_istio.yaml
