---
- name: Create GatewayClass for OpenShift Ingress
  kubernetes.core.k8s:
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: gateway.networking.k8s.io/v1
      kind: GatewayClass
      metadata:
        name: openshift-default
      spec:
        controllerName: openshift.io/gateway-controller/v1
    state: present
    wait: true
    wait_condition:
      type: Accepted
      status: "True"
  when:
    - tools_cluster.platform == "openshift"

- name: Create Namespaces for Kubernetes Gateways
  kubernetes.core.k8s:
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        labels:
          "app.kubernetes.io/component": gateway
          "prometheus.itbench.io/monitor": "true"
        name: "{{ gateway.namespace }}"
    state: present
  loop:
    - "{{ tools_kubernetes_gateway_istio }}"
  loop_control:
    label: namespace/{{ gateway.namespace }}
    loop_var: gateway
  when:
    - tools_cluster.platform == "kubernetes"

- name: Create OpenShift implemented Kubernetes Gateway
  kubernetes.core.k8s:
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: gateway.networking.k8s.io/v1
      kind: Gateway
      metadata:
        name: "{{ tools_kubernetes_gateway_openshift.name }}"
        namespace: "{{ tools_kubernetes_gateway_openshift.namespace }}"
      spec:
        gatewayClassName: openshift-default
        listeners:
          - name: http
            port: 80
            protocol: HTTP
            allowedRoutes:
              namespaces:
                from: Selector
                selector:
                  matchLabels:
                    "itbench.io/gateway-access": shared
    state: present
    wait: true
    wait_condition:
      status: "True"
      type: Programmed
  when:
    - tools_cluster.platform == "openshift"
