---
- name: Retrieve all namespaces
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Namespace
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
  register: tools_namespaces

- name: Validate that namespaces exists
  ansible.builtin.assert:
    that:
      - tools_namespaces.api_found
      - tools_namespaces.resources | ansible.builtin.length > 0
    fail_msg: No namespaces were found. Please ensure that tool installation completed successfully.
    success_msg: Namespaces found.

- name: Map resources to names list
  ansible.builtin.set_fact:
    tools_namespaces_names: "{{ tools_namespaces.resources | map(attribute='metadata.name') }}"

- name: Validate that Kubernetes Gateway instance namespace exists
  ansible.builtin.assert:
    that:
      - tools_managers.kubernetes_gateway.instances.kubernetes.namespace in tools_namespaces_names
    fail_msg: Kubernetes Gateway namespace does not exist. Please ensure tool installation was successful.
    success_msg: Kubernetes Gateway namespace exists.

- name: Retrieve Istio managed Gateway
  kubernetes.core.k8s_info:
    api_version: gateway.networking.k8s.io/v1
    kind: Gateway
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    name: "{{ tools_managers.kubernetes_gateway.instances.names.istio }}"
    namespace: "{{ tools_managers.kubernetes_gateway.instances.kubernetes.namespace }}"
  register: tools_istio_gateway
  until:
    - tools_istio_gateway.resources | ansible.builtin.length == 1
    - tools_istio_gateway.resources[0].status.addresses is defined
    - tools_istio_gateway.resources[0].status.addresses | ansible.builtin.length > 0
  delay: 15
  retries: 20

- name: Extract Kubernetes Gateway address
  when:
    - tools_cluster.platform == "kubernetes"
    - (tools_cluster.provider != "kind") or (tools_cluster.provider == "kind" and ansible_system == "Linux")
  block:
    - name: Extract ip address information
      ansible.builtin.set_fact:
        tools_gateway_http_address: http://{{ tools_istio_gateway.resources[0].status.addresses[0].value }}:80
      when:
        - tools_istio_gateway.resources[0].status.addresses[0].type == "IPAddress"

    - name: Extract hostname address information
      ansible.builtin.set_fact:
        tools_gateway_http_address: http://{{ tools_istio_gateway.resources[0].status.addresses[0].value }}
      when:
        - tools_istio_gateway.resources[0].status.addresses[0].type == "Hostname"

- name: Extract localhost address from container runtime
  vars:
    istio_gateway_service:
      name: "{{ tools_managers.kubernetes_gateway.instances.names.istio }}-istio"
      namespace: "{{ tools_managers.kubernetes_gateway.instances.kubernetes.namespace }}"
  when:
    - tools_cluster.provider == "kind" and ansible_system == "Darwin"
  block:
    - name: Fail playbook for `invalid network configuration` error
      ansible.builtin.fail:
        msg: "Network settings for cloud provider kind have not been provided."
      when:
        - tools_network_configuration is undefined
        - tools_network_configuration.cloud_provider_kind is undefined
        - tools_network_configuration.cloud_provider_kind[istio_gateway_service.namespace] is undefined
        - tools_network_configuration.cloud_provider_kind[istio_gateway_service.namespace][istio_gateway_service.name] is undefined

    - name: Create localhost address based on service provider
      ansible.builtin.set_fact:
        tools_gateway_http_address: http://localhost:{{ host_port }}
      vars:
        host_port: "{{ tools_network_configuration.cloud_provider_kind[istio_gateway_service.namespace][istio_gateway_service.name]['host_port'] }}"

- name: Validate that address has been parsed
  ansible.builtin.assert:
    that:
      - tools_gateway_http_address is defined
    fail_msg: External address could not be determined.
    success_msg: External address determined.

- name: Import Clickhouse variable setting tasks
  ansible.builtin.import_tasks:
    file: set_external_endpoints_clickhouse.yaml
  when:
    - tools_managers.clickhouse_operator.instances.kubernetes.namespace in tools_namespaces_names

- name: Import Jaeger variable setting tasks
  ansible.builtin.import_tasks:
    file: set_external_endpoints_jaeger.yaml
  when:
    - tools_managers.opentelemetry_operator.instances.kubernetes.namespace in tools_namespaces_names

- name: Import Kubernetes Topology Monitor variable setting tasks
  ansible.builtin.import_tasks:
    file: set_external_endpoints_kubernetes_topology_monitor.yaml
  when:
    - tools_managers.kubernetes_topology_monitor.kubernetes.namespace in tools_namespaces_names

- name: Import OpenCost variable setting tasks
  ansible.builtin.import_tasks:
    file: set_external_endpoints_opencost.yaml
  when:
    - tools_managers.opencost.kubernetes.namespace in tools_namespaces_names

- name: Import Prometheus variable setting tasks
  ansible.builtin.import_tasks:
    file: set_external_endpoints_prometheus.yaml
  when:
    - (
        ("openshift-monitoring" in tools_namespaces_names) or
        (tools_managers.prometheus.kubernetes.namespace in tools_namespaces_names)
      )
