---
- name: Retrieve current cluster from kubeconfig
  ansible.builtin.set_fact:
    tools_current_cluster: |-
      {{
        kubeconfig.clusters |
        ansible.builtin.selectattr("name", "==", kubeconfig["current-context"])
      }}
  vars:
    kubeconfig: |-
      {{
        lookup("ansible.builtin.file", (tools_cluster.kubeconfig | ansible.builtin.expanduser)) |
        ansible.builtin.from_yaml
      }}

- name: Validate that there is only one context
  ansible.builtin.assert:
    that:
      - tools_current_cluster | ansible.builtin.length == 1
    fail_msg: More than one context discovered. Please ensure kubeconfig is properly formatted.
    success_msg: Context discovered.

- name: Import container runtime check tasks
  ansible.builtin.import_tasks:
    file: check_container_runtime_status.yaml
  vars:
    binary_name: docker

- name: Import container runtime check tasks
  ansible.builtin.import_tasks:
    file: check_container_runtime_status.yaml
  vars:
    binary_name: podman

- name: Fail with `no container runtime active` error
  ansible.builtin.fail:
    msg: Neither `docker` or `podman` is running. Please ensure Cloud Provider Kind is running using one of these tools.
  when:
    - tools_docker_path is undefined
    - tools_podman_path is undefined

- name: Retrieve Cloud Provider Kind load balancer container
  vars:
    container_label: |-
      {{
        [
          tools_current_cluster[0].name,
          tools_managers.kubernetes_gateway.instances.kubernetes.namespace,
          (tools_managers.kubernetes_gateway.instances.names.istio + "-istio"),
        ] |
        ansible.builtin.join("/")
      }}
  block:
    - name: Import variable setting tasks
      ansible.builtin.import_tasks:
        file: set_load_balancer_container_docker.yaml
      vars:
        binary_path: "{{ tools_docker_path.stdout }}"
      when:
        - tools_docker_path.rc == 0

    - name: Import variable setting tasks
      ansible.builtin.import_tasks:
        file: set_load_balancer_container_podman.yaml
      vars:
        binary_path: "{{ tools_podman_path.stdout }}"
      when:
        - tools_podman_path.rc == 0

    - name: Validate that load balancer container was found
      ansible.builtin.assert:
        that:
          - tools_container_info is defined
        fail_msg: Unable to get container id from container runtime. Please verify that Cloud Provider Kind is running.
        success_msg: Retrieved container id from container runtime.
