---
- name: Uninstall OpenCost
  kubernetes.core.helm:
    release_name: "{{ tools_releases.opencost.name }}"
    release_namespace: "{{ tools_releases.opencost.namespace }}"
    release_state: absent
    wait: true

- name: Delete Namespace for OpenCost
  kubernetes.core.k8s:
    resource_definition:
      api_version: v1
      kind: Namespace
      metadata:
        name: "{{ tools_releases.opencost.namespace }}"
    state: absent
    wait: true
