---
- name: Uninstall Istio ZTunnel
  kubernetes.core.helm:
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    release_name: "{{ tools_releases.istio_ztunnel.name }}"
    release_namespace: "{{ tools_releases.istio_ztunnel.namespace }}"
    release_state: absent
    wait: true

- name: Uninstall Istio CNI Node Agent
  kubernetes.core.helm:
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    release_name: "{{ tools_releases.istio_cni.name }}"
    release_namespace: "{{ tools_releases.istio_cni.namespace }}"
    release_state: absent
    wait: true

- name: Uninstall Istiod Control Plane
  kubernetes.core.helm:
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    release_name: "{{ tools_releases.istio_istiod.name }}"
    release_namespace: "{{ tools_releases.istio_istiod.namespace }}"
    release_state: absent
    wait: true

- name: Uninstall Istio Base (CRDs)
  kubernetes.core.helm:
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    release_name: "{{ tools_releases.istio_base.name }}"
    release_namespace: "{{ tools_releases.istio_base.namespace }}"
    release_state: absent
    wait: true

- name: Delete Istio namespace(s)
  kubernetes.core.k8s:
    api_version: v1
    delete_all: true
    kind: Namespace
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    label_selectors:
      - "app.kubernetes.io/component=istio"
      - "app.kubernetes.io/managed-by=ITBench"
    state: absent
    wait: true

- name: Delete subscription
  kubernetes.core.k8s:
    resource_definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: servicemeshoperator3
        namespace: openshift-operators
    state: absent
    wait: true
  when:
    - tools_cluster.platform == "openshift"
