---
# NOTE: The start and end timestamp are never used at
#       the same time. So they are both initialized to
#       `now`. start is only used duing setup and end
#       is only used during export.
recorders_timestamps:
  start: "{{ now(utc=true, fmt='%Y-%m-%dT%H:%M:%SZ') }}"
  end: "{{ now(utc=true, fmt='%Y-%m-%dT%H:%M:%SZ') }}"
