---
- name: Create test resources
  hosts:
    - localhost
  tasks:
    - name: Install Kubernetes Metrics Server
      kubernetes.core.helm:
        chart_ref: metrics-server
        chart_repo_url: "https://kubernetes-sigs.github.io/metrics-server/"
        chart_version: "3.14.0"
        create_namespace: true
        release_name: metrics-server
        release_namespace: metrics-server
        release_state: present
        timeout: 10m0s
        wait: true

    - name: Create test namespace
      kubernetes.core.k8s:
        resource_definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: misconfigured-hpa-test
        state: present

    - name: Create test deployment
      kubernetes.core.k8s:
        resource_definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: test-workload
            namespace: misconfigured-hpa-test
          spec:
            replicas: 2
            selector:
              matchLabels:
                "app.kubernetes.io/name": test-workload
            template:
              metadata:
                labels:
                  "app.kubernetes.io/name": test-workload
              spec:
                containers:
                  - name: server
                    image: registry.access.redhat.com/ubi10-minimal:10.2-1788940913@sha256:26dc3089ab24491c1ba01ab92a7d502d181425b6021e362a07484daee696a3aa
                    command:
                      - /bin/sh
                    args:
                      - -c
                      - "sleep infinity"
                    resources:
                      requests:
                        cpu: 100m
                        memory: 128Mi
                      limits:
                        cpu: 200m
                        memory: 256Mi
        state: present
        wait: true

    - name: Create HorizontalPodAutoscaler
      kubernetes.core.k8s:
        resource_definition:
          apiVersion: autoscaling/v2
          kind: HorizontalPodAutoscaler
          metadata:
            name: test-workload-hpa
            namespace: misconfigured-hpa-test
          spec:
            scaleTargetRef:
              apiVersion: apps/v1
              kind: Deployment
              name: test-workload
            minReplicas: 1
            maxReplicas: 10
            metrics:
              - type: Resource
                resource:
                  name: cpu
                  target:
                    type: Utilization
                    averageUtilization: 70
              - type: Resource
                resource:
                  name: memory
                  target:
                    type: Utilization
                    averageUtilization: 80
        state: present
