---
- name: Retrieve all waiters index templates
  ansible.builtin.find:
    path: "{{ role_path }}/files/library/waiters/indexes"
  register: documentation_waiters_indexes

- name: Create identifiers for waiters
  ansible.builtin.set_fact:
    documentation_waiters_library: |
      {{
        (
          documentation_waiters_library |
          ansible.builtin.default([])
        ) +
        [
          (
            waiter |
            ansible.builtin.combine(
              {
                "id": (
                  waiter.name |
                  ansible.builtin.lower |
                  ansible.builtin.replace(" ", "-")
                ),
                "index": (
                  waiter_index.path |
                  ansible.builtin.basename |
                  ansible.builtin.splitext |
                  ansible.builtin.first |
                  ansible.builtin.int
                )
              }
            )
          )
        ]
      }}
  loop: "{{ documentation_waiters_indexes.files }}"
  loop_control:
    label: file/{{ waiter_index.path | ansible.builtin.basename }}
    loop_var: waiter_index
  vars:
    waiter: |-
      {{
        lookup("ansible.builtin.file", waiter_index.path) |
        ansible.builtin.from_yaml
      }}

- name: Generate waiters library index
  ansible.builtin.copy:
    content: |
      {{
        documentation_waiters_library |
        ansible.builtin.sort(attribute="name") |
        ansible.builtin.to_nice_json
      }}
    dest: "{{ [role_path, 'files', 'library', 'waiters', 'index.json'] | ansible.builtin.path_join }}"
    mode: "0644"

- name: Generate waiter library readme
  ansible.builtin.copy:
    content: "{{ lookup('ansible.builtin.template', 'templates/library/waiters/readmes/index.j2') }}"
    dest: "{{ playbook_dir }}/../../../documentation/library/waiters/README.md"
    mode: "0644"
  vars:
    waiters: |-
      {{
        lookup("ansible.builtin.file", "files/library/waiters/index.json") |
        ansible.builtin.from_json
      }}

- name: Generate waiter library index readmes
  ansible.builtin.copy:
    content: "{{ lookup('ansible.builtin.template', 'templates/library/waiters/readmes/waiter.j2') }}"
    dest: "{{ playbook_dir }}/../../../documentation/library/waiters/{{ waiter.id }}.md"
    mode: "0644"
  loop: |-
    {{
      lookup("ansible.builtin.file", "files/library/waiters/index.json") |
      ansible.builtin.from_json
    }}
  loop_control:
    label: waiter/{{ waiter.id }}
    loop_var: waiter
  vars:
    waiter_platforms: "{{ waiter.platforms | ansible.builtin.sort | ansible.builtin.join(', ') }}"
    schema_file_path: ../../../schemas/json/waiters/{{ waiter.id }}.json
    source_file_path: ../../../scenarios/sre/project/roles/documentation/files/library/waiters/indexes/{{ waiter.index }}.yaml

- name: Generate waiter library index json schemas
  ansible.builtin.copy:
    content: |-
      {{
        waiter.arguments.jsonSchema |
        ansible.builtin.combine({"$schema": "https://json-schema.org/draft/2020-12/schema"}) |
        ansible.builtin.to_nice_json
      }}
    dest: "{{ playbook_dir }}/../../../schemas/json/waiters/{{ waiter.id }}.json"
    mode: "0644"
  loop: |-
    {{
      lookup("ansible.builtin.file", "files/library/waiters/index.json") |
      ansible.builtin.from_json
    }}
  loop_control:
    label: waiter/{{ waiter.id }}
    loop_var: waiter
