---


- name: Create temporary directory for scenario templates
  ansible.builtin.tempfile:
    prefix: scenarios
    state: directory
  register: documentation_temporary_directory

- name: Include applications role variables for templating
  ansible.builtin.include_vars:
    file: |-
      {{
        [
          playbook_dir,
          "roles",
          "applications",
          "defaults",
          "main",
          "managers.yaml"
        ] |
        ansible.builtin.path_join
      }}

- name: Include tools role variables for templating
  ansible.builtin.include_vars:
    file: |-
      {{
        [
          playbook_dir,
          "roles",
          "tools",
          "defaults",
          "main",
          "managers.yaml"
        ] |
        ansible.builtin.path_join
      }}

- name: Generate map for applications based on application id
  ansible.builtin.set_fact:
    documentation_applications: |-
      {{
        documentation_applications |
        ansible.builtin.default({}) |
        ansible.builtin.combine({application.id: application})
      }}
  loop: |-
    {{
      lookup("ansible.builtin.file", "files/library/applications/index.json") |
      ansible.builtin.from_json
    }}
  loop_control:
    label: application/{{ application.name }}
    loop_var: application

- name: Generate map for faults based on fault id
  ansible.builtin.set_fact:
    documentation_faults: |-
      {{
        documentation_faults |
        ansible.builtin.default({}) |
        ansible.builtin.combine({fault.id: fault})
      }}
  loop: |-
    {{
      lookup("ansible.builtin.file", "files/library/faults/index.json") |
      ansible.builtin.from_json
    }}
  loop_control:
    label: fault/{{ fault.name }}
    loop_var: fault

- name: Generate map for waiters based on waiter id
  ansible.builtin.set_fact:
    documentation_waiters: |-
      {{
        documentation_waiters |
        ansible.builtin.default({}) |
        ansible.builtin.combine({waiter.id: waiter})
      }}
  loop: |-
    {{
      lookup("ansible.builtin.file", "files/library/waiters/index.json") |
      ansible.builtin.from_json
    }}
  loop_control:
    label: waiter/{{ waiter.name }}
    loop_var: waiter

- name: Retrieve all scenario index templates
  ansible.builtin.find:
    path: |-
      {{
        [
          role_path,
          "templates",
          "library",
          "scenarios",
          "indexes"
        ] |
        ansible.builtin.path_join
      }}
  register: documentation_scenarios_indexes_templates

- name: Template all scenario indexes
  ansible.builtin.set_fact:
    documentation_scenarios_indexes: |-
      {{
        (
          documentation_scenarios_indexes |
          ansible.builtin.default([])
        ) +
        [
          (
            lookup("ansible.builtin.template", scenario_index.path) |
            ansible.builtin.from_yaml
          ) |
          ansible.builtin.combine(
            {
              "index": (
                scenario_index.path |
                ansible.builtin.basename |
                ansible.builtin.splitext |
                ansible.builtin.first |
                ansible.builtin.int
              )
            }
          )
        ]
      }}
  loop: "{{ documentation_scenarios_indexes_templates.files }}"
  loop_control:
    label: file/{{ scenario_index.path | ansible.builtin.basename }}
    loop_var: scenario_index

- name: Create solution templates for each templated scenario
  ansible.builtin.copy:
    content: |-
      {{
        lookup("ansible.builtin.template", "templates/library/scenarios/solutions.j2") |
        ansible.builtin.from_yaml |
        ansible.builtin.to_nice_yaml
      }}
    dest: "{{ documentation_temporary_directory.path }}/{{ scenario.id }}_solutions.j2"
    mode: "0644"
  loop: "{{ documentation_scenarios_indexes }}"
  loop_control:
    label: scenario/{{ scenario.id }}
    loop_var: scenario

- name: Add solution and fault information to scenario
  ansible.builtin.set_fact:
    documentation_scenarios: |-
      {{
        (
          documentation_scenarios |
          ansible.builtin.default([])
        ) +
        [
          (
            scenario |
            ansible.utils.remove_keys(target=["solutionTemplates"]) |
            ansible.builtin.combine(
              {
                "alerts": (
                  (
                    (
                      scenario_faults |
                      map(attribute="alerts.application", default=[]) |
                      ansible.builtin.flatten
                    ) +
                    (
                      scenario_faults |
                      map(attribute="alerts.goldenSignal", default=[]) |
                      ansible.builtin.flatten
                    )
                  ) |
                  ansible.builtin.unique
                ),
                "platforms": (
                  (
                    (
                      scenario.platforms |
                      ansible.builtin.default([])
                    ) +
                    (
                      scenario_faults |
                      map(attribute="platform")
                    )
                  ) |
                  ansible.builtin.unique
                ),
                "tags": (
                  (
                    (
                      scenario.tags |
                      ansible.builtin.default([])
                    ) +
                    (
                      scenario_faults |
                      map(attribute="tags", default=[]) |
                      ansible.builtin.flatten
                    )
                  ) |
                  ansible.builtin.unique
                ),
                "solutions": (
                  lookup("ansible.builtin.template", scenario_solutions_file) |
                  ansible.builtin.from_yaml
                )
              }
            )
          )
        ]
      }}
  loop: "{{ documentation_scenarios_indexes }}"
  loop_control:
    label: scenario/{{ scenario.id }}
    loop_var: scenario
  vars:
    scenario_faults: |-
      {{
        scenario.disruptions |
        map(attribute="injections", default=[]) |
        ansible.builtin.flatten(1) |
        map(attribute="id") |
        map("extract", documentation_faults)
      }}
    scenario_solutions_file: "{{ documentation_temporary_directory.path }}/{{ scenario.id }}_solutions.j2"

- name: Generate scenarios libary schema
  ansible.builtin.copy:
    content: |-
      {{
        lookup("ansible.builtin.template", "templates/library/scenarios/schema.j2") |
        ansible.builtin.from_yaml |
        ansible.builtin.to_nice_json
      }}
    dest: |-
      {{
        [
          role_path,
          "files",
          "library",
          "scenarios",
          "schema.json"
        ] |
        ansible.builtin.path_join
      }}
    mode: "0644"

- name: Generate scenario indexes
  ansible.builtin.copy:
    content: |-
      {{
        scenario |
        ansible.utils.remove_keys(target=["index"]) |
        ansible.builtin.to_nice_yaml(explicit_start=true, indent=2, width=9999)
      }}
    dest: |-
      {{
        [
          role_path,
          "files",
          "library",
          "scenarios",
          "indexes",
          index_file_name
        ] |
        ansible.builtin.path_join
      }}
    mode: "0644"
  loop: "{{ documentation_scenarios }}"
  loop_control:
    label: index/{{ scenario.index }}
    loop_var: scenario
  vars:
    index_file_name: "{{ scenario.index | ansible.builtin.string }}.yaml"

- name: Generate scenarios libary index
  ansible.builtin.copy:
    content: |
      {{
        documentation_scenarios |
        ansible.builtin.sort(attribute="id") |
        ansible.builtin.to_nice_json
      }}
    dest: |-
      {{
        [
          role_path,
          "files",
          "library",
          "scenarios",
          "index.json"
        ] |
        ansible.builtin.path_join
      }}
    mode: "0644"

- name: Generate scenario library readme
  ansible.builtin.copy:
    content: "{{ lookup('ansible.builtin.template', 'templates/library/scenarios/readmes/index.j2') }}"
    dest: |-
      {{
        [
          playbook_dir,
          "..",
          "..",
          "..",
          "documentation",
          "library",
          "scenarios",
          "README.md"
        ] |
        ansible.builtin.path_join
      }}
    mode: "0644"
  vars:
    scenarios: |-
      {{
        lookup("ansible.builtin.file", "files/library/scenarios/index.json") |
        ansible.builtin.from_json
      }}
    statistics:
      application:
        book_info: |-
          {{
            documentation_scenarios |
            map(attribute="environment.applications") |
            ansible.builtin.flatten |
            ansible.builtin.selectattr("id", "==", "book-info") |
            ansible.builtin.length
          }}
        otel_demo: |-
          {{
            documentation_scenarios |
            map(attribute="environment.applications") |
            ansible.builtin.flatten |
            ansible.builtin.selectattr("id", "==", "opentelemetry-demo") |
            ansible.builtin.length
          }}
      category:
        finops: |-
          {{
            documentation_scenarios |
            ansible.builtin.selectattr("category", "==", "finops") |
            ansible.builtin.length
          }}
        sre: |-
          {{
            documentation_scenarios |
            ansible.builtin.selectattr("category", "==", "sre") |
            ansible.builtin.length
          }}
      complexity:
        high: |-
          {{
            documentation_scenarios |
            ansible.builtin.selectattr("complexity", "==", "high") |
            ansible.builtin.length
          }}
        low: |-
          {{
            documentation_scenarios |
            ansible.builtin.selectattr("complexity", "==", "low") |
            ansible.builtin.length
          }}
        medium: |-
          {{
            documentation_scenarios |
            ansible.builtin.selectattr("complexity", "==", "medium") |
            ansible.builtin.length
          }}

- name: Generate scenario library index readmes
  ansible.builtin.copy:
    content: "{{ lookup('ansible.builtin.template', 'templates/library/scenarios/readmes/scenario.j2') }}"
    dest: |-
      {{
        [
          playbook_dir,
          "..",
          "..",
          "..",
          "documentation",
          "library",
          "scenarios",
          scenario.category,
          scenario.id ~ ".md"
        ] |
        ansible.builtin.path_join
      }}
    mode: "0644"
  loop: |-
    {{
      lookup("ansible.builtin.file", "files/library/scenarios/index.json") |
      ansible.builtin.from_json
    }}
  loop_control:
    label: scenario/{{ scenario.id }}
    loop_var: scenario
  vars:
    scenario_tags: "{{ scenario.tags | ansible.builtin.sort | ansible.builtin.join(', ') }}"
    scenario_platforms: "{{ scenario.platforms | ansible.builtin.sort | ansible.builtin.join(', ') }}"
    source_file_path: |-
      {{
        [
          "..",
          "..",
          "..",
          "..",
          "scenarios",
          "sre",
          "project",
          "roles",
          "documentation",
          "files",
          "library",
          "scenarios",
          "indexes",
          scenario.index ~ ".yaml"
        ] |
        ansible.builtin.path_join
      }}

- name: Delete the temporary directory
  ansible.builtin.file:
    path: "{{ documentation_temporary_directory.path }}"
    state: absent
