---
- name: Retrieve all applications index templates
  ansible.builtin.find:
    path: |-
      {{
        [
          role_path,
          "files",
          "library",
          "applications",
          "indexes"
        ] |
        ansible.builtin.path_join
      }}
  register: documentation_applications_indexes

- name: Create identifiers for applications
  ansible.builtin.set_fact:
    documentation_applications_library: |
      {{
        (
          documentation_applications_library |
          ansible.builtin.default([])
        ) +
        [
          (
            application |
            ansible.builtin.combine(
              {
                "id": (
                  application.name |
                  ansible.builtin.lower |
                  ansible.builtin.replace(" ", "-")
                ),
                "index": (
                  application_index.path |
                  ansible.builtin.basename |
                  ansible.builtin.splitext |
                  ansible.builtin.first |
                  ansible.builtin.int
                )
              }
            )
          )
        ]
      }}
  loop: "{{ documentation_applications_indexes.files }}"
  loop_control:
    label: file/{{ application_index.path | ansible.builtin.basename }}
    loop_var: application_index
  vars:
    application: |-
      {{
        lookup("ansible.builtin.file", application_index.path) |
        ansible.builtin.from_yaml
      }}

- name: Generate applications library index
  ansible.builtin.copy:
    content: |
      {{
        documentation_applications_library |
        ansible.builtin.sort(attribute="name") |
        ansible.builtin.to_nice_json
      }}
    dest: |-
      {{
        [
          role_path,
          "files",
          "library",
          "applications",
          "index.json"
        ] |
        ansible.builtin.path_join
      }}
    mode: "0644"

- name: Generate application library readme
  ansible.builtin.copy:
    content: "{{ lookup('ansible.builtin.template', 'templates/library/applications/readmes/index.j2') }}"
    dest: |-
      {{
        [
          playbook_dir,
          "..",
          "..",
          "..",
          "documentation",
          "library",
          "applications",
          "README.md"
        ] |
        ansible.builtin.path_join
      }}
    mode: "0644"
  vars:
    applications: |-
      {{
        lookup("ansible.builtin.file", "files/library/applications/index.json") |
        ansible.builtin.from_json
      }}

- name: Generate application library index readmes
  ansible.builtin.copy:
    content: "{{ lookup('ansible.builtin.template', 'templates/library/applications/readmes/application.j2') }}"
    dest: |-
      {{
        [
          playbook_dir,
          "..",
          "..",
          "..",
          "documentation",
          "library",
          "applications",
          application.id ~ ".md"
        ] |
        ansible.builtin.path_join
      }}
    mode: "0644"
  loop: |-
    {{
      lookup("ansible.builtin.file", "files/library/applications/index.json") |
      ansible.builtin.from_json
    }}
  loop_control:
    label: application/{{ application.id }}
    loop_var: application
  vars:
    application_platforms: "{{ application.platforms | ansible.builtin.sort | ansible.builtin.join(', ') }}"
    schema_file_path: |-
      {{
        [
          "..",
          "..",
          "..",
          "schemas",
          "json",
          "applications",
          application.id ~ ".json"
        ] |
        ansible.builtin.path_join
      }}
    source_file_path: |-
      {{
        [
          "..",
          "..",
          "..",
          "scenarios",
          "sre",
          "project",
          "roles",
          "documentation",
          "files",
          "library",
          "applications",
          "indexes",
          application.index ~ ".yaml"
        ] |
        ansible.builtin.path_join
      }}

- name: Generate application library index json schemas
  ansible.builtin.copy:
    content: |-
      {{
        application.arguments.jsonSchema |
        ansible.builtin.combine({"$schema": "https://json-schema.org/draft/2020-12/schema"}) |
        ansible.builtin.to_nice_json
      }}
    dest: |-
      {{
        [
          playbook_dir,
          "..",
          "..",
          "..",
          "schemas",
          "json",
          "applications",
          application.id ~ ".json"
        ] |
        ansible.builtin.path_join
      }}
    mode: "0644"
  loop: |-
    {{
      lookup("ansible.builtin.file", "files/library/applications/index.json") |
      ansible.builtin.from_json
    }}
  loop_control:
    label: application/{{ application.id }}
    loop_var: application
