---
- name: Retrieve all waiters index templates
  ansible.builtin.find:
    path: "{{ role_path }}/files/library/waiters/indexes"
  register: documentation_waiters_indexes

- name: Create identifiers for waiters
  ansible.builtin.set_fact:
    documentation_waiters_library: |
      {{
        (
          documentation_waiters_library |
          ansible.builtin.default([])
        ) +
        [
          (
            waiter |
            ansible.builtin.combine(
              {
                "id": (
                  waiter.name |
                  ansible.builtin.lower |
                  ansible.builtin.replace(" ", "-")
                ),
                "index": (
                  waiter_index.path |
                  ansible.builtin.basename |
                  ansible.builtin.splitext |
                  ansible.builtin.first |
                  ansible.builtin.int
                )
              }
            )
          )
        ]
      }}
  loop: "{{ documentation_waiters_indexes.files }}"
  loop_control:
    label: file/{{ waiter_index.path | ansible.builtin.basename }}
    loop_var: waiter_index
  vars:
    waiter: |-
      {{
        lookup("ansible.builtin.file", waiter_index.path) |
        ansible.builtin.from_yaml
      }}

- name: Generate waiters library index
  ansible.builtin.copy:
    content: |
      {{
        documentation_waiters_library |
        ansible.builtin.sort(attribute="name") |
        ansible.builtin.to_nice_json
      }}
    dest: "{{ [role_path, 'files', 'library', 'waiters', 'index.json'] | ansible.builtin.path_join }}"
    mode: "0644"

- name: Generate Waiters README
  ansible.builtin.copy:
    content: "{{ lookup('ansible.builtin.template', 'templates/readmes/waiters.j2') }}"
    dest: "{{ playbook_dir }}/../docs/waiters.md"
    mode: "0644"
  vars:
    documentation_contents: |-
      {{
        lookup("ansible.builtin.file", "files/library/waiters/index.json") |
        ansible.builtin.from_json
      }}
