---
- name: Load all library index files
  ansible.builtin.set_fact:
    documentation_library_index:
      applications: |-
        {{
          lookup("ansible.builtin.file", "files/library/applications/index.json") |
          ansible.builtin.from_json
        }}
      faults: |-
        {{
          lookup("ansible.builtin.file", "files/library/faults/index.json") |
          ansible.builtin.from_json
        }}
      scenarios: |-
        {{
          lookup("ansible.builtin.file", "files/library/scenarios/index.json") |
          ansible.builtin.from_json
        }}
      waiters: |-
        {{
          lookup("ansible.builtin.file", "files/library/waiters/index.json") |
          ansible.builtin.from_json
        }}
