---
- name: Include library validation tasks
  ansible.builtin.include_tasks:
    file: validate_library_index.yaml
    apply:
      tags:
        - validate_docs
      vars:
        library_name: "{{ library.name }}"
  loop:
    - name: applications
    - name: faults
    - name: scenarios
    - name: waiters
  loop_control:
    loop_var: library
    label: library/{{ library.name }}
