---
- name: Create test resources
  hosts:
    - localhost
  tasks:
    - name: Include tools role variables
      ansible.builtin.include_vars:
        file: |-
          {{
            [
              playbook_dir,
              "..",
              "..",
              "..",
              "tools",
              "defaults",
              "main",
              "managers.yaml"
            ] |
            ansible.builtin.path_join
          }}

    - name: Install Chaos Mesh
      kubernetes.core.helm:
        chart_ref: "{{ tools_managers.chaos_mesh.helm.chart.reference }}"
        chart_repo_url: "{{ tools_managers.chaos_mesh.helm.chart.repository }}"
        chart_version: "{{ tools_managers.chaos_mesh.helm.chart.version }}"
        create_namespace: true
        kubeconfig: "{{ cluster.kubeconfig }}"
        release_name: "{{ tools_managers.chaos_mesh.helm.release.name }}"
        release_namespace: "{{ tools_managers.chaos_mesh.kubernetes.namespace }}"
        release_state: present
        wait: true

    - name: Create test namespace
      kubernetes.core.k8s:
        kubeconfig: "{{ cluster.kubeconfig }}"
        resource_definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: scheduled-chaos-test
        state: present

    - name: Create test deployment
      kubernetes.core.k8s:
        kubeconfig: "{{ cluster.kubeconfig }}"
        resource_definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: test-workload
            namespace: scheduled-chaos-test
          spec:
            replicas: 2
            selector:
              matchLabels:
                "app.kubernetes.io/name": test-workload
            template:
              metadata:
                labels:
                  "app.kubernetes.io/name": test-workload
              spec:
                containers:
                  - name: server
                    image: registry.access.redhat.com/ubi10-minimal:10.1-1778461919
                    command:
                      - /bin/sh
                    args:
                      - -c
                      - "sleep infinity"
        state: present
        wait: true
