---
- name: Destroy test resources
  hosts:
    - localhost
  tasks:
    - name: Include tools role variables
      ansible.builtin.include_vars:
        file: |-
          {{
            [
              playbook_dir,
              "..",
              "..",
              "..",
              "tools",
              "defaults",
              "main",
              "managers.yaml"
            ] |
            ansible.builtin.path_join
          }}

    - name: Delete test namespace
      kubernetes.core.k8s:
        kubeconfig: "{{ cluster.kubeconfig }}"
        resource_definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: scheduled-chaos-test
        state: absent
        wait: true

    - name: Uninstall Chaos Mesh
      kubernetes.core.helm:
        kubeconfig: "{{ cluster.kubeconfig }}"
        release_name: "{{ tools_managers.chaos_mesh.helm.release.name }}"
        release_namespace: "{{ tools_managers.chaos_mesh.kubernetes.namespace }}"
        release_state: absent
        wait: true

    - name: Delete Chaos Mesh namespace
      kubernetes.core.k8s:
        kubeconfig: "{{ cluster.kubeconfig }}"
        resource_definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ tools_managers.chaos_mesh.kubernetes.namespace }}"
        state: absent
        wait: true

    - name: Retrieve all CustomResourceDefinitions
      kubernetes.core.k8s_info:
        api_version: apiextensions.k8s.io/v1
        kind: CustomResourceDefinition
        kubeconfig: "{{ cluster.kubeconfig }}"
      register: faults_custom_resource_definitions

    - name: Delete Chaos Mesh related CustomResourceDefinitions
      kubernetes.core.k8s:
        kubeconfig: "{{ cluster.kubeconfig }}"
        resource_definition:
          apiVersion: "{{ custom_resource_definition.apiVersion }}"
          kind: "{{ custom_resource_definition.kind }}"
          metadata:
            name: "{{ custom_resource_definition.metadata.name }}"
        state: absent
        wait: true
      loop: |-
        {{
          faults_custom_resource_definitions.resources |
          ansible.builtin.selectattr("spec.group", "==", "chaos-mesh.org")
        }}
      loop_control:
        label: customresourcedefinition/{{ custom_resource_definition.metadata.name }}
        loop_var: custom_resource_definition
