generator_library_index:
  applications: |-
    {{
      lookup("ansible.builtin.file", "files/library/index/applications.json") |
      ansible.builtin.from_json
    }}
  faults: |-
    {{
      lookup("ansible.builtin.file", "files/library/index/faults.json") |
      ansible.builtin.from_json
    }}
  scenarios: |-
    {{
      lookup("ansible.builtin.file", "files/library/index/scenarios.json") |
      ansible.builtin.from_json
    }}
  waiters: |-
    {{
      lookup("ansible.builtin.file", "files/library/index/waiters.json") |
      ansible.builtin.from_json
    }}
