---
collections:
  - name: amazon.aws
    version: "10.1.2"
  - name: ansible.posix
    version: "2.1.0"
  - name: ansible.utils
    version: "6.0.1"
  - name: ansible.windows
    version: "3.2.0"
  - name: awx.awx
    version: "24.6.1"
  - name: azure.azcollection
    version: "3.9.0"
  - name: community.aws
    version: "10.0.0"
  - name: community.general
    version: "12.0.1"
  - name: community.vmware
    version: "6.1.0"
  - name: google.cloud
    version: "1.9.0"
  - name: kubernetes.core
    version: "6.2.0"
  - name: kubevirt.core
    version: "2.2.3"
  - name: openstack.cloud
    version: "2.5.0"
  - name: ovirt.ovirt
    version: "3.2.2"
  - name: redhatinsights.insights
    version: "1.3.0"
  - name: theforeman.foreman
    version: "5.7.0"
