---
apiVersion: itbench.io/v2
kind: Scenario
metadata:
  name: scenario-91
spec:
  applications:
    opentelemetryDemo:
      enabled: true
  faults:
    - injections:
        - args:
            kubernetesObject:
              apiVersion: chaos-mesh.org/v1alpha1
              kind: Schedule
              metadata:
                name: fraud-detection-kafka-network-partition
                namespace: chaos-mesh
            scheduleSpec:
              networkChaos:
                action: partition
                direction: to
                mode: all
                selector:
                  labelSelectors:
                    app.kubernetes.io/component: email
                  namespaces:
                    - otel-demo
                target:
                  mode: all
                  selector:
                    labelSelectors:
                      app.kubernetes.io/component: checkout
                    namespaces:
                      - otel-demo
              type: NetworkChaos
          id: scheduled-chaos-mesh-experiment
      waitFor:
        preInjection:
          - args:
              kubernetesObject:
                apiVersion: apps/v1
                kind: Deployment
                metadata:
                  name: email
                  namespace: otel-demo
              replicas: 2
            id: scale-kubernetes-workload
  tools:
    sre:
      enabled: true
