---
- name: Import documentation role
  ansible.builtin.import_role:
    name: documentation
    tasks_from: load

- name: Generate scenario directory paths
  ansible.builtin.set_fact:
    scenarios_directory_paths: |-
      {{
        scenarios_directory_paths |
        ansible.builtin.default({}) |
        ansible.builtin.combine(
          {
            scenario.id: (
              [
                role_path,
                "files",
                "scenario_" ~ scenario.id
              ] |
              ansible.builtin.path_join
            )
          }
        )
      }}
  loop: "{{ documentation_library_index.scenarios }}"
  loop_control:
    label: scenario-{{ scenario.id }}
    loop_var: scenario

- name: Generate scenario directories
  ansible.builtin.file:
    mode: "0755"
    path: "{{ scenarios_directory_paths[scenario.id] }}"
    state: directory
  loop: "{{ documentation_library_index.scenarios }}"
  loop_control:
    label: scenario-{{ scenario.id }}
    loop_var: scenario

- name: Create scenarios roles meta argument specs file
  ansible.builtin.copy:
    content: |-
      {{
        lookup('ansible.builtin.template', 'templates/meta/argument_specs.j2') |
        ansible.builtin.from_yaml |
        ansible.builtin.to_nice_yaml(explicit_start=true, indent=2)
      }}
    dest: |-
      {{
        [
          role_path,
          "meta",
          "argument_specs.yaml"
        ] |
        ansible.builtin.path_join
      }}
    mode: "0644"
  vars:
    scenario_ids: "{{ documentation_library_index.scenarios | map(attribute='id') }}"

- name: Generate scenario specs
  ansible.builtin.copy:
    content: |-
      {{
        lookup('ansible.builtin.template', 'templates/manifests/scenario.j2') |
        ansible.builtin.from_yaml |
        ansible.builtin.to_nice_yaml(indent=2, width=160)
      }}
    dest: |-
      {{
        [
          scenarios_directory_paths[scenario.id],
          "scenario.yaml"
        ] |
        ansible.builtin.path_join
      }}
    mode: "0644"
  loop: "{{ documentation_library_index.scenarios }}"
  loop_control:
    label: scenario-{{ scenario.id }}
    loop_var: scenario

- name: Generate scenario ground truths
  ansible.builtin.copy:
    content: |
      {{
        lookup('ansible.builtin.template', 'templates/manifests/groundtruth.j2') |
        ansible.builtin.from_yaml |
        ansible.builtin.to_nice_yaml(indent=2, width=160)
      }}
    dest: |-
      {{
        [
          scenarios_directory_paths[scenario.id],
          "groundtruth.yaml"
        ] |
        ansible.builtin.path_join
      }}
    mode: "0644"
  loop: "{{ documentation_library_index.scenarios }}"
  loop_control:
    label: scenario-{{ scenario.id }}
    loop_var: scenario
