---
- name: Set scenario variables
  ansible.builtin.set_fact:
    scenarios_scenario: |-
      {{
        lookup("ansible.builtin.file", scneario_path) |
        ansible.builtin.from_yaml
      }}
    scenarios_ground_truth: |-
      {{
        lookup("ansible.builtin.file", ground_truth_path) |
        ansible.builtin.from_yaml
      }}
  vars:
    ground_truth_path: files/scenario-{{ scenarios_identifier }}/groundtruth.yaml
    scenario_path: files/scenario-{{ scenarios_identifier }}/scenario.yaml
  tags:
    - always
