---
- name: Set scenario variables
  ansible.builtin.set_fact:
    scenarios_scenario: |-
      {{
        lookup("ansible.builtin.file", scenario_path) |
        ansible.builtin.from_yaml
      }}
    scenarios_ground_truth: |-
      {{
        lookup("ansible.builtin.file", ground_truth_path) |
        ansible.builtin.from_yaml
      }}
  vars:
    ground_truth_path: |-
      {{
        [
          playbook_dir,
          "..",
          "..",
          "..",
          "library",
          "specs",
          "scenarios",
          scenarios_identifier | string,
          "groundtruth.yaml"
        ] |
        ansible.builtin.path_join
      }}
    scenario_path: |-
      {{
        [
          playbook_dir,
          "..",
          "..",
          "..",
          "library",
          "specs",
          "scenarios",
          scenarios_identifier | string,
          "scenario.yaml"
        ] |
        ansible.builtin.path_join
      }}
  tags:
    - always
