---
- name: Create temporary spec file for {{ cluster_name }}
  ansible.builtin.tempfile:
    prefix: "{{ cluster_name }}-spec-"
    suffix: .yaml
    state: file
  register: kops_cluster_spec_file

- name: Render cluster and instance group specs for {{ cluster_name }}
  ansible.builtin.template:
    src: templates/specs/cluster.yaml.j2
    dest: "{{ kops_cluster_spec_file.path }}"
    mode: "0600"

- name: Append control-plane instance group spec for {{ cluster_name }}
  ansible.builtin.blockinfile:
    path: "{{ kops_cluster_spec_file.path }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - control-plane instancegroup"
    block: "{{ lookup('ansible.builtin.template', 'templates/specs/instancegroup_control.yaml.j2') }}"
    insertafter: EOF

- name: Append worker instance group spec for {{ cluster_name }}
  ansible.builtin.blockinfile:
    path: "{{ kops_cluster_spec_file.path }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - worker instancegroup"
    block: "{{ lookup('ansible.builtin.template', 'templates/specs/instancegroup_worker.yaml.j2') }}"
    insertafter: EOF

- name: Create kOps cluster from spec file for {{ cluster_name }}
  ansible.builtin.command:
    argv:
      - kops
      - create
      - -f
      - "{{ kops_cluster_spec_file.path }}"
      - --state
      - "{{ kops_state_store }}"
  register: kops_create_cluster_results
  changed_when:
    - kops_create_cluster_results.rc == 0

- name: Import SSH public key for {{ cluster_name }}
  ansible.builtin.command:
    argv:
      - kops
      - create
      - secret
      - sshpublickey
      - admin
      - -i
      - "{{ kops_configuration.ssh_keys.public }}"
      - --name
      - "{{ cluster_name }}"
      - --state
      - "{{ kops_state_store }}"
  register: kops_ssh_key_results
  changed_when:
    - kops_ssh_key_results.rc == 0

- name: Delete temporary spec file for {{ cluster_name }}
  ansible.builtin.file:
    path: "{{ kops_cluster_spec_file.path }}"
    state: absent
