---
- name: Create export directory
  ansible.builtin.file:
    mode: "0755"
    path: "{{ export_directory }}"
    state: directory
  register: kops_export_directory

- name: Export kubeconfig
  ansible.builtin.command:
    argv:
      - kops
      - export
      - --name
      - "{{ cluster_name }}"
      - kubecfg
      - --admin
      - --state
      - "{{ kops_state_store }}"
      - --kubeconfig
      - "{{ [kops_export_directory.path, cluster_name] | ansible.builtin.path_join }}"
  loop: "{{ kops_cluster_group.clusters }}"
  loop_control:
    label: cluster/{{ cluster_name }}
    loop_var: cluster_name
  register: kops_export_result
  changed_when: kops_export_result.rc == 0

- name: Copy kubeconfigs to /tmp for scenarios/sre compatibility
  ansible.builtin.copy:
    src: "{{ [kops_export_directory.path, cluster_name] | ansible.builtin.path_join }}"
    dest: "/tmp/{{ cluster_name }}"
    mode: "0600"
    remote_src: true
  loop: "{{ kops_cluster_group.clusters }}"
  loop_control:
    label: cluster/{{ cluster_name }}
    loop_var: cluster_name

- name: Update stack group variables file for scenarios/sre
  ansible.builtin.copy:
    content: "{{ stack_definition | to_nice_yaml(indent=2) }}"
    dest: "{{ (playbook_dir ~ '/../../../scenarios/sre/group_vars/runner/stack.yaml') | realpath }}"
    mode: "0644"
  vars:
    head_cluster: "{{ kops_cluster_group.clusters | first }}"
    runner_clusters: "{{ kops_cluster_group.clusters[1:] }}"
    stack_definition:
      stack:
        awx:
          kubeconfig: "/tmp/{{ head_cluster }}"
        runners:
          kubeconfigs: "{{ runner_clusters | map('regex_replace', '^(.*)$', '/tmp/\\1') | list }}"

- name: Set export paths fact
  ansible.builtin.set_fact:
    kops_export_paths: |-
      {{
        [kops_export_directory.path] |
        product(kops_cluster_group.clusters) |
        map("path_join") |
        map("realpath")
      }}

- name: Display paths to kubeconfigs
  ansible.builtin.debug:
    var: kops_export_paths

- name: Display the export environment variable commands for all clusters
  ansible.builtin.debug:
    msg:
      - "Run the following command to execute kubectl commands for {{ cluster_path | basename }}:"
      - "export KUBECONFIG={{ cluster_path }}"
  loop: "{{ kops_export_paths }}"
  loop_control:
    label: "{{ cluster_path | basename }}"
    loop_var: cluster_path
