---
- name: Create export directory
  ansible.builtin.file:
    mode: "0755"
    path: "{{ [playbook_dir, '..', 'kubeconfigs'] | ansible.builtin.path_join }}"
    state: directory
  register: kops_export_directory

- name: Export kubeconfig
  ansible.builtin.command:
    argv:
      - kops
      - export
      - --name
      - "{{ cluster_name }}"
      - kubecfg
      - --admin
      - --state
      - "{{ kops_state_store }}"
      - --kubeconfig
      - "{{ [kops_export_directory.path, cluster_name] | ansible.builtin.path_join }}"
  loop: "{{ kops_cluster_group.clusters }}"
  loop_control:
    label: cluster/{{ cluster_name }}
    loop_var: cluster_name
  register: kops_export_result
  changed_when:
    - kops_export_result.rc == 0

- name: Display the export environment variable commands for all clusters
  ansible.builtin.debug:
    msg:
      - "Run the following command to access the cluster ({{ kubeconfig_path | ansible.builtin.basename }}) using kubectl:"
      - "export KUBECONFIG={{ kubeconfig_path }}"
  loop: |-
    {{
      [kops_export_directory.path] |
      product(kops_cluster_group.clusters) |
      map("ansible.builtin.path_join") |
      map("ansible.builtin.realpath")
    }}
  loop_control:
    label: "{{ kubeconfig_path | ansible.builtin.basename }}"
    loop_var: kubeconfig_path
