---
- name: Include fault argument validation tasks
  ansible.builtin.include_tasks:
    file: validate_fault_arguments.yaml

- name: Create ResourceQuota
  kubernetes.core.k8s:
    kubeconfig: "{{ faults_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: v1
      kind: ResourceQuota
      metadata:
        name: memory
        namespace: "{{ faults_kubernetes_object.metadata.namespace }}"
      spec:
        hard:
          memory: 1Gi
    state: present

- name: Scale down workload
  kubernetes.core.k8s_scale:
    api_version: "{{ faults_kubernetes_object.apiVersion }}"
    kubeconfig: "{{ faults_cluster.kubeconfig }}"
    kind: "{{ faults_kubernetes_object.kind }}"
    name: "{{ faults_kubernetes_object.metadata.name }}"
    namespace: "{{ faults_kubernetes_object.metadata.namespace }}"
    replicas: 0
    wait: true
    wait_timeout: 60

# NOTE: Do not wait for the following operation to complete successfully.
#       It will not because the node is cordoned and thus no new pods can
#       be created on the node.

- name: Scale up workload
  kubernetes.core.k8s_scale:
    api_version: "{{ faults_kubernetes_object.apiVersion }}"
    kubeconfig: "{{ faults_cluster.kubeconfig }}"
    kind: "{{ faults_kubernetes_object.kind }}"
    name: "{{ faults_kubernetes_object.metadata.name }}"
    namespace: "{{ faults_kubernetes_object.metadata.namespace }}"
    replicas: "{{ faults_kubernetes_object.spec.replicas }}"
    wait: false
