---
- name: Include fault argument validation tasks
  ansible.builtin.include_tasks:
    file: validate_fault_arguments.yaml

- name: Update workload containers
  kubernetes.core.k8s:
    kubeconfig: "{{ faults_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: "{{ faults_kubernetes_object.apiVersion }}"
      kind: "{{ faults_kubernetes_object.kind }}"
      metadata:
        name: "{{ faults_kubernetes_object.metadata.name }}"
        namespace: "{{ faults_kubernetes_object.metadata.namespace }}"
      spec:
        template:
          spec:
            containers:
              - name: "{{ faults_container.name }}"
                env:
                  - name: "{{ faults_container_environment_variable.name }}"
                    value: "{{ fault_args.container.env.value }}"
    state: patched
