---
- name: Include fault argument validation tasks
  ansible.builtin.include_tasks:
    file: validate_fault_arguments.yaml

- name: Fail playbook with `opentelemetry demo flagd data not found` error
  ansible.builtin.fail:
    msg: Unable to find `flagd` configuration data. Please ensure the correct config map is configured for this injection.
  when:
    - faults_kubernetes_object.data["demo.flagd.json"] is ansible.builtin.undefined

- name: Update configmap data
  kubernetes.core.k8s:
    kubeconfig: "{{ faults_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: "{{ faults_kubernetes_object.apiVersion }}"
      kind: "{{ faults_kubernetes_object.kind }}"
      metadata:
        name: "{{ faults_kubernetes_object.metadata.name }}"
        namespace: "{{ faults_kubernetes_object.metadata.namespace }}"
      data:
        "demo.flagd.json": |-
          {{
            faults_kubernetes_object.data["demo.flagd.json"] |
            ansible.builtin.from_json |
            ansible.builtin.combine(
              {
                "flags": {
                  fault_args.flag.name: {
                    "defaultVariant": fault_args.flag.state
                  }
                }
              },
              recursive=true
            ) |
            ansible.builtin.to_json
          }}
    state: patched
