---
- name: Retrieve containers from runtime
  ansible.builtin.command:
    argv:
      - "{{ binary_path }}"
      - ps
      - --format
      - json
  register: containers_list_result
  changed_when:
    - false

- ansible.builtin.debug:
    var: containers_list_result

# - name: Extract path from retrieval task output {{ binary_name }}
#   ansible.builtin.set_fact:
#     containers_{{ binary_name }}: "{{ containers_list_result.stdout }}"
