---
- name: Import validation tasks
  ansible.builtin.import_tasks:
    file: validate_runtime.yaml

- name: List docker containers
  when:
    - containers_docker_path is ansible.builtin.defined
  block:
    - name: Retrieve cloud provider kind containers from Docker
      ansible.builtin.command:
        argv:
          - "{{ containers_docker_path }}"
          - ps
          - --filter
          - name=^kindccm
          - --format
          - json
          - --no-trunc
      register: containers_docker_ps
      changed_when:
        - false

    - name: Parse cloud provider kind containers ids
      ansible.builtin.set_fact:
        containers_docker_cpk_containers: |-
          {{
            (
              containers_docker_cpk_containers |
              ansible.builtin.default({})
            ) |
            ansible.builtin.combine(
              {
                container.ID: {
                  "service": {
                    "name": load_balancer_label_components[2],
                    "namespace": load_balancer_label_components[1]
                  }
                }
              }
            )
          }}
      loop: |-
        {{
          containers_docker_ps.stdout_lines |
          map("ansible.builtin.from_json")
        }}
      loop_control:
        label: container/{{ container.ID }}
        loop_var: container
      vars:
        load_balancer_label_components: |-
          {{
            (
              dict(
                container.Labels |
                ansible.builtin.split(",") |
                map("ansible.builtin.split", "=")
              )["io.x-k8s.cloud-provider-kind.loadbalancer.name"]
            ) |
            ansible.builtin.split("/")
          }}

    - name: Inspect containers
      ansible.builtin.command:
        argv:
          - "{{ containers_docker_path }}"
          - inspect
          - |-
            {{
              containers_docker_cpk_containers.keys() |
              ansible.builtin.default([]) |
              ansible.builtin.join(" ")
            }}
      register: containers_docker_inspect
      changed_when:
        - false
      when:
        - containers_docker_cpk_containers is ansible.builtin.defined
        - containers_docker_cpk_containers.keys() | ansible.builtin.length > 0

    - name: Parse cloud provider kind host ports
      ansible.builtin.set_fact:
        containers_docker_cpk_ports: |-
          {{
            (
              containers_docker_cpk_ports |
              ansible.builtin.default({})
            ) |
            ansible.builtin.combine(
              {
                kubernetes_service.namespace: {
                  kubernetes_service.name: {
                    "host_port": (
                      (
                        load_balancer_service_port["80/tcp"] |
                        ansible.builtin.first
                      ).HostPort
                    )
                  }
                }
              },
              recursive=true
            )
          }}
      loop: |-
        {{
          containers_docker_inspect.stdout |
          ansible.builtin.from_json
        }}
      loop_control:
        label: container/{{ container.Id }}
        loop_var: container
      vars:
        kubernetes_service: "{{ containers_docker_cpk_containers[container.Id].service }}"
        load_balancer_service_port: "{{ container['NetworkSettings']['Ports'] }}"
      when:
        - load_balancer_service_port["80/tcp"] is ansible.builtin.defined

- name: List podman containers
  when:
    - containers_podman_path is ansible.builtin.defined
  block:
    - name: Retrieve cloud provider kind containers from podman
      ansible.builtin.command:
        argv:
          - "{{ containers_podman_path }}"
          - ps
          - --filter
          - name=^kindccm
          - --format
          - json
      register: containers_podman_ps
      changed_when:
        - false

    - name: Parse cloud provider kind host ports
      ansible.builtin.set_fact:
        containers_podman_cpk_ports: |-
          {{
            (
              containers_podman_cpk_ports |
              ansible.builtin.default({})
            ) |
            ansible.builtin.combine(
              {
                load_balancer_label_components[1]: {
                  load_balancer_label_components[2]: {
                    "host_port": load_balancer_service_port[0].host_port
                  }
                }
              },
              recursive=true
            )
          }}
      loop: |-
        {{
          containers_podman_ps.stdout |
          ansible.builtin.from_json
        }}
      loop_control:
        label: container/{{ container.ID }}
        loop_var: container
      vars:
        load_balancer_service_port: |-
          {{
            container.Ports |
            ansible.builtin.selectattr("container_port", "==", 80)
          }}
        load_balancer_label_components: |-
          {{
            container.Labels["io.x-k8s.cloud-provider-kind.loadbalancer.name"] |
            ansible.builtin.split("/")
          }}
      when:
        - load_balancer_service_port | ansible.builtin.length == 1

- name: Create combine host port dictionary
  ansible.builtin.set_fact:
    containers_cpk_host_ports: |-
      {{
        containers_docker_cpk_ports |
        ansible.builtin.default({}) |
        ansible.builtin.combine(
          containers_podman_cpk_ports |
          ansible.builtin.default({})
        )
      }}
