---
apiVersion: itbench.io/v2
kind: GroundTruth
metadata:
  name: scenario-107
spec:
  alerts:
    - labels: {}
      name: KafkaConsumerGroupInactive
  entities:
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: accounting
        namespace: otel-demo
  solutions:
    - - steps:
          - command: kubectl -n otel-demo scale deployment/accounting --replicas=1
            text: Scale the workload back to 1 replica to restore service.
      - steps:
          - command: kubectl -n otel-demo rollout undo deployment/accounting
            text: Revert the last change done to the manifest to restore the original replica count.
