---
apiVersion: itbench.io/v2
kind: GroundTruth
metadata:
  name: scenario-114
spec:
  alerts:
    - labels: {}
      name: HighRequestErrorRate
  entities:
    - apiVersion: v1
      kind: Service
      metadata:
        name: product-catalog
        namespace: otel-demo
  solutions:
    - - steps:
          - text: Create the manifest with the expected values.
      - steps:
          - text: Apply the manifest file with the expected values to the application namespace.
