---
- name: Create Kubernetes objects
  hosts:
    - localhost
  tasks:
    - name: Create namespace
      kubernetes.core.k8s:
        kubeconfig: "{{ cluster.kubeconfig }}"
        resource_definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: active-host-network-k8s-deployment-test
        state: present
