---
- name: Destroy test resources
  hosts:
    - localhost
  tasks:
    - name: Delete test namespace
      kubernetes.core.k8s:
        kubeconfig: "{{ cluster.kubeconfig }}"
        resource_definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: breaking-configuration-change-test
        state: absent
        wait: true
