---
alerts:
  application:
    - KubePodNotReady
arguments:
  jsonSchema:
    properties:
      container:
        properties:
          name:
            type: string
        required:
          - name
        type: object
      kubernetesObject:
        properties:
          apiVersion:
            enum:
              - apps/v1
            type: string
          kind:
            enum:
              - Deployment
              - StatefulSet
            type: string
          metadata:
            properties:
              name:
                type: string
              namespace:
                type: string
            required:
              - name
              - namespace
            type: object
        required:
          - apiVersion
          - kind
          - metadata
        type: object
    required:
      - kubernetesObject
    type: object
description: This fault injects a misconfigured readiness probe into a workload container. This probe blocks the pod from starting up.
expectation: The faulted pod(s) will enter the `Pending` state due to a `ContainersNotReady` reason for the `Ready` condition.
name: Misconfigured Kubernetes Workload Container Readiness Probe
platform: Kubernetes
resources:
  - https://kubernetes.io/docs/concepts/configuration/liveness-readiness-startup-probes/
  - https://kubernetes.io/docs/concepts/workloads/
  - https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/
  - https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/
solutions:
  templates:
    - steps:
        - command: kubectl -n {{ args.kubernetesObject.metadata.namespace }} rollout undo {{ args.kubernetesObject.kind | lower }}/{{ args.kubernetesObject.metadata.name }}
          text: Revert the last change done to the manifest.
    - steps:
        - command: kubectl -n {{ args.kubernetesObject.metadata.namespace }} edit {{ args.kubernetesObject.kind | lower }} {{ args.kubernetesObject.metadata.name }}
          text: Manually edit the manifest and remove the faulty readiness probe in the container rule.
tags:
  - Deployment
  - Performance
