---
arguments:
  jsonSchema:
    properties:
      kubernetesObject:
        properties:
          apiVersion:
            enum:
              - chaos-mesh.org/v1alpha1
            type: string
          kind:
            enum:
              - Schedule
            type: string
          metadata:
            properties:
              name:
                type: string
              namespace:
                type: string
            required:
              - name
              - namespace
            type: object
        required:
          - apiVersion
          - kind
          - metadata
        type: object
      scheduleSpec:
        properties:
          type:
            type: string
        required:
          - type
        type: object
    required:
      - kubernetesObject
      - scheduleSpec
    type: object
description: This fault injects a Chaos Mesh experiment into the environment. The experiment is
  [scheduled](https://chaos-mesh.org/docs/define-scheduling-rules/) to repeated fire so that the behavior persists.
expectation: Varies based on the Chaos Mesh experiment used.
name: Scheduled Chaos Mesh Experiment
platform: Kubernetes
resources:
  - https://chaos-mesh.org/docs/run-a-chaos-experiment/
  - https://chaos-mesh.org/docs/developer-guide-overview/
solutions:
  templates:
    - steps:
        - command: kubectl -n {{ args.kubernetesObject.metadata.namespace }} annotate schedule {{ args.kubernetesObject.metadata.name }} experiment.chaos-mesh.org/pause='true'
          text: Annotate the schedule to pause the active experiment.
        - command: kubectl -n {{ args.kubernetesObject.metadata.namespace }} get {{ args.scheduleSpec.type | lower }} --selector='experiment.chaos-mesh.org/pause=true'
          text: Retrieve the associated experiment managed by the schedule.
        - text: Delete the retrieved experiement after it has entered the `Paused` state.
        - command: kubectl -n {{ args.kubernetesObject.metadata.namespace }} delete schedule {{ args.kubernetesObject.metadata.name }} experiment.chaos-mesh.org/pause='true'
          text: Delete the schedule.
tags:
  - Deployment
  - Performance
