---
alerts:
  goldenSignal:
    - HighRequestErrorRate
arguments:
  jsonSchema:
    properties:
      kubernetesObject:
        properties:
          apiVersion:
            enum:
              - v1
            type: string
          kind:
            enum:
              - Service
            type: string
          metadata:
            properties:
              name:
                type: string
              namespace:
                type: string
            required:
              - name
              - namespace
            type: object
        required:
          - apiVersion
          - kind
          - metadata
        type: object
    required:
      - kubernetesObject
    type: object
description: This fault modifies an existing service's selector, causing the service to be unable to find its intended workload.
expectation: Existing workloads will be unable to communicate with faulted workload.
name: Invalid Kubernetes Service Selector
platform: Kubernetes
resources:
  - https://kubernetes.io/docs/concepts/workloads/
  - https://kubernetes.io/docs/concepts/services-networking/service/
  - https://kubernetes.io/docs/tasks/access-application-cluster/connecting-frontend-backend/
  - https://kubernetes.io/docs/reference/kubernetes-api/service-resources/service-v1/
solutions:
  templates:
    - steps:
        - command: kubectl -n {{ args.kubernetesObject.metadata.namespace }} edit {{ args.kubernetesObject.kind | lower }} {{
            args.kubernetesObject.metadata.name }}
          text: Manually edit the manifest and replace the selector with the correct value.
tags:
  - Deployment
  - Networking
