---
alerts:
  application:
    - NoRequestsReceived
  goldenSignal:
    - HighRequestErrorRate
arguments:
  jsonSchema:
    properties:
      kubernetesObject:
        properties:
          apiVersion:
            enum:
              - apps/v1
            type: string
          kind:
            enum:
              - Deployment
              - StatefulSet
            type: string
          metadata:
            properties:
              name:
                type: string
              namespace:
                type: string
            required:
              - name
              - namespace
            type: object
        required:
          - apiVersion
          - kind
          - metadata
        type: object
    required:
      - kubernetesObject
    type: object
description: This fault injects a network policy which blocks traffic on all ingress ports of a given workload.
expectation: Other workloads will be unable to communicate with the faulted pod(s) on the correct port. This usually results in increased latency and errors in
  applications.
name: Ingress Port Blocking Network Policy
platform: Kubernetes
resources:
  - https://kubernetes.io/docs/concepts/workloads/
  - https://kubernetes.io/docs/concepts/services-networking/network-policies/
  - https://kubernetes.io/docs/tasks/administer-cluster/quota-api-object/
  - https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/
  - https://kubernetes.io/docs/reference/kubernetes-api/policy-resources/network-policy-v1/
solutions:
  templates:
    - steps:
        - command: kubectl -n {{ args.kubernetesObject.metadata.namespace }} get networkpolicy
          text: Retrieve and review the configuration of the network policy(s) in the affected namespace.
        - command: kubectl -n {{ args.kubernetesObject.metadata.namespace }} edit networkpolicy {{ args.kubernetesObject.metadata.name }}-ingress
          text: Manually edit the manifest(s) and allow access to workload's ports of the network policy(s).
    - steps:
        - command: kubectl -n {{ args.kubernetesObject.metadata.namespace }} get networkpolicy
          text: Retrieve and review the configuration of the network policy(s) in the affected namespace.
        - command: kubectl -n {{ args.kubernetesObject.metadata.namespace }} edit networkpolicy {{ args.kubernetesObject.metadata.name }}-ingress
          text: Delete the offending network policy(s) if it is no longer required.
tags:
  - Deployment
  - Networking
