---
- name: Uninstall SRE tools
  hosts:
    - localhost
  tasks:
    - name: Import cluster role
      ansible.builtin.import_role:
        name: cluster
      vars:

    - name: Import tools role
      ansible.builtin.import_role:
        name: tools
        tasks_from: uninstall.yaml
      vars:
        tools_cluster:
          platform: "{{ cluster_platform }}"
          provider: "{{ cluster_provider }}"
