---
apiVersion: itbench.io/v2
kind: Scenario
metadata:
  name: scenario-60
spec:
  applications:
    opentelemetryDemo:
      enabled: true
  faults:
    - injections:
        - args:
            configMapName: features
            kubernetesObject:
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: recommendation
                namespace: otel-demo
          id: crashing-kubernetes-workload-init-container
    - injections:
        - args:
            container:
              name: checkout
            kubernetesObject:
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: checkout
                namespace: otel-demo
          id: unsupported-architecture-kubernetes-workload-container-image
      waitFor:
        postInjection:
          - args:
              kubernetesObject:
                apiVersion: apps/v1
                kind: Deployment
                metadata:
                  name: checkout
                  namespace: otel-demo
            id: delete-workload-pods
  tools:
    sre:
      enabled: true
