---
- name: Create temporary directory for records from {{ recorder.name }}
  ansible.builtin.tempfile:
    prefix: "{{ export.directory }}"
    state: directory
  register: recorders_export_directory

- name: Copy files from volume
  block:
    - name: Create Pod to export records from {{ recorder.name }}
      kubernetes.core.k8s:
        kubeconfig: "{{ recorders_cluster.kubeconfig }}"
        resource_definition:
          apiVersion: v1
          kind: Pod
          metadata:
            labels:
              "app.kubernetes.io/component": "records-exporter"
              "app.kubernetes.io/managed-by": ITBench
              "app.kubernetes.io/name": "{{ recorder.name }}-exporter"
              "app.kubernetes.io/part-of": data-collection
            name: "{{ recorder.name }}-exporter"
            namespace: "{{ recorder.namespace }}"
          spec:
            containers:
              - name: exporter
                image: registry.access.redhat.com/ubi10:10.2-1790841271@sha256:454c3b22fd9dc97859df5a6bce662da1af5e3cf18313ef034190de3759392add
                command:
                  - /bin/sh
                args:
                  - -c
                  - "sleep 600"
                resources:
                  requests:
                    cpu: 10m
                    memory: 50Mi
                  limits:
                    memory: 100Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                      - ALL
                volumeMounts:
                  - name: records
                    mountPath: /opt/app-root/src/records
            securityContext:
              fsGroup: 1001
              runAsUser: 1001
              runAsNonRoot: true
              seccompProfile:
                type: RuntimeDefault
            volumes:
              - name: records
                persistentVolumeClaim:
                  claimName: "{{ recorder.name }}-records"
        state: present
        wait: true
        wait_condition:
          type: Ready
          status: "True"

    - name: Copy records from pod
      kubernetes.core.k8s_cp:
        kubeconfig: "{{ recorders_cluster.kubeconfig }}"
        local_path: "{{ recorders_export_directory.path }}"
        namespace: "{{ recorder.namespace }}"
        pod: "{{ recorder.name }}-exporter"
        remote_path: /opt/app-root/src/records
        state: from_pod
  always:
    - name: Delete Pod
      kubernetes.core.k8s:
        kubeconfig: "{{ recorders_cluster.kubeconfig }}"
        resource_definition:
          apiVersion: v1
          kind: Pod
          metadata:
            name: "{{ recorder.name }}-exporter"
            namespace: "{{ recorder.namespace }}"
        state: absent
        wait: true

- name: Copy exported data into local directory
  when:
    - recorders_storage_local is ansible.builtin.defined
  block:
    - name: Create local directory for exported data
      ansible.builtin.file:
        mode: "0755"
        path: |-
          {{
            [
              recorders_storage_local.directory,
              export.directory
            ] |
            ansible.builtin.path_join
          }}
        state: directory
      register: recorders_local_directory

    - name: Copy exported data into local directory
      ansible.builtin.copy:
        dest: "{{ recorders_local_directory.path }}"
        mode: "0644"
        src: "{{ recorders_export_directory.path }}/"

- name: Copy exported data into S3
  when:
    - recorders_storage_s3 is ansible.builtin.defined
  block:
    - name: Retrieve all files in temporary directory for {{ recorder.name }}
      ansible.builtin.find:
        path: "{{ recorders_export_directory.path }}"
      register: recorders_exported_files

    - name: Create AWS S3 bucket
      amazon.aws.s3_bucket:
        endpoint_url: "{{ recorders_storage_s3.endpoint }}"
        name: "{{ recorders_storage_s3.bucket }}"
        state: present

    - name: Upload exported data to S3 bucket
      amazon.aws.s3_object:
        bucket: "{{ recorders_storage_s3.bucket }}"
        endpoint_url: "{{ recorders_storage_s3.endpoint }}"
        mode: put
        object: |-
          {{
            [
              recorders_storage_s3.directory,
              export.directory,
              (record.path | ansible.builtin.basename)
            ] |
            ansible.builtin.path_join
          }}
        src: "{{ record.path }}"
      loop: "{{ recorders_exported_files.files }}"
      loop_control:
        label: file/{{ record.path | ansible.builtin.basename }}
        loop_var: record

- name: Delete temporary directory for records from {{ recorder.name }}
  ansible.builtin.file:
    path: "{{ recorders_export_directory.path }}"
    state: absent
