---
- name: Import variable setting tasks
  ansible.builtin.import_role:
    name: tools
    tasks_from: set_credentials_clickhouse
  vars:
    tools_cluster:
      kubeconfig: "{{ recorders_cluster.kubeconfig }}"

- name: Create PersistentVolumeClaim for clickhouse-recorder
  kubernetes.core.k8s:
    kubeconfig: "{{ recorders_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        labels:
          "app.kubernetes.io/managed-by": ITBench
          "app.kubernetes.io/name": "{{ recorders_instances.clickhouse_data_recorder.name }}-records"
        name: "{{ recorders_instances.clickhouse_data_recorder.name }}-records"
        namespace: "{{ recorders_namespaces.data_recorders }}"
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
        volumeMode: Filesystem
    state: present

- name: Wait for any ongoing jobs to be removed
  kubernetes.core.k8s_info:
    api_version: batch/v1
    kind: Job
    kubeconfig: "{{ recorders_cluster.kubeconfig }}"
    name: "{{ recorders_instances.clickhouse_data_recorder.name }}"
    namespace: "{{ recorders_instances.clickhouse_data_recorder.namespace }}"
  register: recorders_job
  until:
    - recorders_job.resources | ansible.builtin.length == 0
  retries: 6
  delay: 30

- name: Install Kubernetes Job for clickhouse-recorder
  kubernetes.core.k8s:
    kubeconfig: "{{ recorders_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: batch/v1
      kind: Job
      metadata:
        labels:
          "app.kubernetes.io/managed-by": ITBench
          "app.kubernetes.io/name": "{{ recorders_instances.clickhouse_data_recorder.name }}"
        name: "{{ recorders_instances.clickhouse_data_recorder.name }}"
        namespace: "{{ recorders_namespaces.data_recorders }}"
      spec:
        ttlSecondsAfterFinished: 10
        template:
          metadata:
            labels:
              "app.kubernetes.io/managed-by": ITBench
              "app.kubernetes.io/name": "{{ recorders_instances.clickhouse_data_recorder.name }}"
          spec:
            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                    - matchExpressions:
                        - key: node-role.itbench.io/sandbox
                          operator: DoesNotExist
            containers:
              - name: recorder
                image: quay.io/it-bench/clickhouse-recorder:1.0.0
                env:
                  - name: CLICKHOUSE_HOST
                    value: "{{ tools_clickhouse_endpoint.tcp }}"
                  - name: CLICKHOUSE_USERNAME
                    value: "{{ tools_clickhouse_username }}"
                  - name: CLICKHOUSE_PASSWORD
                    value: "{{ tools_clickhouse_password }}"
                resources:
                  requests:
                    cpu: 500m
                    memory: 1Gi
                  limits:
                    memory: 15Gi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                      - ALL
                volumeMounts:
                  - name: records
                    mountPath: /root/records
            restartPolicy: Never
            securityContext:
              fsGroup: 0
              runAsNonRoot: false
              seccompProfile:
                type: RuntimeDefault
            volumes:
              - name: records
                persistentVolumeClaim:
                  claimName: "{{ recorders_instances.clickhouse_data_recorder.name }}-records"
    state: present
