---
- name: Wait for any ongoing jobs to be removed
  kubernetes.core.k8s_info:
    api_version: batch/v1
    kind: Job
    kubeconfig: "{{ recorders_cluster.kubeconfig }}"
    name: "{{ recorders_instances.kubernetes_topology_monitor_data_recorder.name }}"
    namespace: "{{ recorders_instances.kubernetes_topology_monitor_data_recorder.namespace }}"
  register: recorders_job
  until:
    - recorders_job.resources | ansible.builtin.length == 0
  retries: 8
  delay: 15
- name: Create PersistentVolumeClaim for kubernetes-topology-monitor-recorder
  kubernetes.core.k8s:
    kubeconfig: "{{ recorders_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        labels:
          "app.kubernetes.io/managed-by": ITBench
          "app.kubernetes.io/name": "{{ recorders_instances.kubernetes_topology_monitor_data_recorder.name }}-records"
        name: "{{ recorders_instances.kubernetes_topology_monitor_data_recorder.name }}-records"
        namespace: "{{ recorders_namespaces.data_recorders }}"
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        volumeMode: Filesystem
    state: present

- name: Install Kubernetes Job for kubernetes-topology-monitor-recorder
  kubernetes.core.k8s:
    kubeconfig: "{{ recorders_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: batch/v1
      kind: Job
      metadata:
        labels:
          "app.kubernetes.io/managed-by": ITBench
          "app.kubernetes.io/name": "{{ recorders_instances.kubernetes_topology_monitor_data_recorder.name }}"
        name: "{{ recorders_instances.kubernetes_topology_monitor_data_recorder.name }}"
        namespace: "{{ recorders_namespaces.data_recorders }}"
      spec:
        ttlSecondsAfterFinished: 10
        template:
          metadata:
            labels:
              "app.kubernetes.io/managed-by": ITBench
              "app.kubernetes.io/name": "{{ recorders_instances.kubernetes_topology_monitor_data_recorder.name }}"
          spec:
            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                    - matchExpressions:
                        - key: node-role.itbench.io/sandbox
                          operator: DoesNotExist
            containers:
              - name: recorder
                image: quay.io/it-bench/kubernetes-topology-monitor-recorder:1.0.0
                env:
                  - name: FILENAME_ANNOTATION
                    value: "{{ file_name_prefixes[recorders_configuration.phase] }}"
                  - name: KUBERNETES_TOPOLOGY_MONITOR_ENDPOINT
                    value: "{{ tools_kubernetes_topology_monitor_endpoint.http }}"
                resources:
                  requests:
                    cpu: 100m
                    memory: 128Mi
                  limits:
                    memory: 512Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                      - ALL
                volumeMounts:
                  - name: records
                    mountPath: /root/records
            restartPolicy: Never
            securityContext:
              fsGroup: 0
              runAsNonRoot: false
              seccompProfile:
                type: RuntimeDefault
            volumes:
              - name: records
                persistentVolumeClaim:
                  claimName: "{{ recorders_instances.kubernetes_topology_monitor_data_recorder.name }}-records"
    state: present
