---
- name: Import setup tasks
  ansible.builtin.import_tasks:
    file: setup.yaml
  tags:
    - setup_recording

- name: Import export tasks
  ansible.builtin.import_tasks:
    file: export.yaml
  tags:
    - export_records

- name: Import teardown tasks
  ansible.builtin.import_tasks:
    file: teardown.yaml
  tags:
    - teardown_recording
