---
- name: Create namespace for data collection recorders
  kubernetes.core.k8s:
    kubeconfig: "{{ recorders_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        labels:
          "pod-security.kubernetes.io/audit": restricted
          "pod-security.kubernetes.io/audit-version": v1.34
          "pod-security.kubernetes.io/enforce": restricted
          "pod-security.kubernetes.io/enforce-version": v1.34
          "pod-security.kubernetes.io/warn": restricted
          "pod-security.kubernetes.io/warn-version": v1.34
        name: "{{ recorders_namespaces.data_recorders }}"
    state: present

- name: Create ConfigMap for Prometheus data collection
  kubernetes.core.k8s:
    kubeconfig: "{{ recorders_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        labels:
          "app.kubernetes.io/component": prometheus-recorder
          "app.kubernetes.io/managed-by": ITBench
          "app.kubernetes.io/name": "{{ recorders_instances.prometheus_data_recorder.name }}-config"
          "app.kubernetes.io/part-of": data-collection
        name: "{{ recorders_instances.prometheus_data_recorder.name }}-config"
        namespace: "{{ recorders_namespaces.data_recorders }}"
      stringData:
        start: "{{ recorders_timestamps.start }}"
    state: present

- name: Create ConfigMap for Clickhouse data collection
  kubernetes.core.k8s:
    kubeconfig: "{{ recorders_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        labels:
          "app.kubernetes.io/component": clickhouse-recorder
          "app.kubernetes.io/managed-by": ITBench
          "app.kubernetes.io/name": "{{ recorders_instances.clickhouse_data_recorder.name }}-config"
          "app.kubernetes.io/part-of": data-collection
        name: "{{ recorders_instances.clickhouse_data_recorder.name }}-config"
        namespace: "{{ recorders_namespaces.data_recorders }}"
      stringData:
        start: "{{ recorders_timestamps.start }}"
    state: present
