---
- name: Delete the namespace
  kubernetes.core.k8s:
    kubeconfig: "{{ recorders_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ recorders_namespaces.data_recorders }}"
    state: absent
    wait: true
