---
- name: Scale down all StatefulSets
  kubernetes.core.k8s_scale:
    api_version: apps/v1
    kind: StatefulSet
    kubeconfig: "{{ recorders_cluster.kubeconfig }}"
    label_selectors:
      - "app.kubernetes.io/component=recorder"
      - "app.kubernetes.io/managed-by=ITBench"
      - "app.kubernetes.io/part-of=data-collection"
    namespace: "{{ recorders_namespaces.data_recorders }}"
    replicas: 0
    wait: true
    wait_timeout: 120

- name: Wait for all jobs to finish running
  kubernetes.core.k8s_info:
    api_version: batch/v1
    kind: Job
    kubeconfig: "{{ recorders_cluster.kubeconfig }}"
    label_selectors:
      - "app.kubernetes.io/managed-by=ITBench"
    namespace: "{{ recorders_namespaces.data_recorders }}"
  register: recorders_jobs
  until:
    - recorders_jobs.resources | ansible.builtin.length == 0
  retries: 12
  delay: 30

- name: Import recorder export tasks for ClickHouse
  ansible.builtin.import_tasks:
    file: copy_recorder_files.yaml
  vars:
    export:
      directory: observability_information_from_clickhouse
    recorder: "{{ recorders_instances.clickhouse_data_recorder }}"

- name: Import recorder export tasks for Jaeger
  ansible.builtin.import_tasks:
    file: copy_recorder_files.yaml
  vars:
    export:
      directory: trace_information
    recorder: "{{ recorders_instances.jaeger_data_recorder }}"

- name: Import recorder export tasks for Kubernetes Topology Monitor
  ansible.builtin.import_tasks:
    file: copy_recorder_files.yaml
  vars:
    export:
      directory: topology_information
    recorder: "{{ recorders_instances.kubernetes_topology_monitor_data_recorder }}"

- name: Import recorder export tasks for Prometheus
  ansible.builtin.import_tasks:
    file: copy_recorder_files.yaml
  vars:
    export:
      directory: alerts
    recorder: "{{ recorders_instances.prometheus_data_recorder }}"

- name: Delete the namespace
  kubernetes.core.k8s:
    kubeconfig: "{{ recorders_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ recorders_namespaces.data_recorders }}"
    state: absent
    wait: true
