---
apiVersion: itbench.io/v2
kind: EvaluationCriteria
metadata:
  name: scenario-64
spec:
  checks:
    - backend: kyverno-policy-report
      passingResult: pass
      resource:
        apiVersion: apps/v1
        kind: Deployment
        name: backend
        namespace: benchmarks
