---
apiVersion: itbench.io/v2
kind: GroundTruth
metadata:
  name: scenario-64
spec:
  alerts: []
  entities:
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: backend
        namespace: benchmarks
  kubernetes:
    resources: []
  opa:
    checks: []
  solutions:
    - - steps:
          - command: kubectl -n benchmarks delete deployment backend
            text: Delete the non-compliant Deployment that uses hostNetwork.
          - text: Author and apply a Kyverno ClusterPolicy that disallows hostNetwork on all workloads.
