---
tools_managers:
  cert_manager:
    helm:
      chart:
        reference: "{{ packages.helm_charts.cert_manager.registry }}"
        version: "{{ packages.helm_charts.cert_manager.version }}"
      release:
        name: cert-manager
    kubernetes:
      namespace: cert-manager
  chaos_mesh:
    helm:
      chart:
        reference: "{{ packages.helm_charts.chaos_mesh.name }}"
        repository: "{{ packages.helm_charts.chaos_mesh.repository }}"
        version: "{{ packages.helm_charts.chaos_mesh.version }}"
      release:
        name: chaos-mesh
    kubernetes:
      namespace: chaos-mesh
  clickhouse_operator:
    helm:
      chart:
        reference: "{{ packages.helm_charts.alinity_clickhouse_operator.registry }}"
        version: "{{ packages.helm_charts.alinity_clickhouse_operator.version }}"
      release:
        name: clickhouse-operator
    instances:
      kubernetes:
        namespace: clickhouse
      names:
        main: main
    kubernetes:
      namespace: clickhouse-operator
  istio_base:
    helm:
      chart:
        reference: "{{ packages.helm_charts.istio_base.registry }}"
        version: "{{ packages.helm_charts.istio_base.version }}"
      release:
        name: istio-base
    kubernetes:
      namespace: istio-system
  istio_cni:
    helm:
      chart:
        reference: "{{ packages.helm_charts.istio_cni.registry }}"
        version: "{{ packages.helm_charts.istio_cni.version }}"
      release:
        name: istio-cni
    kubernetes:
      namespace: istio-system
    openshift:
      namespace: kube-system
  istio_istiod:
    helm:
      chart:
        reference: "{{ packages.helm_charts.istio_istiod.registry }}"
        version: "{{ packages.helm_charts.istio_istiod.version }}"
      release:
        name: istiod
    kubernetes:
      namespace: istio-system
  istio_ztunnel:
    helm:
      chart:
        reference: "{{ packages.helm_charts.istio_ztunnel.registry }}"
        version: "{{ packages.helm_charts.istio_ztunnel.version }}"
      release:
        name: ztunnel
    kubernetes:
      namespace: istio-system
    openshift:
      namespace: kube-system
  kubernetes_gateway:
    git:
      repository: "{{ packages..git_repositories.kubernetes_gateway_api.repository }}"
      tag: "{{ packages..git_repositories.kubernetes_gateway_api.tag }}"
    instances:
      kubernetes:
        namespace: kube-gateways
      names:
        istio: istio-main
  kubernetes_metrics_server:
    helm:
      chart:
        reference: "{{ packages.helm_charts.kubernetes_metrics_server.name }}"
        repository: "{{ packages.helm_charts.kubernetes_metrics_server.repository }}"
        version: "{{ packages.helm_charts.kubernetes_metrics_server.version }}"
      release:
        name: kube-metrics-server
    kubernetes:
      namespace: kube-metrics-server
  kubernetes_topology_monitor:
    git:
      branch: "{{ packages..git_repositories.kubernetes_topology_monitor.branch }}"
      repository: "{{ packages..git_repositories.kubernetes_topology_monitor.repository }}"
    helm:
      release:
        name: kube-topology-monitor
    kubernetes:
      namespace: topology-monitor
  opencost:
    helm:
      chart:
        reference: "{{ packages.helm_charts.opencost.registry }}"
        version: "{{ packages.helm_charts.opencost.version }}"
      release:
        name: opencost
    kubernetes:
      namespace: opencost
  opensearch:
    helm:
      chart:
        reference: "{{ packages.helm_charts.opensearch.name }}"
        repository: "{{ packages.helm_charts.opensearch.repository }}"
        version: "{{ packages.helm_charts.opensearch.version }}"
      release:
        name: opensearch
    kubernetes:
      namespace: opensearch
  opentelemetry_operator:
    helm:
      chart:
        reference: "{{ packages.helm_charts.opentelemetry_operator.registry }}"
        version: "{{ packages.helm_charts.opentelemetry_operator.version }}"
      release:
        name: opentelemetry-operator
    instances:
      kubernetes:
        namespace: opentelemetry-collectors
      names:
        istio: istio
        jaeger: jaeger
        kubernetes_events: kubernetes-events
        kubernetes_objects_snapshot: kubernetes-objects-snapshot
    kubernetes:
      namespace: opentelemetry-operator
  prometheus:
    helm:
      chart:
        reference: "{{ packages.helm_charts.kube_prometheus_stack.registry }}"
        version: "{{ packages.helm_charts.kube_prometheus_stack.version }}"
      release:
        name: prometheus
    kubernetes:
      namespace: prometheus
    openshift:
      namespace: openshift-user-workload-monitoring
