---
- name: KOps (Kubernetes Operations) Cluster Management
  hosts:
    - localhost
  tasks:
    - name: Create kOps configuration variable
      ansible.builtin.set_fact:
        kops_configuration:
          aws: "{{ aws }}"
          cluster: "{{ cluster }}"
          ssh_keys: "{{ ssh_keys }}"

    - name: Add docker information to configuration
      ansible.builtin.set_fact:
        kops_configuration: "{{ kops_configuration | ansible.builtin.combine({'docker': docker}) }}"
      when:
        - docker is defined

    - name: Import kOps role
      ansible.builtin.import_role:
        name: kops
      vars:
        kops_cluster_group:
          clusters: "{{ kops_cluster_name | ansible.builtin.default(runner.name.prefix + 'aws.k8s.local') }}"
          name: "{{ stack.name.prefix }}"
