---
- name: AWX Stack Cluster Management
  hosts:
    - localhost
  pre_tasks:
    - name: Validate runners cluster count
      ansible.builtin.assert:
        that:
          - stack.runners.count > 0
        fail_msg: Invalid number of kOps clusters set. Must be greater than 0.
        success_msg: Valid number of kOps clusters configured.
  tasks:
    - name: Create kOps configuration variable
      ansible.builtin.set_fact:
        kops_configuration:
          aws: "{{ aws }}"
          cluster: "{{ cluster }}"
          ssh_keys: "{{ ssh_keys }}"

    - name: Add docker information to configuration
      ansible.builtin.set_fact:
        kops_configuration: "{{ kops_configuration | ansible.builtin.combine({'docker': docker}) }}"
      when:
        - docker is defined

    - name: Import kOps role
      ansible.builtin.import_role:
        name: kops
      vars:
        kops_cluster_group:
          clusters: |-
            {{
              (
                [
                  stack.name.prefix + "-head-aws.k8s.local"
                ]
              ) +
              (
                [
                  range(1, stack.runners.count + 1) |
                  map("format", stack.name.prefix + "-runner-%s-aws.k8s.local")
                ]
              )
            }}
          name: "{{ stack.name.prefix }}"
