---
- name: Sync stack group variables with scenarios directory
  hosts:
    - localhost
  pre_tasks:
    - name: Validate target variable
      ansible.builtin.assert:
        that:
          - target == "argo-stack"
        fail_msg: Invalid target provided. This playbook only supports the argo-stack target.
        success_msg: Valid target provided.

    - name: Fail playbook with `directory not found` error
      ansible.builtin.fail:
        msg: Unable to find group variable directory. Please ensure the path exists.
      when:
        - not scenarios_group_variables_directory is ansible.builtin.directory
  tasks:
    - name: Retrieve exported environment kubeconfigs
      ansible.builtin.find:
        path: "{{ kubeconfig_directory | ansible.builtin.realpath }}"
        patterns:
          - "{{ name_prefix }}-environment-*"
      register: kubeconfig_paths
      vars:
        kubeconfig_directory: "{{ playbook_dir }}/../kubeconfigs"

    - name: Write stack group variables
      block:
        - name: Validate the existence of kubeconfigs
          ansible.builtin.assert:
            that:
              - kubeconfig_paths.matched == environments_count | int
            fail_msg: Unable to find kubeconfigs. Please ensure that cluster kubeconfigs have been exported.
            success_msg: Located kubeconfigs.

        - name: Write stack group variables
          ansible.builtin.copy:
            content: |-
              {{
                (
                  {
                    "stack": {
                      "environments": (
                        [] |
                        ansible.builtin.zip_longest(
                          (
                            kubeconfig_paths.files |
                            ansible.builtin.selectattr("path", "search", name_prefix ~ "-environment") |
                            map(attribute="path")
                          ),
                          fillvalue="kubeconfig"
                        ) |
                        map("ansible.builtin.batch", 2) |
                        map("ansible.builtin.dict")
                      )
                    }
                  }
                ) |
                ansible.builtin.to_nice_yaml(explicit_start=true, indent=2)
              }}
            dest: "{{ [scenarios_group_variables_directory, 'stack.yaml'] | ansible.builtin.path_join }}"
            mode: "0644"
