---
- name: Generate files from templates
  vars:
    faults: "{{ generator_library_index.faults }}"
  block:
    - name: Create faults roles meta argument specs file
      ansible.builtin.template:
        dest: "{{ [role_path, 'meta', 'argument_specs.yaml'] | ansible.builtin.path_join }}"
        mode: "0644"
        src: templates/meta/argument_specs.j2

    - name: Create faults `task_files` variable
      ansible.builtin.template:
        dest: "{{ [role_path, 'vars', 'main', 'task_files.yaml'] | ansible.builtin.path_join }}"
        mode: "0644"
        src: templates/vars/task_files.j2

    - name: Create faults unimplemeneted injection task
      ansible.builtin.template:
        dest: "{{ [role_path, 'tasks', task_file_name] | ansible.builtin.path_join }}"
        force: false
        mode: "0644"
        src: templates/tasks/inject_unimplemented.j2
      loop: "{{ faults }}"
      loop_control:
        label: fault/{{ fault.id }}
        loop_var: fault
      vars:
        task_file_name: inject_{{ fault.id | ansible.builtin.replace('-', '_') }}.yaml
