---
- name: Include fault argument validation tasks
  ansible.builtin.include_tasks:
    file: validate_fault_arguments.yaml

- name: Include worker nodes validation tasks
  ansible.builtin.include_tasks:
    file: validate_worker_nodes.yaml

- name: Select an available worker node randomly
  ansible.builtin.set_fact:
    faults_node: "{{ faults_worker_nodes.resources | ansible.builtin.random }}"

- name: Create PriorityClass (high priority)
  kubernetes.core.k8s:
    kubeconfig: "{{ faults_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: scheduling.k8s.io/v1
      kind: PriorityClass
      metadata:
        labels:
          "app.kubernetes.io/managed-by": ITBench
        name: application-critical
      value: 10000
      globalDefault: false
      description: High priorty class for application workloads
    state: present

- name: Create PriorityClass (lower priority)
  kubernetes.core.k8s:
    kubeconfig: "{{ faults_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: scheduling.k8s.io/v1
      kind: PriorityClass
      metadata:
        labels:
          "app.kubernetes.io/managed-by": ITBench
        name: application-non-critical
      value: 1
      globalDefault: false
      description: Lower priorty class for application workloads
    state: present

- name: Patch workload with priority class and assign to node
  kubernetes.core.k8s:
    kubeconfig: "{{ faults_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: "{{ faults_kubernetes_object.apiVersion }}"
      kind: "{{ faults_kubernetes_object.kind }}"
      metadata:
        name: "{{ faults_kubernetes_object.metadata.name }}"
        namespace: "{{ faults_kubernetes_object.metadata.namespace }}"
      spec:
        template:
          spec:
            nodeSelector:
              "kubernetes.io/hostname": "{{ faults_node.metadata.name }}"
            priorityClassName: application-non-critical
    state: patched

- name: Wait for workload to update
  kubernetes.core.k8s_info:
    api_version: "{{ faults_kubernetes_object.apiVersion }}"
    kubeconfig: "{{ faults_cluster.kubeconfig }}"
    kind: "{{ faults_kubernetes_object.kind }}"
    name: "{{ faults_kubernetes_object.metadata.name }}"
    namespace: "{{ faults_kubernetes_object.metadata.namespace }}"
  register: faults_patched_workload
  until:
    - faults_patched_workload.api_found
    - faults_patched_workload.resources | ansible.builtin.length == 1
    - faults_patched_workload.resources[0].status.availableReplicas == faults_patched_workload.resources[0].status.replicas
  delay: 15
  retries: 20

- name: Create priority workload
  kubernetes.core.k8s:
    kubeconfig: "{{ faults_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        labels:
          "app.kubernetes.io/name": critical-data-collector
        name: critical-data-collector
        namespace: "{{ faults_kubernetes_object.metadata.namespace }}"
      spec:
        replicas: "{{ replicas + 1 }}"
        selector:
          matchLabels:
            "app.kubernetes.io/name": critical-data-collector
        template:
          metadata:
            labels:
              "app.kubernetes.io/name": critical-data-collector
          spec:
            containers:
              - name: worker
                image: registry.access.redhat.com/ubi10-minimal:10.2-1779773684
                command:
                  - /bin/sh
                args:
                  - -c
                  - "sleep infinity"
                resources:
                  requests:
                    cpu: "{{ ((((faults_node.status.allocatable.cpu | int) - 1) / replicas) * 1000) }}m"
                    memory: 1Mi
            nodeSelector:
              "kubernetes.io/hostname": "{{ faults_node.metadata.name }}"
            priorityClassName: application-critical
    state: present
    wait: true
  vars:
    replicas: 20
