---
- name: Import fault argument validation tasks
  ansible.builtin.import_tasks:
    file: validate_fault_arguments.yaml

- name: Import worker nodes validation tasks
  ansible.builtin.import_tasks:
    file: validate_worker_nodes.yaml

- name: Select an available worker node randomly
  ansible.builtin.set_fact:
    faults_node: "{{ faults_worker_nodes.resources | ansible.builtin.random }}"

- name: Update workload containers
  kubernetes.core.k8s:
    kubeconfig: "{{ faults_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: "{{ faults_kubernetes_object.apiVersion }}"
      kind: "{{ faults_kubernetes_object.kind }}"
      metadata:
        name: "{{ faults_kubernetes_object.metadata.name }}"
        namespace: "{{ faults_kubernetes_object.metadata.namespace }}"
      spec:
        template:
          spec:
            containers:
              - name: "{{ faults_container.name }}"
                image: quay.io/it-bench/hello-bench-arm64:2.0.0
            nodeSelector:
              "kubernetes.io/hostname": "{{ faults_node.metadata.name }}"
    state: patched
  when:
    - faults_node.status.nodeInfo.architecture == "amd64"

- name: Update workload containers
  kubernetes.core.k8s:
    kubeconfig: "{{ faults_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: "{{ faults_kubernetes_object.apiVersion }}"
      kind: "{{ faults_kubernetes_object.kind }}"
      metadata:
        name: "{{ faults_kubernetes_object.metadata.name }}"
        namespace: "{{ faults_kubernetes_object.metadata.namespace }}"
      spec:
        template:
          spec:
            containers:
              - name: "{{ faults_container.name }}"
                image: quay.io/it-bench/hello-bench-amd64:2.0.0
            nodeSelector:
              "kubernetes.io/hostname": "{{ faults_node.metadata.name }}"
    state: patched
  when:
    - faults_node.status.nodeInfo.architecture == "arm64"
