---
- name: Include fault argument validation tasks
  ansible.builtin.include_tasks:
    file: validate_fault_arguments.yaml

- name: Create fault injection job
  kubernetes.core.k8s:
    kubeconfig: "{{ faults_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: valkey-password-management
        namespace: "{{ faults_kubernetes_object.metadata.namespace }}"
      spec:
        ttlSecondsAfterFinished: 10
        template:
          spec:
            restartPolicy: Never
            containers:
              - name: injector
                image: docker.io/valkey/valkey:9.1.2-alpine3.24@sha256:48332870af354a799964c0012ae1194a0bf2bf894eb508f945810596dc2d8d11
                command:
                  - valkey-cli
                args:
                  - -h
                  - "{{ faults_kubernetes_object.metadata.name }}.{{ faults_kubernetes_object.metadata.namespace }}.svc.cluster.local"
                  - CONFIG
                  - SET
                  - requirepass
                  - invalid_password # pragma: allowlist secret
    state: present
    wait: true
    wait_condition:
      type: Complete
      status: "True"
