---
- name: Include fault argument validation tasks
  ansible.builtin.include_tasks:
    file: validate_fault_arguments.yaml

- name: Create Secret
  kubernetes.core.k8s:
    kubeconfig: "{{ faults_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: valkey-credentials
        namespace: "{{ faults_kubernetes_object.metadata.namespace }}"
      stringData:
        valkey-password: invalid_password # pragma: allowlist secret
    state: present

- name: Update workload containers
  kubernetes.core.k8s:
    kubeconfig: "{{ faults_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: "{{ faults_kubernetes_object.apiVersion }}"
      kind: "{{ faults_kubernetes_object.kind }}"
      metadata:
        name: "{{ faults_kubernetes_object.metadata.name }}"
        namespace: "{{ faults_kubernetes_object.metadata.namespace }}"
      spec:
        template:
          spec:
            containers:
              - name: "{{ faults_container.name }}"
                command:
                  - valkey-server
                args:
                  - --requirepass
                  - $(VALKEY_PASSWORD)
                env:
                  - name: VALKEY_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        name: valkey-credentials
                        key: valkey-password
    state: patched
