---
- name: Include fault argument validation tasks
  ansible.builtin.include_tasks:
    file: validate_fault_arguments.yaml

- name: Create PersistentVolumeClaim
  kubernetes.core.k8s:
    kubeconfig: "{{ faults_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: "{{ faults_kubernetes_object.metadata.name }}"
        namespace: "{{ faults_kubernetes_object.metadata.namespace }}"
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 25Mi
        storageClassName: invalid-class-name
    state: present

- name: Update workload containers
  kubernetes.core.k8s:
    kubeconfig: "{{ faults_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: "{{ faults_kubernetes_object.apiVersion }}"
      kind: "{{ faults_kubernetes_object.kind }}"
      metadata:
        name: "{{ faults_kubernetes_object.metadata.name }}"
        namespace: "{{ faults_kubernetes_object.metadata.namespace }}"
      spec:
        template:
          spec:
            containers:
              - name: "{{ faults_container.name }}"
                volumeMounts:
                  - name: database
                    mountPath: /data/database
            securityContext:
              fsGroup: 1000
            volumes:
              - name: database
                persistentVolumeClaim:
                  claimName: "{{ faults_kubernetes_object.metadata.name }}"
    state: patched
