---
- name: Include fault argument validation tasks
  ansible.builtin.include_tasks:
    file: validate_fault_arguments.yaml

- name: Update namespace labels
  kubernetes.core.k8s:
    kubeconfig: "{{ faults_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: "{{ faults_kubernetes_object.apiVersion }}"
      kind: "{{ faults_kubernetes_object.kind }}"
      metadata:
        labels:
          "istio.io/dataplane-mode": none
        name: "{{ faults_kubernetes_object.metadata.name }}"
    state: patched
