---
- name: Import fault argument validation tasks
  ansible.builtin.import_tasks:
    file: validate_fault_arguments.yaml

- name: Create PeerAuthentication
  kubernetes.core.k8s:
    kubeconfig: "{{ faults_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: security.istio.io/v1
      kind: PeerAuthentication
      metadata:
        name: mtls-strict
        namespace: "{{ faults_kubernetes_object.metadata.namespace }}"
      spec:
        mtls:
          mode: STRICT
    state: present

- name: Update workload labels
  kubernetes.core.k8s:
    kubeconfig: "{{ faults_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: "{{ faults_kubernetes_object.apiVersion }}"
      kind: "{{ faults_kubernetes_object.kind }}"
      metadata:
        name: "{{ faults_kubernetes_object.metadata.name }}"
        namespace: "{{ faults_kubernetes_object.metadata.namespace }}"
      spec:
        template:
          metadata:
            labels:
              "istio.io/dataplane-mode": none
    state: patched
