---
- name: Import fault argument validation tasks
  ansible.builtin.include_tasks:
    file: validate_fault_arguments.yaml

- name: Import worker nodes validation tasks
  ansible.builtin.include_tasks:
    file: validate_worker_nodes.yaml

- name: Select an available worker node randomly
  ansible.builtin.set_fact:
    faults_node: "{{ faults_worker_nodes.resources | ansible.builtin.random }}"

- name: Assign workload to selected worker node
  kubernetes.core.k8s:
    kubeconfig: "{{ faults_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: "{{ faults_kubernetes_object.apiVersion }}"
      kind: "{{ faults_kubernetes_object.kind }}"
      metadata:
        name: "{{ faults_kubernetes_object.metadata.name }}"
        namespace: "{{ faults_kubernetes_object.metadata.namespace }}"
      spec:
        template:
          spec:
            nodeSelector:
              "kubernetes.io/hostname": "{{ faults_node.metadata.name }}"
    state: patched

- name: Wait for workload to update
  kubernetes.core.k8s_info:
    api_version: "{{ faults_kubernetes_object.apiVersion }}"
    kubeconfig: "{{ faults_cluster.kubeconfig }}"
    kind: "{{ faults_kubernetes_object.kind }}"
    name: "{{ faults_kubernetes_object.metadata.name }}"
    namespace: "{{ faults_kubernetes_object.metadata.namespace }}"
  register: faults_patched_workload
  until:
    - faults_patched_workload.api_found
    - faults_patched_workload.resources | ansible.builtin.length == 1
    - faults_patched_workload.resources[0].status.availableReplicas == faults_patched_workload.resources[0].status.replicas
  delay: 15
  retries: 20

- name: Cordon the selected worker node
  kubernetes.core.k8s_drain:
    kubeconfig: "{{ faults_cluster.kubeconfig }}"
    name: "{{ faults_node.metadata.name }}"
    state: cordon

# NOTE: Do not wait for the following operation to complete successfully.
#       It will not because the node is cordoned and thus no new pods can
#       be created on the node.

- name: Scale workload
  kubernetes.core.k8s_scale:
    api_version: "{{ faults_kubernetes_object.apiVersion }}"
    kubeconfig: "{{ faults_cluster.kubeconfig }}"
    kind: "{{ faults_kubernetes_object.kind }}"
    name: "{{ faults_kubernetes_object.metadata.name }}"
    namespace: "{{ faults_kubernetes_object.metadata.namespace }}"
    replicas: "{{ faults_kubernetes_object.spec.replicas + 1 }}"
    wait: false
