---
- name: Include injection tasks
  ansible.builtin.include_tasks:
    file: "{{ faults_task_files[injection_task.id].injection }}"
    apply:
      tags:
        - inject_faults
      vars:
        fault_args: "{{ injection_task.args }}"
  loop: "{{ faults_injection_tasks }}"
  loop_control:
    label: task/{{ injection_task.id }}
    loop_var: injection_task
