---
- name: Include fault argument validation tasks
  ansible.builtin.include_tasks:
    file: validate_fault_arguments.yaml

- name: Create ConfigMap
  kubernetes.core.k8s:
    kubeconfig: "{{ faults_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: "{{ faults_kubernetes_object.metadata.name }}-config"
        namespace: "{{ faults_kubernetes_object.metadata.namespace }}"
      data:
        config: "{{ lookup('ansible.builtin.file', 'files/scripts/crashing_kubernetes_workload_init_container/invalid_config.json') }}"
        script: "{{ lookup('ansible.builtin.file', 'files/scripts/crashing_kubernetes_workload_init_container/load_config.py') }}"
    state: present

- name: Update workload init containers
  kubernetes.core.k8s:
    kubeconfig: "{{ faults_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: "{{ faults_kubernetes_object.apiVersion }}"
      kind: "{{ faults_kubernetes_object.kind }}"
      metadata:
        name: "{{ faults_kubernetes_object.metadata.name }}"
        namespace: "{{ faults_kubernetes_object.metadata.namespace }}"
      spec:
        template:
          spec:
            initContainers:
              - name: worker
                image: registry.access.redhat.com/ubi10/python-314-minimal:10.2-1782827458
                command:
                  - /bin/sh
                args:
                  - -c
                  - "python3.14 ~/scripts/load_config.py"
                volumeMounts:
                  - name: config
                    mountPath: /opt/app-root/src/config
                    readOnly: true
                  - name: scripts
                    mountPath: /opt/app-root/src/scripts
                    readOnly: true
            volumes:
              - name: config
                configMap:
                  name: "{{ faults_kubernetes_object.metadata.name }}-config"
                  defaultMode: 0755
                  items:
                    - key: config
                      path: config.json
              - name: scripts
                configMap:
                  name: "{{ faults_kubernetes_object.metadata.name }}-config"
                  defaultMode: 0755
                  items:
                    - key: script
                      path: load_config.py
    state: patched
