---
- name: Import fault argument validation tasks
  ansible.builtin.import_tasks:
    file: validate_fault_arguments.yaml

- name: Create authorization policy for gateway
  kubernetes.core.k8s:
    kubeconfig: "{{ faults_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: security.istio.io/v1
      kind: AuthorizationPolicy
      metadata:
        name: "{{ faults_kubernetes_object.metadata.name }}-deny"
        namespace: "{{ faults_kubernetes_object.metadata.namespace }}"
      spec:
        action: DENY
        targetRef:
          group: gateway.networking.k8s.io
          kind: Gateway
          name: "{{ faults_kubernetes_object.metadata.name }}"
        rules:
          - to:
              - operation:
                  methods: "{{ injection_task.args.httpMethods }}"
    state: present
    wait: true
    wait_condition:
      reason: Accepted
      status: "True"
      type: WaypointAccepted
