---
# TODO: We need to add node labels to specific worker nodes so that the
#       the tool stack is not impacted by these faults.

- name: Retrieve worker nodes
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Node
    kubeconfig: "{{ faults_cluster.kubeconfig }}"
    label_selectors:
      - "!node-role.kubernetes.io/control-plane"
  register: faults_worker_nodes

- name: Fail playbook due to `suitable worker nodes not found` error
  ansible.builtin.fail:
    msg: "suitable worker nodes could not be found. please worker nodes are properly labeled."
  when:
    - not faults_worker_nodes.api_found
    - faults_worker_nodes.resources | ansible.builtin.length == 0
