---
- name: Validate `kubernetesObject` fault argument
  when:
    - fault_args.kubernetesObject is ansible.builtin.defined
  block:
    - name: Retrieve {{ fault_args.kubernetesObject.kind | ansible.builtin.lower }}
      kubernetes.core.k8s_info:
        kubeconfig: "{{ faults_cluster.kubeconfig }}"
        api_version: "{{ fault_args.kubernetesObject.apiVersion }}"
        kind: "{{ fault_args.kubernetesObject.kind }}"
        name: "{{ fault_args.kubernetesObject.metadata.name }}"
        namespace: "{{ fault_args.kubernetesObject.metadata.namespace | ansible.builtin.default(omit) }}"
      register: faults_args_kubernetes_object

    - name: Fail playbook due to `kubernetes object not found` error
      ansible.builtin.fail:
        msg: "{{ object.kind }}/{{ object.name }} not found. please ensure object exists before injecting this fault."
      vars:
        object:
          kind: "{{ fault_args.kubernetesObject.kind }}"
          name: "{{ fault_args.kubernetesObject.metadata.name }}"
      when:
        - not faults_args_kubernetes_object.api_found
        - faults_args_kubernetes_object.resources | ansible.builtin.length != 1

    - name: Extract object information from output
      ansible.builtin.set_fact:
        faults_kubernetes_object: "{{ faults_args_kubernetes_object.resources | ansible.builtin.first }}"

- name: Validate `container` fault argument
  when:
    - fault_args.container is ansible.builtin.defined
    - faults_kubernetes_object is ansible.builtin.defined
  block:
    - name: Retrieve container from {{ faults_kubernetes_object.name }}
      ansible.builtin.set_fact:
        faults_args_container: |-
          {{
            faults_kubernetes_object.spec.template.spec.containers |
            ansible.builtin.selectattr("name", "==", fault_args.container.name)
          }}

    - name: Fail playbook due to `kubernetes workload container not found` error
      ansible.builtin.fail:
        msg: "{{ fault_args.container.name }} not found. please ensure container exists before injecting this fault."
      when:
        - faults_args_container | ansible.builtin.length != 1

    - name: Extract object information from output
      ansible.builtin.set_fact:
        faults_container: "{{ faults_args_container | ansible.builtin.first }}"

- name: Validate `container.env` fault argument
  when:
    - fault_args.container.env is ansible.builtin.defined
    - faults_container is ansible.builtin.defined
  block:
    - name: Retrieve container from {{ faults_kubernetes_object.name }}
      ansible.builtin.set_fact:
        faults_args_container_environment_variable: |-
          {{
            faults_container.env |
            ansible.builtin.selectattr("name", "==", fault_args.container.env.name)
          }}

    - name: Fail playbook due to `kubernetes workload container environmental variable not found` error
      ansible.builtin.fail:
        msg: "{{ fault_args.container.env.name }} not found. please ensure env var exists before injecting this fault."
      when:
        - faults_args_container_environment_variable | ansible.builtin.length != 1

    - name: Extract object information from output
      ansible.builtin.set_fact:
        faults_container_environment_variable: "{{ faults_args_container_environment_variable | ansible.builtin.first }}"

- name: Validate `targetPort` fault argument
  when:
    - fault_args.targetPort is ansible.builtin.defined
    - faults_kubernetes_object is ansible.builtin.defined
  block:
    - name: Retrieve port from {{ faults_kubernetes_object.name }}
      ansible.builtin.set_fact:
        faults_args_port: |-
          {{
            faults_kubernetes_object.spec.ports |
            ansible.builtin.selectattr("targetPort", "==", fault_args.targetPort)
          }}

    - name: Fail playbook due to `kubernetes service port not found` error
      ansible.builtin.fail:
        msg: "{{ fault_args.targetPort }} not found. please ensure port exists before injecting this fault."
      when:
        - faults_args_port | ansible.builtin.length != 1

    - name: Extract object information from output
      ansible.builtin.set_fact:
        faults_port: "{{ faults_args_port | ansible.builtin.first }}"
