---
- name: Verify containers role functionality
  hosts:
    - localhost
  tasks:
    - name: Retrieve service info
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Service
        kubeconfig: ~/.kube/config
        name: test-lb-service
        namespace: cloud-provider-kind-test
      register: containers_load_balancer_service

    - name: Verify load balance was added
      ansible.builtin.assert:
        that:
          - containers_load_balancer_service.resources[0].status.loadBalancer.ingress is defined
          - containers_load_balancer_service.resources[0].status.loadBalancer.ingress | ansible.builtin.length == 1
        fail_msg: load balancer not added to service.
        success_msg: load balancer added to service.

    - name: Import containers role
      ansible.builtin.import_role:
        name: containers

    # - name: Verify cloud-provider-kind container was detected
    #   ansible.builtin.assert:
    #     that:
    #       - containers_list_result is defined
    #       - containers_list_result.stdout is defined
    #     fail_msg: cloud-provider-kind container was not detected by the containers role
    #     success_msg: cloud-provider-kind container was successfully detected
