---
docker_managers:
  kyverno:
    helm:
      chart:
        reference: "{{ packages.helm_charts.kyverno.registry }}"
        version: "{{ packages.helm_charts.kyverno.version }}"
      release:
        name: kyverno
    kubernetes:
      namespace: kyverno
