---
alerts:
  - HighRequestErrorRate
category: sre
complexity: low
description: This scenario simulates OpenTelementry Demo's `product-catalog` service being unable to accept traffic due to a missing service.
disruptions:
  - injections:
      - args:
          kubernetesObject:
            apiVersion: v1
            kind: Service
            metadata:
              name: product-catalog
              namespace: otel-demo
        id: deleted-kubernetes-service
environment:
  applications:
    - id: opentelemetry-demo
id: 114
platforms:
  - Kubernetes
solutions:
  - - steps:
        - text: Create the manifest with the expected values.
    - steps:
        - text: Apply the manifest file with the expected values to the application namespace.
tags:
  - Deployment
  - Networking
