# yaml-language-server: $schema=../schema.json
---
alerts:
  - KubePodNotReady
category: sre
complexity: medium
description: This scenario simulates node resource exhaustion by injecting excessive resource requests into the OpenTelemetry Demo's `product-catalog` service,
  causing resource pressure on the node and affecting co-located workloads.
disruptions:
  - injections:
      - args:
          kubernetesObject:
            apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: product-catalog
              namespace: otel-demo
        id: node-resource-exhaustion
environment:
  applications:
    - id: opentelemetry-demo
id: 121
platforms:
  - Kubernetes
solutions:
  - - steps:
        - command: kubectl -n otel-demo rollout undo deployment/product-catalog
          text: Revert the resource request changes to restore normal resource usage.
    - steps:
        - command: kubectl -n otel-demo edit deployment product-catalog
          text: Manually edit the manifest and set resource requests to appropriate values.
tags:
  - Deployment
  - Performance
