---
alerts: []
category: finops
complexity: low
description: This scenario simulates OpenTelemetry Demo services running normally with autoscaling.
disruptions: []
environment:
  applications:
  - args:
      autoscaling:
        kubernetes:
          hpa: true
    id: opentelemetry-demo
id: 37
platforms:
- Kubernetes
solutions: []
tags:
- Deployment
- Performance
