---
alerts:
  - KubePodCrashLooping
category: sre
complexity: low
description: This scenario simulates OpenTelemetry Demo's `valkey-cart` service experiencing an Out of Memory (OOM) error.
disruptions:
  - injections:
      - args:
          container:
            name: valkey-cart
          kubernetesObject:
            apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: valkey-cart
              namespace: otel-demo
        id: valkey-workload-out-of-memory
environment:
  applications:
    - id: opentelemetry-demo
id: 40
platforms:
  - Kubernetes
solutions:
  - - steps:
        - command: kubectl -n otel-demo rollout undo deployment/valkey-cart
          text: Revert the last change done to the manifest.
    - steps:
        - command: kubectl -n otel-demo edit deployment valkey-cart
          text: Manually edit the manifest and remove the code change volumes.
        - command: kubectl -n otel-demo delete configmap valkey-storage-script
          text: Delete the injected ConfigMap object.
    - steps:
        - command: kubectl -n otel-demo edit configmap valkey-storage-script
          text: Manually edit the manifest and change the script.
tags:
  - Deployment
  - Code
