---
alerts:
- KubePodNotReady
category: sre
complexity: medium
description: This scenario simulates BookInfo's `reviews-v3` service being unable to start due to lack of persistent storage.
disruptions:
- injections:
  - args:
      container:
        name: reviews
      kubernetesObject:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: reviews-v3
          namespace: book-info
    id: nonexistent-kubernetes-workload-persistent-volume-claim
environment:
  applications:
  - id: book-info
id: 53
platforms:
- Kubernetes
solutions:
- - steps:
    - command: kubectl -n book-info rollout undo deployment/reviews-v3
      text: Revert the last change done to the manifest.
  - steps:
    - command: kubectl -n book-info edit persistentvolumeclaim reviews-v3
      text: Manually edit the manifest and replace the `storageClassName` with the correct value.
  - steps:
    - command: kubectl -n book-info edit deployment reviews-v3
      text: Manually edit the manifest and replace the volume claim with an existing persistent volume claim.
tags:
- Deployment
