---
alerts: []
category: sre
complexity: low
description: This scenario simulates Kubernetes API server experiencing latency during OpenTelemetry Demo's execution.
disruptions:
  - injections:
      - args:
          kubernetesObject:
            apiVersion: chaos-mesh.org/v1alpha1
            kind: Schedule
            metadata:
              name: api-server-memory-stress
              namespace: chaos-mesh
          scheduleSpec:
            ioChaos:
              action: latency
              delay: 200ms
              duration: 5m
              mode: all
              percent: 50
              selector:
                labelSelectors:
                  component: etcd
                namespaces:
                  - kube-system
              volumePath: /var/lib/etcd
            type: IOChaos
        id: scheduled-chaos-mesh-experiment
environment:
  applications:
    - id: opentelemetry-demo
id: 55
platforms:
  - Kubernetes
solutions:
  - - steps:
        - command: kubectl -n chaos-mesh annotate schedule api-server-memory-stress experiment.chaos-mesh.org/pause='true'
          text: Annotate the schedule to pause the active experiment.
        - command: kubectl -n chaos-mesh get iochaos --selector='experiment.chaos-mesh.org/pause=true'
          text: Retrieve the associated experiment managed by the schedule.
        - text: Delete the retrieved experiement after it has entered the `Paused` state.
        - command: kubectl -n chaos-mesh delete schedule api-server-memory-stress experiment.chaos-mesh.org/pause='true'
          text: Delete the schedule.
tags:
  - Deployment
  - Performance
