---
alerts:
  - NoRequestsReceived
  - HighRequestErrorRate
category: sre
complexity: low
description: This scenario simulates OpenTelemetry Demo's `accounting` service being scaled to zero replicas.
disruptions:
  - injections:
      - args:
          kubernetesObject:
            apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: accounting
              namespace: otel-demo
        id: scaled-to-zero-kubernetes-workload
environment:
  applications:
    - id: opentelemetry-demo
id: 58
platforms:
  - Kubernetes
solutions:
  - - steps:
        - command: kubectl -n otel-demo rollout undo deployment/accounting
          text: Revert the last change done to the manifest.
    - steps:
        - command: kubectl -n otel-demo scale --replicas=1 deployment/accounting
          text: Manually scale the workload to the correct value.
    - steps:
        - command: kubectl -n otel-demo edit deployment accounting
          text: Manually edit the manifest and set the `replicas` field to the correct value.
tags:
  - Deployment
  - Performance
