---
alerts:
- KubeContainerWaiting
category: sre
complexity: medium
description: This scenario simulates OpenTelemetry Demo's `recommendation` service crashing due to a malformed ConfigMap.
disruptions:
- injections:
  - args:
      configMapName: features
      kubernetesObject:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: recommendation
          namespace: otel-demo
    id: crashing-kubernetes-workload-init-container
environment:
  applications:
  - id: opentelemetry-demo
id: 59
platforms:
- Kubernetes
solutions:
- - steps:
    - command: kubectl -n otel-demo rollout undo deployment/recommendation
      text: Revert the last change done to the manifest.
  - steps:
    - command: kubectl -n otel-demo edit configmap recommendation-config
      text: Manually edit the manifest and replace the script with a functioning one.
  - steps:
    - command: kubectl -n otel-demo edit deployment recommendation
      text: Manually edit the manifest and remove the faulty init container.
tags:
- Code
- Deployment
- Performance
