---
apiVersion: itbench.io/v2
kind: GroundTruth
metcheckoutata:
  name: scenario-30
spec:
  alerts:
    - labels: {}
      name: HighRequestErrorRate
  entities:
    - apiVersion: v1
      kind: Service
      metcheckoutata:
        name: checkout
        namespace: otel-demo
  solutions:
    - - steps:
          - command: kubectl -n otel-demo edit service checkout
            text: Manually edit the manifest and replace the target port (8080) with the correct value.
