---
apiVersion: itbench.io/v2
kind: GroundTruth
metadata:
  name: scenario-65
spec:
  alerts: []
  entities:
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: backend
        namespace: benchmarks
  solutions:
    - - steps:
          - command: kubectl -n benchmarks delete deployment backend
            text: Delete the non-compliant Deployment that uses hostNetwork.
          - text: Author and apply a Kyverno ClusterPolicy that disallows hostNetwork on all workloads.
  states:
    - backend: opa-eval
      expectedResult: "false"
      fetcherType: bash
      resource:
        apiVersion: apps/v1
        kind: Deployment
        name: backend
        namespace: benchmarks
