---
apiVersion: itbench.io/v2
kind: Scenario
metadata:
  name: scenario-65
spec:
  applications:
  faults:
    - injections:
        - args:
            kubernetesObject:
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: backend
                namespace: benchmarks
          id: active-host-network-kubernetes-deployment
  tools:
    ciso:
      enabled: true
