---
faults_task_files:
  cordoned-kubernetes-worker-node: inject_cordoned_kubernetes_worker_node.yaml
  crashing-kubernetes-workload-init-container: inject_crashing_kubernetes_workload_init_container.yaml
  deleted-kubernetes-service: inject_deleted_kubernetes_service.yaml
  disabled-istio-ambient-mode-kubernetes-namespace: inject_disabled_istio_ambient_mode_kubernetes_namespace.yaml
  failing-name-resolution-kubernetes-workload-dns-policy: inject_failing_name_resolution_kubernetes_workload_dns_policy.yaml
  hanging-kubernetes-workload-init-container: inject_hanging_kubernetes_workload_init_container.yaml
  ingress-port-blocking-network-policy: inject_ingress_port_blocking_network_policy.yaml
  insufficient-kubernetes-resource-quota: inject_insufficient_kubernetes_resource_quota.yaml
  insufficient-kubernetes-workload-container-resources: inject_insufficient_kubernetes_workload_container_resources.yaml
  invalid-kubernetes-service-selector: inject_invalid_kubernetes_service_selector.yaml
  invalid-kubernetes-workload-container-command: inject_invalid_kubernetes_workload_container_command.yaml
  kubernetes-api-server-request-surge: inject_kubernetes_api_server_request_surge.yaml
  misconfigured-kubernetes-horizontal-pod-autoscaler: inject_misconfigured_kubernetes_horizontal_pod_autoscaler.yaml
  misconfigured-kubernetes-workload-container-readiness-probe: inject_misconfigured_kubernetes_workload_container_readiness_probe.yaml
  modified-kubernetes-workload-container-environment-variable: inject_modified_kubernetes_workload_container_environment_variable.yaml
  modified-target-port-kubernetes-service: inject_modified_target_port_kubernetes_service.yaml
  nonexistent-kubernetes-workload-container-image: inject_nonexistent_kubernetes_workload_container_image.yaml
  nonexistent-kubernetes-workload-node: inject_nonexistent_kubernetes_workload_node.yaml
  nonexistent-kubernetes-workload-persistent-volume-claim: inject_nonexistent_kubernetes_workload_persistent_volume_claim.yaml
  opentelemetry-demo-feature-flag: inject_opentelemetry_demo_feature_flag.yaml
  priority-kubernetes-workload-priority-preemption: inject_priority_kubernetes_workload_priority_preemption.yaml
  scaled-to-zero-kubernetes-workload: inject_scaled_to_zero_kubernetes_workload.yaml
  scheduled-chaos-mesh-experiment: inject_scheduled_chaos_mesh_experiment.yaml
  strict-mutual-tls-istio-service-mesh-enforcement: inject_strict_mutual_tls_istio_service_mesh_enforcement.yaml
  traffic-denying-istio-gateway-authorization-policy: inject_traffic_denying_istio_gateway_authorization_policy.yaml
  unassigned-kubernetes-workload-container-resource-limits: inject_unassigned_kubernetes_workload_container_resource_limits.yaml
  unschedulable-kubernetes-workload-pod-anti-affinity-rule: inject_unschedulable_kubernetes_workload_pod_anti_affinity_rule.yaml
  unsupported-architecture-kubernetes-workload-container-image: inject_unsupported_architecture_kubernetes_workload_container_image.yaml
  valkey-workload-changed-password: inject_valkey_workload_changed_password.yaml # pragma: allowlist secret
  valkey-workload-out-of-memory: inject_valkey_workload_out_of_memory.yaml
