---
apiVersion: itbench.io/v2
kind: Scenario
metadata:
  name: scenario-404
spec:
  applications:
    opentelemetryDemo:
      enabled: true
  faults:
    - injections:
        - args:
            container:
              image: quay.io/shengkunrz/it-bench-dev:monzo-recommendation
              name: recommendation
            kubernetesObject:
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: recommendation
                namespace: otel-demo
          id: modify-kubernetes-workload-container-image
  tools:
    sre:
      enabled: true
