---
- name: Import validation tasks
  ansible.builtin.import_tasks:
    file: validate.yaml

- name: Import Argo Workflows installation tasks
  ansible.builtin.import_tasks:
    file: install_argo.yaml
  tags:
    - install_tools

- name: Import Argo Workflow launch tasks
  ansible.builtin.import_tasks:
    file: launch_workflows.yaml
  tags:
    - launch_workflows

- name: Import Argo Workflows uninstallation tasks
  ansible.builtin.import_tasks:
    file: uninstall_argo.yaml
  tags:
    - uninstall_tools
