---
- name: Verify that wait task succeeded
  hosts:
    - environment
  tasks:
    - name: Retrieve Deployment after pod deletion
      kubernetes.core.k8s_info:
        kubeconfig: "{{ cluster.kubeconfig }}"
        api_version: apps/v1
        kind: Deployment
        name: test-deployment
        namespace: delete-workload-pods-test
      register: waiters_deployment

    - name: Validate that Deployment exists
      ansible.builtin.assert:
        that:
          - waiters_deployment.resources | ansible.builtin.length == 1
        fail_msg: Deployment not found after pod deletion.
        success_msg: Deployment still exists after pod deletion.

    - name: Retrieve Deployment pods after deletion
      kubernetes.core.k8s_info:
        kubeconfig: "{{ cluster.kubeconfig }}"
        api_version: v1
        kind: Pod
        namespace: delete-workload-pods-test
        label_selectors:
          - app.kubernetes.io/name = test-deployment
      register: waiters_deployment_pods

    - name: Validate that Deployment pods were recreated and do not exceed replica count
      ansible.builtin.assert:
        that:
          - waiters_deployment_pods.resources | ansible.builtin.length > 0
          - (
              waiters_deployment_pods.resources | ansible.builtin.length
            ) <=
            (
              waiters_deployment.resources[0].status.unavailableReplicas +
              waiters_deployment.resources[0].status.replicas
            )
        fail_msg: Deployment pod count validation failed. Found {{ waiters_deployment_pods.resources | ansible.builtin.length }} pods.
        success_msg: Deployment pods were deleted and new pods exist within replica count limits.

    - name: Retrieve StatefulSet after pod deletion
      kubernetes.core.k8s_info:
        kubeconfig: "{{ cluster.kubeconfig }}"
        api_version: apps/v1
        kind: StatefulSet
        name: test-statefulset
        namespace: delete-workload-pods-test
      register: waiters_statefulset

    - name: Validate that StatefulSet exists
      ansible.builtin.assert:
        that:
          - waiters_statefulset.resources | ansible.builtin.length == 1
        fail_msg: StatefulSet not found after pod deletion.
        success_msg: StatefulSet still exists after pod deletion.

    - name: Retrieve StatefulSet pods after deletion
      kubernetes.core.k8s_info:
        kubeconfig: "{{ cluster.kubeconfig }}"
        api_version: v1
        kind: Pod
        namespace: delete-workload-pods-test
        label_selectors:
          - app.kubernetes.io/name = test-statefulset
      register: waiters_statefulset_pods

    - name: Validate that StatefulSet pods were recreated and do not exceed replica count
      ansible.builtin.assert:
        that:
          - waiters_statefulset_pods.resources | ansible.builtin.length > 0
          - waiters_statefulset_pods.resources | ansible.builtin.length <= waiters_statefulset.resources[0].status.replicas
        fail_msg: StatefulSet pod count validation failed. Found {{ waiters_statefulset_pods.resources | ansible.builtin.length }} pods.
        success_msg: StatefulSet pods were deleted and new pods exist within replica count limits.
