---
apiVersion: itbench.io/v2
kind: Scenario
metadata:
  name: scenario-24
spec:
  applications:
    opentelemetryDemo:
      enabled: true
  faults:
    - injections:
        - args:
            container:
              env:
                name: KAFKA_ADDR
                value: kafka:9999
              name: checkout
            kubernetesObject:
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: checkout
                namespace: otel-demo
          id: modified-kubernetes-workload-container-environment-variable
  tools:
    sre:
      enabled: true
