---
apiVersion: itbench.io/v2
kind: GroundTruth
metadata:
  name: scenario-49
spec:
  alerts:
    - labels: {}
      name: KubePodNotReady
  entities:
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: cart
        namespace: otel-demo
  solutions:
    - - steps:
          - command: kubectl -n otel-demo rollout undo deployment/cart
            text: Revert the last change done to the manifest.
      - steps:
          - command: kubectl -n otel-demo edit deployment cart
            text: Manually edit the manifest and remove the faulty readiness probe in the container rule.
