---
apiVersion: itbench.io/v2
kind: EvaluationCriteria
metadata:
  name: scenario-66
spec:
  checks:
    - backend: opa-eval
      expectedFiles:
        - policy.rego
        - fetcher.sh
      passingResult: true
