---
apiVersion: itbench.io/v2
kind: GroundTruth
metadata:
  name: scenario-66
spec:
  alerts: []
  entities:
  kubernetes:
    resources: []
  opa:
    checks: []
  solutions:
    - - steps:
          - text: Set X11Forwarding to no in /etc/ssh/sshd_config and restart the sshd service.
