---
apiVersion: itbench.io/v2
kind: GroundTruth
metadata:
  name: scenario-66
spec:
  alerts: []
  entities:
  solutions:
    - - steps:
          - text: Set X11Forwarding to no in /etc/ssh/sshd_config and restart the sshd service.
  states:
    - backend: opa-eval
      expectedResult: "false"
      fetcherType: ansible-playbook
      resource:
        kind: Host
        name: rhel9-benchmark
