collections:
  - name: amazon.aws
    version: 11.0.0
  - name: ansible.posix
    version: 2.1.0
  - name: ansible.utils
    version: 6.0.1
  - name: awx.awx
    version: 24.6.1
  - name: community.general
    version: 12.2.0
  - name: kubernetes.core
    version: 6.2.0
