---
- name: Create Kubernetes objects and directory
  hosts:
    - localhost
  tasks:
    - name: Create directory
      ansible.builtin.file:
        mode: "0755"
        path: "{{ working_directory }}"
        state: directory

    - name: Create Namespaces
      kubernetes.core.k8s:
        kubeconfig: "{{ cluster.kubeconfig }}"
        resource_definition:
          - apiVersion: v1
            kind: Namespace
            metadata:
              name: application
          - apiVersion: v1
            kind: Namespace
            metadata:
              name: observability
        state: present

    - name: Create Deployment
      kubernetes.core.k8s:
        kubeconfig: "{{ cluster.kubeconfig }}"
        resource_definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: test-app
            namespace: application
          spec:
            replicas: 1
            selector:
              matchLabels:
                "app.kubernetes.io/name": test-app
            template:
              metadata:
                labels:
                  "app.kubernetes.io/name": test-app
              spec:
                containers:
                  - name: server
                    image: registry.access.redhat.com/ubi10-minimal:10.2-1788137716@sha256:d801168f5e8b108586c27a4fd5c92e3c1e8d061084383713926e2ca61b8b6c64
                    command:
                      - /bin/sh
                    args:
                      - -c
                      - "sleep infinity"
        state: present
        wait: true

    - name: Create Deployment
      kubernetes.core.k8s:
        kubeconfig: "{{ cluster.kubeconfig }}"
        resource_definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: test-tool
            namespace: observability
          spec:
            replicas: 1
            selector:
              matchLabels:
                "app.kubernetes.io/name": test-tool
            template:
              metadata:
                labels:
                  "app.kubernetes.io/name": test-tool
              spec:
                containers:
                  - name: observer
                    image: registry.access.redhat.com/ubi10-minimal:10.2-1788137716@sha256:d801168f5e8b108586c27a4fd5c92e3c1e8d061084383713926e2ca61b8b6c64
                    command:
                      - /bin/sh
                    args:
                      - -c
                      - "sleep infinity"
        state: present
        wait: true
