---
- name: Verify that restricted kubeconfig works correctly
  hosts:
    - localhost
  tasks:
    - name: Validate restricted kubeconfig was created
      ansible.builtin.assert:
        that:
          - restricted_kubeconfig is ansible.builtin.file
        fail_msg: Restricted kubeconfig was not created.
        success_msg: Restricted kubeconfig exists.
      vars:
        restricted_kubeconfig: "{{ [working_directory, 'kubeconfig'] | ansible.builtin.path_join }}"

    - name: Check pod access in application namespace
      kubernetes.core.k8s:
        kubeconfig: "{{ cluster.kubeconfig }}"
        resource_definition:
          apiVersion: authorization.k8s.io/v1
          kind: LocalSubjectAccessReview
          metadata:
            namespace: application
          spec:
            user: system:serviceaccount:default:agent
            resourceAttributes:
              namespace: application
              verb: get
              resource: pods
              group: ""
        state: present
      register: agent_application_access_review

    - name: Validate that pod access was granted
      ansible.builtin.assert:
        that:
          - agent_application_access_review.result.status.allowed
        fail_msg: Pods are not accessible to agent. Invalid kubeconfig generated.
        success_msg: Pods are accessible to agent.

    - name: Check pod access in observability namespace
      kubernetes.core.k8s:
        kubeconfig: "{{ cluster.kubeconfig }}"
        resource_definition:
          apiVersion: authorization.k8s.io/v1
          kind: LocalSubjectAccessReview
          metadata:
            namespace: observability
          spec:
            user: system:serviceaccount:default:agent
            resourceAttributes:
              namespace: observability
              verb: get
              resource: pods
              group: ""
        state: present
      register: agent_observability_access_review

    - name: Validate that pod access was not granted in observability namespace
      ansible.builtin.assert:
        that:
          - not agent_observability_access_review.result.status.allowed
        fail_msg: Pods are accessible to agent. Invalid kubeconfig generated.
        success_msg: Pods are not accessible to agent.

    - name: Check namespace list access
      kubernetes.core.k8s:
        kubeconfig: "{{ cluster.kubeconfig }}"
        resource_definition:
          apiVersion: authorization.k8s.io/v1
          kind: SubjectAccessReview
          spec:
            user: system:serviceaccount:default:agent
            resourceAttributes:
              verb: list
              resource: namespaces
              group: ""
        state: present
      register: agent_namespace_access_review

    - name: Validate that namespace list access was not granted
      ansible.builtin.assert:
        that:
          - not agent_namespace_access_review.result.status.allowed
        fail_msg: Namespaces are accessible to agent. Invalid kubeconfig generated.
        success_msg: Namespaces are not accessible to agent.

    - name: Retrieve agent Role in application namespace
      kubernetes.core.k8s_info:
        kubeconfig: "{{ cluster.kubeconfig }}"
        api_version: rbac.authorization.k8s.io/v1
        kind: Role
        name: agent-namespace-access
        namespace: application
      register: agent_application_role

    - name: Validate agent Role was created
      ansible.builtin.assert:
        that:
          - agent_application_role.resources | ansible.builtin.length == 1
        fail_msg: Role was not created. Test failed.
        success_msg: Role was created.

    - name: Retrieve agent RoleBinding in application namespace
      kubernetes.core.k8s_info:
        kubeconfig: "{{ cluster.kubeconfig }}"
        api_version: rbac.authorization.k8s.io/v1
        kind: RoleBinding
        name: agent-namespace-access
        namespace: application
      register: agent_application_role_binding

    - name: Validate agent RoleBinding was created
      ansible.builtin.assert:
        that:
          - agent_application_role_binding.resources | ansible.builtin.length == 1
        fail_msg: RoleBinding was not created. Test failed.
        success_msg: RoleBinding was created.

    - name: Retrieve agent Role in observability namespace
      kubernetes.core.k8s_info:
        kubeconfig: "{{ cluster.kubeconfig }}"
        api_version: rbac.authorization.k8s.io/v1
        kind: Role
        name: agent-namespace-access
        namespace: observability
      register: agent_observability_role

    - name: Validate agent Role was not created in observability namespace
      ansible.builtin.assert:
        that:
          - agent_observability_role.resources | ansible.builtin.length == 0
        fail_msg: Role was created in observability namespace. Test failed.
        success_msg: Role was not created in observability namespace.

    - name: Retrieve agent RoleBinding in observability namespace
      kubernetes.core.k8s_info:
        kubeconfig: "{{ cluster.kubeconfig }}"
        api_version: rbac.authorization.k8s.io/v1
        kind: RoleBinding
        name: agent-namespace-access
        namespace: observability
      register: agent_observability_role_binding

    - name: Validate agent RoleBinding was not created in observability namespace
      ansible.builtin.assert:
        that:
          - agent_observability_role_binding.resources | ansible.builtin.length == 0
        fail_msg: RoleBinding was created in observability namespace. Test failed.
        success_msg: RoleBinding was not created in observability namespace.

    - name: Retrieve ClusterRole
      kubernetes.core.k8s_info:
        kubeconfig: "{{ cluster.kubeconfig }}"
        api_version: rbac.authorization.k8s.io/v1
        kind: ClusterRole
        name: agent-cluster-access
      register: agent_cluster_role

    - name: Validate ClusterRole was created
      ansible.builtin.assert:
        that:
          - agent_cluster_role.resources | ansible.builtin.length == 1
        fail_msg: ClusterRole was not created. Test failed.
        success_msg: ClusterRole was created.

    - name: Retrieve ClusterRoleBinding
      kubernetes.core.k8s_info:
        kubeconfig: "{{ cluster.kubeconfig }}"
        api_version: rbac.authorization.k8s.io/v1
        kind: ClusterRoleBinding
        name: agent-cluster-access
      register: agent_cluster_role_binding

    - name: Validate ClusterRoleBinding was created
      ansible.builtin.assert:
        that:
          - agent_cluster_role_binding.resources | ansible.builtin.length == 1
        fail_msg: ClusterRoleBinding was not created. Test failed.
        success_msg: ClusterRoleBinding was created.

    - name: Retrieve ServiceAccount
      kubernetes.core.k8s_info:
        kubeconfig: "{{ cluster.kubeconfig }}"
        api_version: v1
        kind: ServiceAccount
        name: agent
        namespace: default
      register: agent_service_account

    - name: Validate ServiceAccount was created
      ansible.builtin.assert:
        that:
          - agent_service_account.resources | ansible.builtin.length == 1
        fail_msg: ServiceAccount was not created. Test failed.
        success_msg: ServiceAccount was created.
