---
- name: Import fault generation tasks
  ansible.builtin.import_tasks:
    file: generate_fault_index.yaml
  tags:
    - generate_fault

- name: Import scenario generation tasks
  ansible.builtin.import_tasks:
    file: generate_scenario_index.yaml
  tags:
    - generate_scenario
