---
- name: Uninstall OpenTelemetry Demo application
  hosts:
    - localhost
  tasks:
    - name: Import applications role
      ansible.builtin.import_role:
        name: applications
        tasks_from: uninstall_opentelemetry_demo.yaml
      vars:
        applications_cluster:
          kubeconfig: "{{ cluster.kubeconfig }}"
          platform: "{{ cluster_platform }}"
