---
argument_specs:
  main:
    author:
      - Gerard Vanloo
    options:
      tools_cluster:
        required: true
        type: dict
        options:
          kubeconfig:
            required: true
            type: str
          provider:
            required: true
            type: str
          platform:
            choices:
              - kubernetes
              - openshift
            required: true
            type: str
      tools_configuration:
        required: false
        type: dict
  set_external_endpoints:
    author:
      - Gerard Vanloo
    options:
      tools_cluster:
        required: true
        type: dict
        options:
          kubeconfig:
            required: true
            type: str
          provider:
            required: true
            type: str
          platform:
            choices:
              - kubernetes
              - openshift
            required: true
            type: str
      tools_network_configuration:
        required: false
        type: dict
        options:
          cloud_provider_kind:
            required: false
            type: dict
