---
apiVersion: itbench.io/v2
kind: EvaluationCriteria
metadata:
  name: scenario-67
spec:
  checks:
    - backend: kyverno-policy-report
      passingResult: pass
      policyName: container-security-controls
      resource:
        apiVersion: apps/v1
        kind: Deployment
        name: backend
        namespace: benchmarks
    - backend: opa-eval
      expectedRules: []
      passingResult: "true"
      policyName: service-account-requirements
