---
apiVersion: itbench.io/v2
kind: GroundTruth
metadata:
  name: scenario-67
spec:
  alerts: []
  entities:
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: backend
        namespace: benchmarks
  kubernetes:
    resources: []
  opa:
    checks: []
  solutions:
    - - steps:
          - command: kubectl -n benchmarks delete deployment backend
            text: Delete the non-compliant Pod.
          - text: Author and apply a policy that enforces the required security controls for the workload.
