---
apiVersion: itbench.io/v2
kind: Scenario
metadata:
  name: scenario-67
spec:
  applications:
  faults:
    - injections:
        - args:
            kubernetesObject:
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: backend
                namespace: benchmarks
          id: non-compliant-kubernetes-pod-deployment
  tools:
    ciso:
      enabled: true
