---
apiVersion: itbench.io/v2
kind: GroundTruth
metadata:
  name: scenario-36
spec:
  alerts:
    - labels: {}
      name: HighRequestErrorRate
  entities:
    - apiVersion: v1
      kind: Service
      metadata:
        name: details
        namespace: book-info
  solutions:
    - - steps:
          - command: kubectl -n book-info edit service details
            text: Manually edit the manifest and replace the selector with the correct value.
