---
- name: Import provisioning tasks
  ansible.builtin.import_tasks:
    file: provision.yaml
  tags:
    - grant_access

- name: Import deprovisioning tasks
  ansible.builtin.import_tasks:
    file: deprovision.yaml
  tags:
    - revoke_access
