---
- name: Set default agent version
  ansible.builtin.set_fact:
    awx_agent_version_normalized: 'default'

- name: Override agent version if provided and not empty
  ansible.builtin.set_fact:
    awx_agent_version_normalized: "{{ awx_agent.version }}"
  when:
    - awx_agent.version is defined
    - awx_agent.version | length > 0

- name: Update awx_agent with normalized version
  ansible.builtin.set_fact:
    awx_agent: "{{ awx_agent | combine({'version': awx_agent_version_normalized}) }}"
