---
- name: Run waiter tasks
  hosts:
    - localhost
  tasks:
    - name: Import waiters role
      ansible.builtin.import_role:
        name: waiters
      vars:
        waiters_cluster:
          kubeconfig: "{{ cluster.kubeconfig }}"
        waiters_tasks:
          - id: unassign-workload-container-resource-limits
            args:
              kubernetesObject:
                apiVersion: apps/v1
                kind: Deployment
                metadata:
                  name: compromised-workload
                  namespace: unassigned-k8-container-resource-limits-test
              container:
                name: server
