---
tools_releases:
  kyverno:
    name: kyverno
    namespace: kyverno
  cert_manager:
    name: cert-manager
    namespace: cert-manager
  chaos_mesh:
    name: chaos-mesh
    namespace: chaos-mesh
  alinity_clickhouse_operator:
    name: clickhouse-operator
    namespace: clickhouse-operator
  istio_base:
    name: istio-base
    namespace: istio-system
  istio_cni:
    name: istio-cni
    namespace:
      kubernetes: istio-system
      openshift: kube-system
  istio_istiod:
    name: istiod
    namespace: istio-system
  istio_ztunnel:
    name: ztunnel
    namespace:
      kubernetes: istio-system
      openshift: kube-system
  kube_prometheus_stack:
    name: prometheus
    namespace:
      kubernetes: prometheus
      openshift: openshift-user-workload-monitoring
  kubernetes_metrics_server:
    name: kube-metrics-server
    namespace: kube-metrics-server
  kubernetes_topology_monitor:
    name: kube-topology-monitor
    namespace: topology-monitor
  opencost:
    name: opencost
    namespace: opencost
  opensearch:
    name: opensearch
    namespace: opensearch
  opentelemetry_operator:
    name: opentelemetry-operator
    namespace: opentelemetry-operator

tools_namespaces:
  alinity_clickhouse: clickhouse
  kubernetes_gateway: kube-gateways
  opentelemetry_collector: opentelemetry-collectors

tools_operands:
  alinity_clickhouse:
    main:
      name: main
      namespace: "{{ tools_namespaces.alinity_clickhouse }}"
  opentelemetry_collector:
    istio:
      name: istio
      namespace: "{{ tools_namespaces.opentelemetry_collector }}"
    jaeger:
      name: jaeger
      namespace: "{{ tools_namespaces.opentelemetry_collector }}"
    kubernetes_events:
      name: kubernetes-events
      namespace: "{{ tools_namespaces.opentelemetry_collector }}"
    kubernetes_objects_snapshot:
      name: kubernetes-objects-snapshot
      namespace: "{{ tools_namespaces.opentelemetry_collector }}"

tools_kubernetes_gateways:
  istio:
    name: istio-main
    namespace: "{{ tools_namespaces.kubernetes_gateway }}"
