---
- name: Verify that wait task succeeded
  hosts:
    - localhost
  tasks:
    - name: Retrieve workload after restart
      kubernetes.core.k8s_info:
        api_version: apps/v1
        kind: Deployment
        name: test-workload
        namespace: restart-kubernetes-workload-test
        wait: true
      register: waiters_deployment

    - name: Validate that workload was restarted
      ansible.builtin.assert:
        that:
          - waiters_deployment.resources[0].metadata.generation == 2
          - waiters_deployment.resources[0].status.replicas == 2
          - waiters_deployment.resources[0].status.availableReplicas == 2
          - waiters_deployment.resources[0].status.readyReplicas == 2
        fail_msg: Workload was not restarted correctly. Waiter failed.
        success_msg: Workload successfully restarted.
