---
apiVersion: itbench.io/v2
kind: EvaluationCriteria
metadata:
  name: scenario-60
spec:
  checks:
    - alertName: KubeContainerWaiting
      backend: prometheus-alert-absent
    - alertName: KubePodNotReady
      backend: prometheus-alert-absent
