---
apiVersion: itbench.io/v2
kind: GroundTruth
metadata:
  name: scenario-38
spec:
  alerts:
    - labels: {}
      name: KubeHpaMaxedOut
  entities:
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: accounting
        namespace: otel-demo
    - apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: accounting
        namespace: otel-demo
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: ad
        namespace: otel-demo
    - apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: ad
        namespace: otel-demo
  solutions:
    - - steps:
          - command: kubectl -n otel-demo edit horizontalpodautoscaler accounting
            text: Manually edit the manifest and replace the utilization values with the correct values.
    - - steps:
          - command: kubectl -n otel-demo edit horizontalpodautoscaler ad
            text: Manually edit the manifest and replace the utilization values with the correct values.
