---
argument_specs:
  main:
    author:
      - Gerard Vanloo
    options:
      recorders_cluster:
        required: true
        type: dict
        options:
          kubeconfig:
            required: true
            type: str
          platform:
            choices:
              - kubernetes
              - openshift
            required: true
            type: str
      recorders_configuration:
        required: false
        type: dict
        options:
          phase:
            choices:
              - pre-fault-injection
              - pre-agent-injection
              - post-agent-execution
            required: true
            type: str
          tools:
            required: false
            type: dict
            options:
              finops:
                required: false
                type: dict
                options:
                  enabled:
                    default: false
                    required: false
                    type: bool
              sre:
                required: false
                type: dict
                options:
                  enabled:
                    default: false
                    required: false
                    type: bool
      recorders_vendors:
        required: false
        type: dict
        options:
          dynatrace:
            required: false
            type: dict
            options:
              recorder:
                required: false
                type: dict
                options:
                  enabled:
                    default: false
                    required: false
                    type: bool
                  platform_url:
                    required: false
                    type: str
                  platform_token_path:
                    required: false
                    type: str
                  namespace:
                    default: otel-demo
                    required: false
                    type: str
                  timeframe_to:
                    default: now
                    required: false
                    type: str
                  fallback_from:
                    default: now-1h
                    required: false
                    type: str
                  interval:
                    default: 1m
                    required: false
                    type: str
                  limit:
                    default: 1000
                    required: false
                    type: int
                  format:
                    choices:
                      - json
                      - csv
                      - both
                    default: both
                    required: false
                    type: str
      recorders_storage:
        required: false
        type: dict
        options:
          local:
            required: false
            type: dict
            options:
              directory:
                required: true
                type: str
          s3:
            required: false
            type: dict
            options:
              bucket:
                required: true
                type: str
              directory:
                required: true
                type: str
              endpoint:
                required: true
                type: str
