---
- name: Verify that fault injection succeeded
  hosts:
    - localhost
  tasks:
    - name: Retrieve injector job
      kubernetes.core.k8s_info:
        kubeconfig: "{{ cluster.kubeconfig }}"
        api_version: batch/v1
        kind: Job
        name: valkey-password-management
        namespace: valkey-workload-changed-password-test
      register: faults_job

    - name: Validate injector job completed successfully
      ansible.builtin.assert:
        that:
          - faults_job.resources | ansible.builtin.length == 1
          - faults_job.resources[0].status.succeeded == 1
        fail_msg: Injector job did not complete successfully. Fault injection failed.
        success_msg: Injector job completed successfully.

    - name: Create unauthenticated probe job
      kubernetes.core.k8s:
        kubeconfig: "{{ cluster.kubeconfig }}"
        resource_definition:
          apiVersion: batch/v1
          kind: Job
          metadata:
            name: valkey-auth-probe
            namespace: valkey-workload-changed-password-test
          spec:
            ttlSecondsAfterFinished: 10
            template:
              spec:
                restartPolicy: Never
                containers:
                  - name: probe
                    image: docker.io/valkey/valkey:9.1.2-alpine3.24@sha256:48332870af354a799964c0012ae1194a0bf2bf894eb508f945810596dc2d8d11
                    command:
                      - valkey-cli
                    args:
                      - -h
                      - compromised-workload.valkey-workload-changed-password-test.svc.cluster.local
                      - PING
        state: present
        wait: true
        wait_condition:
          type: Failed
          status: "True"
