---
- name: Destroy Kubernetes objects and directory
  hosts:
    - localhost
  tasks:
    - name: Destroy Namespace
      kubernetes.core.k8s:
        kubeconfig: "{{ cluster.kubeconfig }}"
        resource_definition:
          - apiVersion: v1
            kind: Namespace
            metadata:
              name: application
          - apiVersion: v1
            kind: Namespace
            metadata:
              name: observability
        state: absent
        wait: true

    - name: Delete test directory
      ansible.builtin.file:
        path: "{{ working_directory }}"
        state: absent
