---
- name: Verify that access was revoked correctly
  hosts:
    - localhost
  tasks:
    - name: Check token is no longer valid
      kubernetes.core.k8s:
        kubeconfig: "{{ cluster.kubeconfig }}"
        resource_definition:
          apiVersion: authentication.k8s.io/v1
          kind: TokenReview
          spec:
            token: |-
              {{
                (
                  lookup('ansible.builtin.file', kubeconfig_path) |
                  ansible.builtin.from_yaml
                ).users[0].user.token
              }}
        state: present
      register: agent_token_review
      vars:
        kubeconfig_path: "{{ [working_directory, 'kubeconfig'] | ansible.builtin.path_join }}"

    - name: Validate token was revoked
      ansible.builtin.assert:
        that:
          - agent_token_review.result.status.error is ansible.builtin.defined
          - not (agent_token_review.result.status.authenticated | ansible.builtin.default(false))
        fail_msg: Token is still valid. Revoke failed.
        success_msg: Token was revoked.

    - name: Retrieve ClusterRoleBinding
      kubernetes.core.k8s_info:
        kubeconfig: "{{ cluster.kubeconfig }}"
        api_version: rbac.authorization.k8s.io/v1
        kind: ClusterRoleBinding
        name: agent-cluster-access
      register: agent_cluster_role_binding

    - name: Validate ClusterRoleBinding was deleted
      ansible.builtin.assert:
        that:
          - agent_cluster_role_binding.resources | ansible.builtin.length == 0
        fail_msg: ClusterRoleBinding was not deleted. Revoke failed.
        success_msg: ClusterRoleBinding was successfully deleted.

    - name: Retrieve ClusterRole
      kubernetes.core.k8s_info:
        kubeconfig: "{{ cluster.kubeconfig }}"
        api_version: rbac.authorization.k8s.io/v1
        kind: ClusterRole
        name: agent-cluster-access
      register: agent_cluster_role

    - name: Validate ClusterRole was deleted
      ansible.builtin.assert:
        that:
          - agent_cluster_role.resources | ansible.builtin.length == 0
        fail_msg: ClusterRole was not deleted. Revoke failed.
        success_msg: ClusterRole was successfully deleted.

    - name: Retrieve ServiceAccount
      kubernetes.core.k8s_info:
        kubeconfig: "{{ cluster.kubeconfig }}"
        api_version: v1
        kind: ServiceAccount
        name: agent
        namespace: default
      register: agent_service_account

    - name: Validate ServiceAccount was deleted
      ansible.builtin.assert:
        that:
          - agent_service_account.resources | ansible.builtin.length == 0
        fail_msg: ServiceAccount was not deleted. Revoke failed.
        success_msg: ServiceAccount was successfully deleted.
