---
dependency:
  name: galaxy

ansible:
  executor:
    backend: ansible-playbook
    args:
      ansible_playbook:
        - --inventory=${MOLECULE_PROJECT_DIRECTORY}/../../inventory
  playbooks:
    converge: converge.yml
    create: create.yml
    destroy: destroy.yml
    verify: verify.yml

scenario:
  name: external_load_balancers
  test_sequence:
    - syntax
    - create
    - converge
    - verify
    - destroy
