---
- name: Manage SRE and FinOps Incident Data Recorder Stack
  hosts:
    - environment
  pre_tasks:
    - name: Import system role
      ansible.builtin.import_role:
        name: system
      tags:
        - always
      vars:
        system_cluster:
          kubeconfig: "{{ cluster.kubeconfig }}"

    - name: Import cluster role
      ansible.builtin.import_role:
        name: cluster
      tags:
        - always
      vars:
        cluster_files:
          kubeconfig: "{{ cluster.kubeconfig }}"
        cluster_tools_enabled:
          oc: "{{ system_oc_exists }}"
  tasks:
    - name: Import role variables from scenario
      when:
        - scenario_id is defined
      ansible.builtin.import_role:
        name: scenarios
      vars:
        scenarios_identifier: "{{ scenario_id }}"

    - name: Create default recorder configuration
      when:
        - scenario_id is undefined
      ansible.builtin.set_fact:
        scenarios_tools:
          clickhouse: false
          jaeger: false
          kubernetes_topology_monitor: false
          prometheus: false

    - name: Import leaderboard role
      ansible.builtin.import_role:
        name: leaderboard
      vars:
        leaderboard_status:
          status: progressing
        leaderboard_storage: "{{ storage }}"

    - name: Attempt to perform recorders role tasks
      block:
        - name: Import recorders role
          ansible.builtin.import_role:
            name: recorders
          vars:
            recorders_cluster:
              kubeconfig: "{{ cluster.kubeconfig }}"
              platform: "{{ cluster_platform }}"
            recorders_required:
              alerts:
                prometheus: "{{ scenarios_tools.prometheus | default(false) }}"
              topology:
                kubernetes: "{{ scenarios_tools.kubernetes_topology_monitor | default(false) }}"
              traces:
                jaeger: "{{ scenarios_tools.jaeger | default(false) }}"
              unified:
                clickhouse: "{{ scenarios_tools.clickhouse | default(false) }}"
            recorders_storage: "{{ storage }}"

        - name: Import leaderboard role
          ansible.builtin.import_role:
            name: leaderboard
          vars:
            leaderboard_status:
              status: succeeded
            leaderboard_storage: "{{ storage }}"
      rescue:
        - name: Import leaderboard role
          ansible.builtin.import_role:
            name: leaderboard
          vars:
            leaderboard_status:
              failed_task:
                name: "{{ ansible_failed_task.name }}"
                result: "{{ ansible_failed_result }}"
              status: failed
            leaderboard_storage: "{{ storage }}"

        - name: Fail playbook
          ansible.builtin.fail:
            msg: Playbook failed to complete successfully. Please check log for more info.
          tags:
            - always
