---
- name: Create OpenTelemetry Demo feature flag prerequisites
  hosts:
    - localhost
  tasks:
    - name: Create test namespace
      kubernetes.core.k8s:
        kubeconfig: "{{ cluster.kubeconfig }}"
        resource_definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: opentelemetry-demo-feature-flag-test
        state: present

    - name: Fetch flagd configuration from upstream chart at matching release tag
      ansible.builtin.uri:
        url: "https://raw.githubusercontent.com/open-telemetry/opentelemetry-helm-charts/opentelemetry-demo-0.40.10/charts/opentelemetry-demo/flagd/demo.flagd.json"
        return_content: true
      register: faults_flagd_upstream

    - name: Create flagd ConfigMap
      kubernetes.core.k8s:
        kubeconfig: "{{ cluster.kubeconfig }}"
        resource_definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: flagd-config
            namespace: opentelemetry-demo-feature-flag-test
          data:
            "demo.flagd.json": "{{ faults_flagd_upstream.content }}"
        state: present
