---
- name: Destroy OpenTelemetry Demo Application
  hosts:
    - localhost
  tasks:
    - name: Uninstall OpenTelemetry Demo (Astronomy Shop)
      kubernetes.core.helm:
        kubeconfig: "{{ cluster.kubeconfig }}"
        release_name: opentelemetry-demo-feature-flag-release
        release_namespace: opentelemetry-demo-feature-flag-test
        release_state: absent
        wait: true

    - name: Delete Namespace
      kubernetes.core.k8s:
        kubeconfig: "{{ cluster.kubeconfig }}"
        resource_definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: opentelemetry-demo-feature-flag-test
        state: absent
        wait: true
