---
- name: Converge
  hosts:
    - localhost
  tasks:
    - name: Print message
      ansible.builtin.debug:
        msg: LoadBalancer services are created. External IPs will be tested in verify phase.
