---
waiters_task_files:
  delete-workload-pods: wait_delete_workload_pods.yaml
  pause-execution: wait_pause_execution.yaml
  restart-kubernetes-workload: wait_restart_kubernetes_workload.yaml
  scale-kubernetes-workload: wait_scale_kubernetes_workload.yaml
