---
waiters_task_files:
  delete-workload-pods:
    wait: wait_delete_workload_pods.yaml
  pause-execution:
    wait: wait_pause_execution.yaml
  restart-kubernetes-workload:
    wait: wait_restart_kubernetes_workload.yaml
  scale-kubernetes-workload:
    wait: wait_scale_kubernetes_workload.yaml
