---
- name: Skip convergence
  hosts:
    - environment
  tasks:
    - name: Display message
      ansible.builtin.debug:
        msg: "Deployment completed in create phase. Proceeding to verification."
