---
dependency:
  name: galaxy

ansible:
  env:
    ANSIBLE_ROLES_PATH: ../../..
  executor:
    backend: ansible-playbook
    args:
      ansible_playbook:
        - --inventory=${MOLECULE_PROJECT_DIRECTORY}/../../../inventory
        - --tags=install_recorders,untagged
        - --extra-vars="out_directory=${MOLECULE_PROJECT_DIRECTORY}/test-recorders"
  playbooks:
    cleanup: cleanup.yml
    converge: converge.yml
    create: create.yml
    destroy: destroy.yml
    verify: verify.yml

scenario:
  name: deployment
  test_sequence:
    - syntax
    - create
    - converge
    - verify
    - cleanup
    - destroy
