name: Run ITBench Network Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - clusters/kind/go.*
      - scenarios/sre/project/roles/tools/**

concurrency:
  group: ci-network-${{ github.ref }}
  cancel-in-progress: true

jobs:
  environment-tools-gateway-kind:
    name: ITBench Environment Tools Gateway Network Tests on Kind
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: astral-sh/setup-uv@v9.0.0
      - uses: actions/setup-go@v7.0.0
        with:
          go-version-file: clusters/kind/go.mod
          cache-dependency-path: clusters/kind/go.sum
      - uses: azure/setup-helm@v5.0.1
        with:
          version: v4.2.3
      - name: Install project dependencies
        run: |
          make deps
      - name: Create group vars
        run: |
          make -C scenarios/sre group-vars
      - name: Create Kind cluster
        run: |
          make -C clusters/kind create-simple-cluster
      - name: Run Cloud Provider
        run: |
          make -C clusters/kind run-service-provider &
          sleep 10
      - name: Run connection tests
        run: |
          make -C scenarios/sre test-network-gateway
      - name: Destroy Kind cluster
        run: |
          make -C clusters/kind destroy-simple-cluster
