name: Run ITBench Unit Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - scenarios/sre/tools/kubernetes-topology-monitor-recorder/**
      - components/recorders/**
      - src/**
      - tests/**
      - pyproject.toml

concurrency:
  group: ci-unit-${{ github.ref }}
  cancel-in-progress: true

jobs:
  itbench-cli:
    name: ITBench CLI Unit Tests
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: astral-sh/setup-uv@1c37ad07a6a961277cf70c0d37d6f313000f5884 # v10.3.0
        with:
          version-file: pyproject.toml
      - name: Test
        run: uv run --group dev pytest

  kubernetes-topology-monitor-recorder:
    name: Kubernetes Topology Monitor Recorder Unit Tests
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: astral-sh/setup-uv@1c37ad07a6a961277cf70c0d37d6f313000f5884 # v10.3.0
        with:
          version-file: scenarios/sre/tools/kubernetes-topology-monitor-recorder/pyproject.toml
      - name: Test
        run: uv run python -m unittest discover -s . -p 'test_*.py'
        working-directory: scenarios/sre/tools/kubernetes-topology-monitor-recorder
