name: Run ITBench Integration Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - components/recorders/**

concurrency:
  group: ci-integration-${{ github.ref }}
  cancel-in-progress: true

jobs:
  clickhouse-recorder:
    name: ClickHouse Recorder Integration Tests
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: components/recorders/clickhouse/go.mod
          cache-dependency-path: components/recorders/clickhouse/go.sum
      - name: Vet
        run: go vet ./...
        working-directory: components/recorders/clickhouse
      - name: Test
        run: go test -count=1 ./...
        working-directory: components/recorders/clickhouse

  prometheus-recorder:
    name: Prometheus Recorder Integration Tests
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: components/recorders/prometheus/go.mod
          cache-dependency-path: components/recorders/prometheus/go.sum
      - name: Vet
        run: go vet ./...
        working-directory: components/recorders/prometheus
      - name: Test
        run: go test -count=1 ./...
        working-directory: components/recorders/prometheus
