name: Run ITBench Network Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - clusters/kind/go.*
      - scenarios/sre/project/roles/tools/**

concurrency:
  group: ci-network-${{ github.ref }}
  cancel-in-progress: true

jobs:
  environment-tools-gateway-kind:
    name: ITBench Environment Tools Gateway Network Tests on Kind
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7.0.0
      - uses: astral-sh/setup-uv@v8.3.0
      - uses: actions/setup-go@v6.5.0
        with:
          go-version-file: clusters/kind/go.mod
          cache-dependency-path: clusters/kind/go.sum
      - uses: azure/setup-helm@v5.0.1
        with:
          version: v4.2.2
      - name: Install project dependencies
        run: |
          make deps
      - name: Create group vars
        run: |
          make -C scenarios/sre group-vars
      - name: Create Kind cluster
        run: |
          make -C clusters/kind create-simple-cluster
      - name: Run Cloud Provider
        run: |
          make -C clusters/kind run-service-provider &
          sleep 10
      - name: Run connection tests
        run: |
          make -C scenarios/sre test-network-gateway
      - name: Destroy Kind cluster
        run: |
          make -C clusters/kind destroy-simple-cluster
  environment-tools-gateway-minikube:
    name: ITBench Environment Tools Gateway Network Tests on Minikube
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7.0.0
      - uses: astral-sh/setup-uv@v8.3.0
      - uses: azure/setup-helm@v5.0.1
        with:
          version: v4.2.2
      - uses: medyagh/setup-minikube@v0.0.21
        with:
          cache: false
          cni: cilium
          container-runtime: containerd
          driver: docker
          kubernetes-version: v1.35.0
          minikube-version: 1.38.1
          start: false
      - name: Install project dependencies
        run: |
          make deps
      - name: Create group vars
        run: |
          make -C scenarios/sre group-vars
      - name: Create Minikube cluster
        run: |
          make -C clusters/minikube create-simple-cluster
      - name: Start Minikube tunnel
        run: |
          make -C clusters/minikube start-simple-tunnel &
          sleep 10
      - name: Run connection tests
        run: |
          make -C scenarios/sre test-network-gateway
      - name: Destroy Minikube cluster
        run: |
          make -C clusters/minikube destroy-simple-cluster
