name: Perform SRE tool images build tests

on:
  pull_request:
    branches:
      - main
    paths:
      - components/**
      - scenarios/sre/tools/**
      - '!scenarios/sre/tools/kubernetes-topology-monitor/charts/kubernetes-topology-monitor/**'

concurrency:
  group: ci-sre-build-test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  kubernetes-topology-monitor:
    uses: ./.github/workflows/_build-image.yaml
    with:
      context: scenarios/sre/tools/kubernetes-topology-monitor
      image: quay.io/it-bench/topology-monitor
      tags: |
        quay.io/it-bench/topology-monitor:0.0.4
        quay.io/it-bench/topology-monitor:latest
      push: false

  kubernetes-topology-monitor-recorder:
    uses: ./.github/workflows/_build-image.yaml
    with:
      context: scenarios/sre/tools/kubernetes-topology-monitor-recorder
      image: quay.io/it-bench/kubernetes-topology-monitor-recorder
      tags: |
        quay.io/it-bench/kubernetes-topology-monitor-recorder:1.0.0
        quay.io/it-bench/kubernetes-topology-monitor-recorder:latest
      push: false
