name: Validate ITBench documentation

on:
  pull_request:
    branches:
      - main
    paths:
      - scenarios/library/**
      - scenarios/scripts/generate_library_*.py
      - scenarios/scripts/validate_library_*.py
      - scenarios/templates/documentation/**
      - scenarios/templates/library/**
      - scenarios/templates/schemas/**

jobs:
  validate-library:
    name: Validate documents
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: astral-sh/setup-uv@ae62891fec2bb8e7d6c99fc78c9fec3a63790f8d # v10.0.0
        with:
          version-file: pyproject.toml
      - name: Install project dependencies
        run: |
          make deps
      - name: Run validation scripts
        run: |
          make -C scenarios validate-library
